src/util/fd_util_base.h, src/util/log/test_log.c
These were discovered in manually running the unit tests over various compilers and machine targets when reviewing of Philip's store_if API.  The clang-15 symbol value mangling was pretty nasty to track down and fix.
=> Minor clang build cleanups

src/tango/tcache/BUILD
test_tcache was missing in CI tests. Fixes the Bazel automatic test config by using normal pages sizes instead.
=> tango: add automatic test_tcache Bazel config

.bazelignore
Checking the `firedancer` symlink into git meant there was an infinite symlink chain, which causes problems with Bazel. To avoid this, we don't check the symlink into git but instead create it on-demand.
=> firedancer-sys: fix "infinite symlink expansion detected" error

src/util/alloc/fd_alloc_ctl.c, src/util/alloc/test_alloc.c, src/util/wksp/fd_wksp.c, src/util/wksp/fd_wksp.h, src/util/wksp/fd_wksp_ctl.c, src/util/wksp/fd_wksp_ctl_help, src/util/wksp/fd_wksp_private.h, src/util/wksp/test_wksp.c, src/util/wksp/test_wksp_ctl
- By popular demand, added fd_wksp_usage API and "usage" command for getting summary usage reports programmatically and via command line.
- Tangentially related (because it could exploit the same tag set APIs added for usage), tweaked the fd_wksp_tag_free API to support freeing sets of tags at the same algo efficiency as a single tag.
- Tweaked test_wksp to allow unit tests to use an anonymous wksp to simplify CI integration and tweaked test_alloc unit test to match (which gives it some more flexibility to explore TLB and NUMA effects).
=> Added wksp usage summaries and related tweaks

src/ballet/base58/BUILD, src/ballet/base58/Local.mk, src/ballet/base58/fd_base58.c, src/ballet/base58/fd_base58.h, src/ballet/base58/fd_base58_avx.h, src/ballet/base58/fd_base58_tmpl.c, src/ballet/base58/test_base58.c
Add high performance base58 conversion functions (encode and decode) for 32 and 64 bytes.  The encoder functions have been especially optimized for AVX.
=> ballet: add base58 utils

shell.nix
Rational: 
> gcc-9.3 is in some sense the "official" one for gcc builds
```
(marcus/use-gcc930) » nix-shell --run 'gcc --version'
gcc (GCC) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
=> nix: use gcc-9.3.0

shell.nix
This reverts commit df32e0463d6baa04a37c334be2c8d30e01b6fd6f.
I think I misunderstood how nix channels work. Their behavior makes the most sense. We need to revert this previous PR until we pick a path forward.
=> Revert "nix: use gcc-9.3.0"

src/ballet/sha256/Local.mk, src/ballet/sha256/fd_sha256.h, src/ballet/sha256/fd_sha256_batch_avx.c, src/ballet/sha256/test_sha256.c, src/ballet/sha512/Local.mk, src/ballet/sha512/fd_sha512.h, src/ballet/sha512/fd_sha512_batch_avx.c, src/ballet/sha512/test_sha512.c
Supports high performance streaming and batching of large numbers of variable sized messages.  Optimized for the case of hashing same size or temporally clustered size messages.
Reference and single-threaded SIMD implementations provided.  The SIMD implementation requires FD_HAS_AVX platform capability but does not use any recent SHA instruction set extensions (so it will work on a broad range of Intel and AMD targets).
The user facing part of the API is designed to be easy to swap in (with minimal user code modifications) thread parallel implementations, hybrid thread parallel / data parallel implementation, hardware co-processor implementations (e.g. FPGA accelerated) implementations, etc.
The SIMD implementation is based on the new fangled vector uint / ulong SIMD stuff.  Basically …
=> Accelerated bulk SHA256 and SHA512 calculations

src/ballet/sha256/fd_sha256_batch_avx.c, src/ballet/sha512/fd_sha512_batch_avx.c
Faster memcpy and single pass processing of combined in-place bulk message region and out-of-place scratch tail region.
Worth ~10% for sha256 in the small message limit (~22 Mhash/s/core on the same host from original checkin).
=> Round of SHA performance tuning

src/util/bits/fd_bits.h
Further refines #249.
(Guess the earlier branch got merged before addressed the comments about finicky versions of gcc and clang.)
=> Unaligned and aliasing tweaks

src/funk/fd_funk_rec.c, src/funk/fd_funk_val.h
The fd_funk_val at line 532 was being called on rec, which was null and causing a core.
Also, the write call should be allowed to write upto the "max" of the record and should adjust the size as appropriate
=> simplified the rec_write_prepare helper

src/ballet/sha256/test_sha256.c, src/ballet/sha512/test_sha512.c
Adds test to ensure that SHA-256 and SHA-512 behave correctly for large hash inputs.
Covers an additional code path for SHA-256 testing that the size parameter in the Merkle–Damgård finalization overflows correctly for >4GiB inputs.
=> ballet: test sha for >4GiB inputs

.github/workflows/make_coverage.yml, .github/workflows/make_test.yml
Does what it says on the tin. This is done so that shared memory pages are not exhausted.
=> limit test run concurrency

src/app/frank/fd_frank_verify.c, src/disco/quic/fd_quic_tile.c, src/tango/fd_tango_base.h
The way read/write access to dcache chunks is synchronized is via. the mcache. The assumptions is if an mcache points at some chunk, it is valid to read (as long as the mcache stays pointing there). So to start writing to a chunk, we need to find whoever pointed to that chunk before and point them somewhere else (the mechanism for this is just incrementing their seq number.)
The process of "finding" who pointed there is simple, if the dcache is always larger than the mcache, then so long as we always increment the seq number of the next mcache entry before incrementing the chunk we are writing to, the readers will always be evicted before we write.
The QUIC tile here was writing to some dcache chunks without having to increment the mcache seq number which caused corrupt frags. The fix is …
=> quic: prevent quic tile from overwriting chunks owned by the verify tile

src/util/simd/fd_avx_wb.h, src/util/simd/fd_avx_wc.h, src/util/simd/fd_avx_wu.h, src/util/simd/fd_sse_vb.h, src/util/simd/fd_sse_vc.h, src/util/simd/test_avx_32x8.c, src/util/simd/test_avx_common.c, src/util/simd/test_sse_16x8.c, src/util/simd/test_sse_common.c
(Part of the reedsol review)
- Completed the constructor family for making uchar SIMD vectors from 8 and/or 16 scalars and gave the constructors cleaned up consistent names (we should update existing SIMD constructors to use this more generalizable convention at some point).
- Naming consistency for right shifts shifts with wu_t and vu_t and filled in missing rotate support.
- Added some missing converters and made the converter macros robust (we should add converters from the other types into this type too at some point).
- Moved the vb_test to test_sse_common in anticipation of converters in the other direction.
- Test coverage updated to cover all the above.
- Minor comment cleanups.
=> uchar SIMD implementation polishing

config/with-brutality.mk, config/with-extra-brutality.mk
Moves some commented out flags into their own optional config.
To use this during build:
```
EXTRAS=extra-brutality make -j
```
=> build: add extra-brutality config

src/util/shmem/fd_shmem_cfg
Some minimal cloud host setups do not install "free" utility in procps-ng by default.  But fd_shmem_cfg used this to get the total amount of system memory (used to size the huge and gigantic hugetlbfs mounts).  And every time a dependency is eliminated an angel gets its wings.
This extracts the amount of system memory from /proc/meminfo instead (and also traps if this does not work).
Feels like there should be a simple method to robustly, portably and script-friendly query the amount of memory in the system and then without needing to scrape via tools like awk the value from diagnostic strings meant to be read by people.
=> Eliminate dependency on procps-ng

.github/workflows/make_test.yml
Does what it says on the tin. That's useful for the XDP tests.
=> ci: run tests as root

src/ballet/sbpf/fd_sbpf_loader.c, src/ballet/sbpf/fd_sbpf_loader.h, src/ballet/sbpf/fuzz_sbpf_loader.c, src/ballet/sbpf/test_sbpf_load_prog.c, src/ballet/sbpf/test_sbpf_loader.c, src/ballet/utf8/Local.mk, src/ballet/utf8/fd_utf8.c, src/ballet/utf8/fd_utf8.h, src/ballet/utf8/fuzz_utf8_check_cstr.c, src/ballet/utf8/test_utf8.c
- utf8: add fd_utf8_check_cstr
- sbpf: loader refactor and improvements
- add UTF-8 validation
- move rodata segment into separate memory region
and remove zero-copy / masking logic
- fix various diff fuzz findings
=> sbpf: loader improvements

src/app/fdctl/config/default.toml, src/app/fdctl/src/commands/configure/ethtool.rs, src/app/fdctl/src/commands/configure/large_pages.rs, src/app/fdctl/src/commands/configure/netns.rs, src/app/fdctl/src/commands/configure/xdp_leftover.rs, src/app/fdctl/src/commands/run.rs, src/app/fdctl/src/config.rs, src/app/fdctl/src/utility.rs
If we are using a bonded device, we need to ensure the number of channels on the underlying ethernet devices is the same as the number of QUIC tiles or we may drop packets when they get put into a queue we are not reading.
=> fdctl: support bonded interface

config/everything.mk, config/with-ffi.mk, ffi/rust/firedancer-diff/Cargo.toml, ffi/rust/firedancer-sys/Cargo.toml, ffi/rust/firedancer-sys/build.rs, ffi/rust/firedancer-sys/src/ballet/sbpf.rs, ffi/rust/firedancer-sys/src/lib.rs, ffi/rust/firedancer-sys/src/tango/cnc.rs, ffi/rust/firedancer-sys/src/tango/dcache.rs, ffi/rust/firedancer-sys/src/tango/fseq.rs, ffi/rust/firedancer-sys/src/tango/mcache.rs, ffi/rust/firedancer-sys/src/util/bits.rs, ffi/rust/firedancer-sys/src/util/pod.rs, ffi/rust/firedancer-sys/src/util/shmem.rs, ffi/rust/firedancer-sys/src/util/wksp.rs, ffi/rust/firedancer-sys/wrapper_ballet.h, ffi/rust/firedancer-sys/wrapper_disco.h, ffi/rust/firedancer-sys/wrapper_tango.h, ffi/rust/firedancer-sys/wrapper_util.h, src/ballet/Local.mk, src/ballet/sbpf/fd_sbpf_loader.c, src/disco/Local.mk, src/tango/Local.mk, src/util/Local.mk
An extreme pain. More painful than it should be. The problem here is we want to call static inline functions from Rust, but the Rust C ffi is link time, not compile time, so the static inline symbols do not exist.
Bindgen has an experimental `wrap_static_fns` flag which basically, for every `static inline fn()` it sees when parsing, spits out a `fn_extern()` implementation with extern linkage, which just calls the `static inline`. It dumps these functions into a translation unit we give it.
Here's a problem. It produces just one TU, but we have several libraries. If we include the same TU in each of the libraries, we won't be able to link them, since they redefine the same symbols.
To fix this, ideally we will just call bindgen four times, and produce four separate TUs, each with just the …
=> ffi: export static inline functions

contrib/gen-pem-cert.sh, src/app/fdctl/src/commands/configure/certs.rs
Add `-extensions v3_req` so that the generated cert is set to `CA:false`
=> fix: openssl-req v3 (for CA:false)

contrib/gen-pem-cert.sh, src/app/fdctl/src/commands/configure/certs.rs
- contrib: add gen-pem-cert.sh
- fix: openssl-req v3 (for CA:false) (#417)
Adds helper script generating a Solana-compatible PEM cert for QUIC-TLS. From milestone 1.1 branch
=> contrib: add gen-pem-cert.sh

config/everything.mk
Uses a link group for internal libs such as fd_tango, fd_ballet, etc
to resolve "symbol not found" errors resulting from incorrect static
lib ordering.  Also useful for circular dependencies (which should be
avoided, but oh well...)
=> config: support order-independent static linking

src/app/fdctl/config/default.toml, src/app/fdctl/config/development.toml, src/app/fdctl/src/commands/run.rs, src/app/fdctl/src/config.rs, src/app/frank/fd_frank_main.c, src/app/frank/fd_frank_mon.bin.c, src/util/env/fd_env.c, src/util/env/fd_env.h, src/util/env/test_env.c, src/util/fd_util.c, src/util/fd_util.h, src/util/log/fd_log.c, src/util/sandbox/Local.mk, src/util/sandbox/fd_sandbox.c, src/util/sandbox/fd_sandbox.h, src/util/sandbox/test_sandbox.c, src/util/wksp/fd_wksp.h, src/util/wksp/fd_wksp_helper.c
The purpose of the sandbox is to reduce the impact of a Firedancer compromise.
When starting, before executing any task code and/or processing user-provided input, a Firedancer process prepares everything it needs in order to function properly. This initialization mostly consists in:
* Creating new tiles which will be used for task execution (clone syscall)
* Opening the relevant workspaces which will be used to perform work and communicate (mmap syscall)
* Immediately after performing those operations, Firedancer sandboxes itself. Note that firedancer has to be started as root or with various capabilities in order to be able to sandbox itself.
Here are the mechanisms currently used by Firedancer to achieve sandboxing:
* The environment variable are cleared. Environment variables are …
=> sandbox: sandbox implementation

src/app/fdctl/src/commands/configure/frank.rs, src/tango/quic/fd_quic.c, src/tango/quic/fd_quic.h, src/tango/quic/tests/fd_quic_test_helpers.c, src/tango/quic/tests/test_handshake.c, src/tango/quic/tls/fd_quic_tls.c, src/tango/quic/tls/fd_quic_tls.h, src/util/pod/fd_pod_ctl.c
With the sandbox changes in place, QUIC will not be able to open files so the cert/key need to provided in-memory. This makes sense anyway since these should always be generated on the fly and not persisted.
=> quic: support loading key/cert from memory

src/app/fdctl/config/default.toml, src/app/fdctl/src/config.rs
If no interface is specified, we find a default one by looking at which device is used for the default route to 8.8.8.8
=> fdctl: determine bind interface automatically

src/util/sandbox/fd_sandbox.c
All file descriptors in the process should already be open once we go to install seccomp, so we can just set the file limit to zero.
=> sandbox: restrict RLIMIT_NOFILE to 0

.github/workflows/codeql.yml
This check is broken on main. Should be readded once fixed.
=> ci: remove CodeQL from merge_group

src/app/fdctl/config.c, src/app/fdctl/fdctl.h, src/app/fdctl/utility.h
1 - config_parse did not correctly set quic ip address and mac address when development.netns.enabled = true
2 - RUN failed when exit code was zero
3 - replace did not substitute the pattern correctly
Testing output
```bash
llamb@emny-ossdev-firedancer11> /home/llamb/code/firedancer-public/build/native/gcc/bin/fdctl configure fini all
--log-path not specified; using autogenerated path
Log at "/tmp/fd-0.0.0_1894263_llamb_emny-ossdev-firedancer11_2023_07_19_18_43_23_056378245_GMT+00"
--log-path not specified; using autogenerated path
Log at "/tmp/fd-0.0.0_1894265_root_emny-ossdev-firedancer11_2023_07_19_18_43_23_067081830_GMT+00"
NOTICE  07-19 18:43:23.068052 1894265 f0   0    src/app/fdctl/configure/configure.c(148): large-pages ... finishing
NOTICE  07-19 18:43:23.068086 1894265 f0   0 …
```
=> three bug fixes for fdctl

src/app/fdctl/configure/frank.c, src/app/frank/fd_frank_quic.c
initial_rx_max_stream_data was uninitialized in fd_frank_quic which caused streams to not transmit any data
pod configuration firedancer.quic_cfg.initial_rx_max_stream_data now defaults to 32k (1<<15)
=> quic bugfix - client streams don't transmit data 

.github/workflows/make_test.yml
It seems that, by omitting to specify the shell, the GitHub action runner will set its own shell with its own limit, ignoring `/etc/security/limits.conf`.
=> set the default shell

src/app/fddev/dev1.c
Refactor had messed up the `dev1` command by not passing the correct arguments.
=> fdctl: fix dev1 error about null workspace

src/app/fdctl/fdctl.h, src/app/fdctl/monitor/monitor.c, src/app/fdctl/run.c, src/app/fdctl/run.h, src/app/frank/fd_frank.h, src/app/frank/fd_frank_dedup.c, src/app/frank/fd_frank_pack.c, src/app/frank/fd_frank_quic.c, src/app/frank/fd_frank_verify.c, src/disco/dedup/fd_dedup.c, src/disco/dedup/fd_dedup.h, src/disco/dedup/fd_dedup_tile.c, src/disco/dedup/test_dedup.c, src/disco/quic/fd_quic.h, src/disco/quic/fd_quic_tile.c, src/disco/quic/test_quic_tile.c
Nanosleep was only needed on these tiles due to fd_tempo calibration, which can happen once on boot before we enter the sandbox anyway.
=> fdctl: remove nanosleep syscall

src/app/fdctl/monitor/monitor.c, src/app/fdctl/run.c, src/app/frank/fd_frank_dedup.c, src/app/frank/fd_frank_pack.c, src/app/frank/fd_frank_quic.c, src/app/frank/fd_frank_verify.c, src/util/log/fd_log.c, src/util/log/fd_log.h
There's a few problems with the existing implementation,
* `fprintf` is not async signal safe according to POSIX.1, but `write()` is. If we try to log from a signal handler (which we do), it might operate on a half written buffer and cause corruption.
* `fprintf` uses a lock internally to sequence writes, but this lock is within a process, not across processes. Because all Firedancer tiles run in different processes the locking has no effect and messages may get interleaved.
* `fprintf` uses a CAS spinlock internally, which is good, but if it spins too many times will switch to a futex which is bad for us. It requires whitelisting the `futex` syscall in our seccomp profile, and also has a performance overhead. We are already pinning cores so it is OK to spin until we can lock.
* `fprintf` …
=> util: switch log to use posix file api

src/app/fdctl/main.c, src/app/fdctl/monitor/monitor.c, src/app/fdctl/run.c, src/app/fddev/dev.c, src/app/fddev/main.c, src/app/frank/fd_frank.h, src/app/frank/fd_frank_dedup.c, src/app/frank/fd_frank_pack.c, src/app/frank/fd_frank_quic.c, src/app/frank/fd_frank_verify.c, src/tango/xdp/fd_xdp_redirect_user.c, src/util/sandbox/fd_sandbox.c, src/util/sandbox/fd_sandbox.h, src/util/sandbox/test_sandbox.c
It makes more sense for tiles to specify what file descriptors they expect to be open, not to just randomly close stuff and hope its secure.
=> sandbox: rework open file descriptor closing

src/util/Local.mk, src/util/bits/fd_bits.h, src/util/bits/test_bits.c, src/util/log/fd_log.c, src/util/pod/fd_pod_ctl.c, src/util/pod/fd_pod_ctl_help, src/util/pod/test_pod_ctl, src/util/shmem/fd_shmem_admin.c, src/util/test_util_base.c, src/util/tile/fd_tile_threads.cxx
Bunch of minor housekeeping cleanups to some recent PRs and some additional helpers for upcoming PRs.
- bits: pow2_dn support (for upcoming PRs)
- bits: swap / branchless conditional swap (for upcoming PRs)
- log: support for targets with FD_HAS_ATOMIC (related conversing to POSIX style I/O)
- pod: help docs and unit test coverage for insert-file command and minor optimization
- shmem: pedantic error trapping of mutex initializer (related to removal of the NP static initializer for musl support)
- test_util_base: do not build under UBSAN as this deliberately probes UB/IB behaviors (related to ubsan build targets)
- tile: set affinity after tile boot when not running under glibc (related to removal of NP pthread attr for musl support)
=> Housekeeping cleanups

src/util/tmpl/fd_treap.c, src/util/tmpl/test_treap.c
Just changes the comment because it was actually already supported. Adds a test.
When you delete, other than the deleted element, none of the tree nodes change in binary search tree order. In particular, the heap adjustments don't change the order, even when elements have equal keys. Since the iteration only depends on binary search order, deleting an element does not affect iteration.
The behavior of deleting while iterating is pretty intuitive. If you delete something behind the iterator, there's no effect. If you delete something in front of the iterator, then you won't iterate over it when you would have gotten there. You can't delete the current position of the iterator.
=> util/tmpl: allow deleting from treap while iterating

src/app/fdctl/config.c, src/app/fdctl/config.h, src/app/fdctl/config/default.toml, src/app/fdctl/configure/workspace.c, src/app/fdctl/monitor/helper.c, src/app/fdctl/monitor/helper.h, src/app/fdctl/monitor/monitor.c
Various issues with the monitor are fixed, including,
* It would write to the terminal unbuffered using printf, which is slow but also would cause screen tearing. Switched to use a full size buffer for output. This also fixed the issues with xterm so it no longer flickers.
* Fixed Ctrl+C to leave a clean terminal behind with just one buffer of output.
* Removed cursor while drawing to prevent it blinking around randomly.
* Increased default refresh rate 10x.
* Tidied up the code structure to have `tile_t` and `link_t` types for the two output formats. Tiles no longer dump information that really belongs to links (in seq, out seq), since a tile can have multiple in/out links now it doesn't make sense.
* Reworked the IPC object finding to be much cleaner using the workspace definitions in …
=> monitor: improve performance and stability

config/everything.mk, src/app/fdctl/fdctl.h, src/app/fdctl/monitor/helper.h, src/app/fdctl/monitor/monitor.c, src/app/fdctl/run.c, src/app/fddev/dev.c, src/app/fddev/fddev.h, src/app/fddev/main.c
`fddev dev` gets an argument `--monitor` which combines both running and monitoring in one command. Basically, it spawns them each in a separate process, and wires stdout from Firedancer to a pipe in the monitor so the log messages can be cleanly written between output refreshes.
=> fdctl: add combined run and monitor command

config/everything.mk, config/linux_clang_minimal.mk, config/linux_gcc_minimal.mk, config/with-extra-brutality.mk, src/util/alloc/test_alloc_ctl, src/util/fd_util.h, src/util/io/Local.mk, src/util/io/fd_io.c, src/util/io/fd_io.h, src/util/io/test_io.c, src/util/log/fd_log.c, src/util/log/fd_log.h, src/util/log/test_log.c, src/util/wksp/Local.mk, src/util/wksp/fd_wksp.h, src/util/wksp/fd_wksp_admin.c, src/util/wksp/fd_wksp_ctl.c, src/util/wksp/fd_wksp_ctl_help, src/util/wksp/fd_wksp_io.c, src/util/wksp/fd_wksp_private.h, src/util/wksp/fd_wksp_user.c, src/util/wksp/test_wksp_ctl, src/util/wksp/test_wksp_user.c
To do this robustly, needed some lower level APIs and missing functionality filled out.  The most important ones:
- Generic buffered I/O APIs with implementation for POSIX systems.
- Build environment details programmatic exposed.
- Can lookup an wksp allocation by its tag to make various discovery processes at application startup cleaner.
=> Wksp checkpt / restore support

src/app/fdctl/config.c, src/app/fdctl/config.h, src/app/fdctl/config/default.toml, src/app/fdctl/configure/workspace.c, src/app/fdctl/monitor/monitor.c, src/app/fdctl/run.c, src/app/fddev/configure/cluster.c, src/app/fddev/dev.c, src/app/frank/fd_frank.h, src/app/frank/fd_frank_dedup.c, src/app/frank/fd_frank_pack.c, src/app/frank/fd_frank_quic.c, src/app/frank/fd_frank_verify.c
A shared workspace is added for the QUIC, verify, dedup, and pack tiles so that they can share dcache entries and not copy transactions back and forth.
=> fdctl: separate workspace for transaction pipeline

.github/workflows/functional_tests.yml, src/tango/xdp/fd_xdp_redirect_user.c, src/test/frank-single-transaction.sh
This PR reverts https://github.com/firedancer-io/firedancer/pull/504 because it broke `fddev1`.
We need to add it back now that `fddev` is in a testable, working state.
=> update frank-single-transaction.sh workflow to run on github runners

.github/workflows/make_daily.yml, .github/workflows/scripts/fuzzcov_generate.sh, .github/workflows/scripts/fuzzcov_genhtml.sh, .github/workflows/scripts/fuzzcov_publish_codecov.sh
This PR upgrades the daily workflow so that it:
- for each fuzzing target:
- pulls corpus from ClusterFuzz
- runs the whole corpus through the target
- compiles coverage
- publishes coverage to https://app.codecov.io/github/firedancer-io/firedancer
- generates lcov-genhtml reports to `build/pages/fuzzcov`
- generates an index for `fuzzcov/`
- publishes `build/pages` to https://firedancer-io.github.io/
https://vigilant-carnival-vrqv8pw.pages.github.io/fuzzcov/
=> Fuzz: Generate reports

src/app/fdctl/config.c, src/app/fdctl/config.h, src/app/fdctl/config/default.toml, src/app/fdctl/configure/workspace.c, src/app/fdctl/configure/xdp.c, src/app/fdctl/run.c, src/app/frank/fd_frank.h, src/app/frank/fd_frank_quic.c, src/disco/quic/fd_quic.h, src/disco/quic/fd_quic_tile.c, src/disco/quic/test_quic_tile.c, src/tango/quic/tests/fd_quic_test_helpers.c, src/tango/quic/tests/test_quic_txn.c, src/tango/xdp/fd_xdp_ctl.c, src/tango/xdp/fd_xdp_redirect_user.c, src/tango/xdp/fd_xdp_redirect_user.h, src/test/frank-single-transaction.sh
The Linux kernel does some short circuiting optimizations when sending packets to an IP address that's owned by the same host. The optimization is basically to route them over to the loopback interface directly, bypassing the network hardware.
This redirection to the loopback interface happens before XDP programs are executed, so local traffic destined for our listen addresses will not get ingested correctly.
There are two reasons we send traffic locally,
* For testing and development.
* The Solana Labs code sends local traffic to itself to as part of routine operation (eg, when it's the leader it sends votes to its own TPU socket).
So for now we need to also bind to loopback. This is a small performance hit for other traffic, but we only redirect packets destined for our target IP and …
=> xdp: also listen on loopback by default

src/app/fdctl/config/default.toml, src/app/fdctl/configure/configure.c, src/app/fdctl/configure/configure.h, src/app/fdctl/configure/workspace.c, src/app/fdctl/run.c, src/app/fddev/Local.mk, src/app/fddev/configure/genesis.c, src/app/fddev/main.c
When creating a genesis block, hashes per tick of "auto" was causing the genesis to not work correctly. Switching this to "sleep" like the Solana Labs run.sh command fixes the problem. Also fixed some other issues,
* Fixed issue with affinity not matching number of tiles, due to new tiles not getting counted correctly.
* Fixed problem where fini destructors were run in the wrong order (they should run in reverse).
* Fixed issue where if workspace creation was killed while in-progress, the workspace would have "bad magic" and be undeleteable.
* Renamed cluster stage to genesis to better reflect what it does.
* Fixed problem where genesis creation spawned many threads into the Firedancer root process, causing sanboxing to fail later.
* Fixed issue where genesis was not being re-created …
=> fdctl: create genesis correctly

src/app/fdctl/Local.mk, src/app/fdctl/config.h, src/app/fdctl/configure/configure.h, src/app/fdctl/configure/large_pages.c, src/app/fdctl/configure/sysctl.c, src/app/fdctl/configure/xdp.c, src/app/fdctl/fdctl.h, src/app/fdctl/main1.c, src/app/fdctl/ready.c, src/app/fdctl/run.c, src/app/fddev/Local.mk, src/app/fddev/dev.c, src/app/fddev/fddev.h, src/app/fddev/main.c, src/app/fddev/txn.c, src/app/frank/fd_frank_quic.c, src/tango/xdp/fd_xdp_redirect_user.c, src/test/frank-single-transaction.sh
`fdctl ready` waits until all tiles being booted by the systeme are ready to accept transactions.  Currently ignores the bank tile since it takes a while to start and will get backpressured so it doesn't really matter if it's booted anyway.
The `txn` command is stolen from `test_quic_txn.c` but integrates nicely with `fddev` so that it automatically targets the right endpoint and can be run easily.
=> fdctl: add ready and txn commands

.github/workflows/make_daily.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: write output command to GITHUB_OUTPUT

config/everything.mk
```
~/src/firedancer (main*) » make EXTRA_CPPFLAGS="LOOKHERE"
gcc -isystem ./opt/include -DFD_LOG_UNCLEAN_EXIT=1 -march=native -mtune=native -Werror -Wall -Wextra -Wpedantic -Wstrict-aliasing=2 -Wconversion -Wdouble-promotion -Wformat-security -Wimplicit-fallthrough -Wimplicit-fallthrough=2 -O3 -ffast-math -fno-associative-math -fno-reciprocal-math -DFD_HAS_OPTIMIZATION=1 -g -DFD_HAS_INT128=1 -DFD_HAS_DOUBLE=1 -DFD_HAS_ALLOCA=1 -DFD_HAS_THREADS=1 -DFD_HAS_OPENSSL=1 -DFD_HAS_X86=1 -DFD_HAS_SSE=1 -DFD_HAS_AVX=1 -DFD_IS_X86_64=1 -D_XOPEN_SOURCE=700 -DFD_HAS_HOSTED=1 -pthread -DFD_HAS_THREADS=1 -DFD_HAS_ATOMIC=1 -DFD_HAS_OPENSSL=1 -DOPENSSL_API_COMPAT=0x10100000L -DOPENSSL_SUPPRESS_DEPRECATED -fomit-frame-pointer -mfpmath=sse -falign-functions=32 -falign-jumps=32 -falign-labels=32 …
```
=> make it simple to add extra cppflags

README.md, ffi/rust/firedancer-sys/src/tango/mod.rs, ffi/rust/firedancer-sys/src/tango/mvcc.rs, src/tango/fd_tango.h, src/tango/mvcc/Local.mk, src/tango/mvcc/fd_mvcc.c, src/tango/mvcc/fd_mvcc.h, src/tango/mvcc/test_mvcc.c
A primitive is added for versioning data for single-producer multi-consumer contexts.  This is designed for use between Solana Labs and Firedancer for passing information like stake weights and the leader schedule which Firedancer cannot yet derive independently.
=> tango: add multi version concurrency control (mvcc)

src/tango/quic/fd_quic.c
fix firedancer-io/auditor-internal#5
=> fix(quic): missing NULL check in fd_quic_conn_close

src/ballet/ed25519/fd_ed25519_user.c
=> [ed25519] use FD_ED25519_ERR_SIG instead of 0 on return

.github/workflows/publish_fuzz_targets.yml
The value is instead provided by the Docker image which is aware of which packages provides the headers.
=> ci: do not provide extra_cppflags from job

config/everything.mk
As requested by @lheeger-jump, it writes finding in the appropriate corpus directory.
=> fuzz: crash file destination

src/tango/ip/Local.mk, src/tango/ip/fd_ip.c, src/tango/ip/fd_ip.h, src/tango/ip/fd_netlink.c, src/tango/ip/fd_netlink.h, src/tango/ip/test_arp, src/tango/ip/test_arp.c, src/tango/ip/test_ip, src/tango/ip/test_ip.c, src/tango/ip/test_netlink.c, src/tango/ip/test_routing.c
This PR adds functionality to do the following, needed for XDP kernel bypass:
Fetch ARP and Routing tables from the kernel via Netlink
Run a routing algo for an IP address
generate an ARP request
prime the kernel ARP table to accept an ARP response for a specific IP address
It is only intended to support Ethernet and IPv4
=> IP stack - ARP and routing table

src/tango/ip/fd_netlink.c
I got this error while building because I had an older version of gcc (8.5.0) set as the default. I know this isn't our target compiler, but it still seems like an easy fix.
=> fd_netlink: fix warning in older GCC

ffi/rust/firedancer-sys/src/ballet/shred.rs, src/ballet/shred/Local.mk, src/ballet/shred/fd_shred.c, src/ballet/shred/fd_shred.h, src/ballet/shred/fuzz_shred_parse.c, src/ballet/shred/test_shred.c
Basically rewrote the parsing function, added a fuzzer. 
Other assorted small changes, mostly changes that Richie made, plus a few fixes, many of which Josh also made
Note: Way back when, Tom suggested some changes on #123 that we never made, but it's nothing critical.
=> fd_shred: tighten parse constraints, other small changes

src/util/tmpl/fd_deque_dynamic.c, src/util/tmpl/test_deque_dynamic.c
Kevin and I discussed some issues with fd_deque_dynamic and he suggested some changes. Previously iterating over a full deque would return 0 elements.
=> fd_deque_dynamic: fix iteration on full deque

src/tango/quic/fd_quic.c, src/tango/quic/templ/fd_quic_encoders.h
https://github.com/firedancer-io/auditor-internal/issues/4
=> FD_TEMPL_MBR_ELEM_{VAR,ARRAY} encoding lacks a boundary check #4. Also made zero_rtt return FD_QUIC_PARSE_FAIL instead of zero to avoid looping.

src/tango/quic/fd_quic.c, src/tango/quic/fd_quic_proto.h, src/tango/quic/tests/fuzz_quic.c, src/tango/udpsock/fd_udpsock.c, src/tango/udpsock/test_udpsock_echo.c, src/tango/xdp/test_xsk_aio_echo_rx.c, src/util/net/fd_igmp.h, src/util/net/fd_ip4.h, src/util/net/fd_pcap.c, src/util/net/test_ip4.c
UBSAN kicked out a lot of unaligned access UB cases. In preference for keeping the warnings/errors/UB to a minimum/zero I have "fixed" a number of them. In some key areas I ensured that the output of several versions of gcc and clang produce good output, particularly in eliding the memcpys.
Note: using fd_memcpy would prevent the compiler from eliding them.
=> quic - fix alignment issues

src/app/fdctl/run/run.c, src/app/fddev/dev.c, src/util/log/fd_log.c, src/util/log/fd_log.h
If a child process is holding the lock for the log, and then the process tree is killed (due to Ctrl+C, or another process terminates), it will die holding the lock, and the process supervision infrastructure will hang trying to print some last diagnostics.
=> log: don't lock the log after subprocess termination

src/ballet/chacha20/fd_chacha20rng.h, src/ballet/chacha20/test_chacha20rng_roll.c
Kevin noticed that the addition to form `lh` could overflow and reminded me about `fd_uwide`. The existing tests weren't exhaustive enough to catch the mistake, so I added one that does catch it.
=> chacha20: fix potential overflow

src/util/pod/fd_pod.h
`fd_pod_query_buf` writes to `opt_buf_sz` if it is non-NULL, and thus isn't a pure function according to the GCC manual
=> fd_pod: remove FD_FN_PURE from fd_pod_query_buf

config/base.mk, src/util/wksp/fd_wksp_admin.c
This doesn't make sense within the sandbox, we cannot see or check if another process is alive, and all processes have a PID of 0 anyway since they are within their own PID namespace. The operating model of Firedancer will bring all processes down together if one of them crashes so it's OK to just not run this logic.
=> wksp: add compile time option to avoid lock reclamation

.github/workflows/functional_tests.yml, src/test/single-transaction.sh
An example of a failed pipeline due to a bad syscall https://github.com/firedancer-io/firedancer/actions/runs/6501223757/job/17658136990?pr=766#step:7:779
```
52:type=SECCOMP msg=audit(1697147265.298:78): auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=unconfined pid=53620 comm="fddev" exe="/home/runner/work/firedancer/firedancer/build/native/gcc/bin/fddev" sig=31 arch=c000003e syscall=1 compat=0 ip=0x7fad80314a37 code=0x80000000AUID="unset" UID="runner" GID="runner" ARCH=x86_64 SYSCALL=write
```
A bad syscall to `write`.
=> Output audit.log in CI to help with debugging bad syscalls

src/app/fdctl/config.c, src/app/fdctl/config.h, src/app/fdctl/config/default.toml, src/app/fdctl/configure/workspace.c
Testing
After adding an invalid key to `default.toml` we get the following output
```
llamb@emny-ossdev-firedancer11> fddev
--log-path not specified; using autogenerated path
Log at "/tmp/fd-0.0.0_577344_llamb_emny-ossdev-firedancer11_2023_10_18_04_22_27_927939606_GMT+00"
ERR     10-18 04:22:27.928847 577344 f0   main src/app/fdctl/config.c(416): Error while parsing the embedded configuration. The configuration had an unrecognized key [tiles.quic.wat].
```
Doing the same test but after copying `default.toml` to `/tmp`
```
llamb@emny-ossdev-firedancer11> fddev --config /tmp/default.toml
--log-path not specified; using autogenerated path
Log at "/tmp/fd-0.0.0_578027_llamb_emny-ossdev-firedancer11_2023_10_18_04_23_58_023990675_GMT+00"
ERR     10-18 04:23:58.024996 578027 f0   main …
```
=> change toml parsing to fail on unrecognized keys

src/app/fddev/configure/genesis.c
```
llamb@emfr-ossdev-firedancer14> cat no-lu-buffer-too-small.c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main() {
char buf[16];
snprintf(buf, sizeof(buf), "%u", 500000000000000000UL);
printf("%s\n", buf);
}
llamb@emfr-ossdev-firedancer14> gcc no-lu-buffer-too-small.c && ./a.out
3551657984
llamb@emfr-ossdev-firedancer14> cat buffer-too-small.c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main() {
char buf[16];
snprintf(buf, sizeof(buf), "%lu", 500000000000000000UL);
printf("%s\n", buf);
}
llamb@emfr-ossdev-firedancer14> gcc buffer-too-small.c && ./a.out
500000000000000
llamb@emfr-ossdev-firedancer14> cat lu-and-buffer-big-enough.c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main() {
char buf[24];
snprintf(buf, sizeof(buf), "%lu", …
```
=> fix --faucet-lamports parsing used in genesis creation

src/app/fdctl/config.c, src/app/fdctl/configure/workspace.c, src/app/fdctl/run/tiles/net.c, src/app/fdctl/run/tiles/shred.c, src/disco/net/fd_net.c, src/disco/net/fd_net.h, src/disco/quic/fd_quic.c
Range end was not getting set correctly resulting in:
```
ERR     10-19 20:15:38.662281 16     f0   shred src/disco/shred/fd_shred_tile.c(331): chunk 823780 1245 corrupt, not in range [16370,16370]
```
If some port, for e.g. shred port is set to 8003 and it is not in the range of handled_port, we were erroring out:
```
ERR     10-19 20:15:38.656524 6      f0   quic src/disco/quic/fd_quic.c(313): Firedancer received a UDP packet on port 8003 which was not expected. Only ports 9007 and 9001 should be configured to forward packets. Do you need to reload the XDP program?
```
=> fix some port traffic related issues

src/ballet/ed25519/fd_ed25519_user.c, src/ballet/sha256/Local.mk, src/ballet/sha256/fd_sha256.h, src/ballet/sha256/fd_sha256_batch_avx.c, src/ballet/sha256/fd_sha256_batch_avx512.c, src/ballet/sha256/test_sha256.c, src/ballet/sha512/fd_sha512_batch_avx.c, src/ballet/sha512/fd_sha512_batch_avx512.c, src/ballet/shred/fd_shred.h, src/disco/shred/fd_shred_dest.h, src/disco/shred/fd_shredder.h, src/disco/shred/test_shredder.c, src/tango/quic/fd_quic.c, src/tango/quic/fd_quic_conn.h, src/util/fd_util_base.h, src/util/simd/Local.mk, src/util/simd/fd_avx512.h, src/util/simd/fd_avx512_wwi.h, src/util/simd/fd_avx512_wwl.h, src/util/simd/fd_avx512_wwu.h, src/util/simd/fd_avx512_wwv.h, src/util/simd/test_avx512.h, src/util/simd/test_avx512_16x32.c, src/util/simd/test_avx512_8x64.c, src/util/tmpl/fd_map_dynamic.c, src/util/tmpl/fd_map_giant.c, src/util/tmpl/fd_pool.c
As mentioned in PR #760, here is the accelerated SHA-256 version.  On a 2.3 GHz Icelake server core with turbo disabled (same one mentioned previously for AVX-512 accelerated SHA-512 and ED25519), quick and dirty benchmarks saw a large batch asymptotic Ethernet equivalent bandwidth processing rate of:
```
impl      | small msg | large msg
----------+-----------+----------
portable  |  1.8 Gbps |  1.4 Gbps
shani     |  6.4 Gbps |  7.0 Gbps
avx       |  9.4 Gbps |  8.7 Gbps * same asymptotic w shani
avx512    | 18.9 Gbps | 18.4 Gbps * same asymptotic w shani
```
As before, the small message size was 14 bytes (i.e. a maximum UDP payload of a minimal Ethernet frame holding a UDP/IP4/VLAN/Ethernet packet) and the large message size was 1472 bytes (i.e. a maximum UDP payload of a non-Jumbo 1500 …
=> AVX-512 accelerated batch SHA256 implementation, related features and minor cleanups

config/linux_clang_minimal.mk, config/linux_clang_noarch128.mk, config/linux_clang_noarch64.mk, config/linux_clang_x86_64.mk, config/linux_gcc_icelake.mk, config/linux_gcc_minimal.mk, config/linux_gcc_noarch128.mk, config/linux_gcc_noarch64.mk, config/linux_gcc_x86_64.mk, config/linux_gcc_x86_64_wd_f1.mk, config/with-security.mk, deps.sh, src/flamenco/vm/Local.mk
* make executables position independent
* use fortify source
* build with immediate bindings if possible
* enable stack canaries (previously, only the gcc builds would end up having stack canaries)
=> Improve build security flags

src/app/fdctl/config.c, src/app/fdctl/run/tiles/fd_dedup.c, src/app/fdctl/run/tiles/fd_net.c, src/app/fdctl/run/tiles/fd_pack.c, src/app/fdctl/run/tiles/fd_quic.c, src/app/fdctl/run/tiles/fd_shred.c, src/app/fdctl/run/tiles/fd_verify.c, src/app/fdctl/topology.c, src/app/fdctl/topology.h, src/app/fdctl/utility.c, src/app/fdctl/utility.h, src/ballet/pack/fd_pack.c, src/disco/mux/fd_mux.c, src/disco/mux/fd_mux.h
The logic for keeping the pack tile and the bank tile in sync is a bit tricky. Because pack keeps track of per-block limits, it needs to make sure the transactions it packs land in the block it expects them to. A prerequisite for getting this to work is for the pack tile to know if it's actually leader or not.
While we're at it, have pack filter transactions it already knows about. This can happen when we get the same vote transaction over the normal TPU pipeline and over gossip, or if the dedup tcache is too small.
=> disco/pack: Only pack when leader, and pack for a specific slot

src/app/fdctl/configure/workspace.c, src/app/fdctl/monitor/monitor.c, src/app/fdctl/ready.c, src/app/fdctl/run/tiles/fd_dedup.c, src/app/fdctl/topology.c, src/app/fdctl/topology.h
We want to map shared memory as PROT_READ only for added security if a tile does not write to the associated workspace.  We automatically determine if this is possible from the topology.
=> fdctl: map some workspaces as readonly if possible

src/util/tmpl/fd_map_dynamic.c
Without this change [this code path](https://github.com/firedancer-io/firedancer/blob/main/src/util/tmpl/fd_map_dynamic.c#L380) would return `NULL` and [cause a segfault in pack](https://github.com/firedancer-io/firedancer/blob/main/src/ballet/pack/fd_pack.c#L617).
=> reset key count when clearing dynamic map

src/app/fdctl/run/tiles/fd_pack.c, src/ballet/pack/fd_pack.c, src/ballet/pack/fd_pack.h, src/ballet/pack/test_pack.c
Long term, we probably want a better solution than this (e.g. shred tile doing better batching), but for now this is safe.
=> fd_pack: limit the number of microblocks we produce in a block

src/app/fdctl/config.c, src/app/fdctl/monitor/monitor.c, src/app/fdctl/run/tiles/fd_pack.c, src/app/fdctl/run/tiles/fd_shred.c, src/app/fdctl/topology.c, src/app/fdctl/topology.h, src/disco/shred/Local.mk, src/disco/shred/fd_shred_dest.c, src/disco/shred/fd_shred_dest.h, src/disco/shred/fd_stake_ci.c, src/disco/shred/fd_stake_ci.h
Rather than sending the full leader schedule, we now send the stake weights. These are usable by the pack tile and the shred tile. Also changed the splice point for contact info.
Around epoch boundaries, this can get a little tricky (especially in the shred tile case), so we keep around an even epoch and an odd epoch, which is normally the current epoch and the next epoch. We get the next epoch as soon as the current one is rooted.
=> redo plumbing of stake weights, contact info into pack, shred tiles

src/app/fdctl/config.c, src/disco/fd_disco_base.h
Gossiped votes -> Pack was wrong in Rust, and two on the C side had their MTUs switched.
=> app: fix mismatched MTUs

src/ballet/blake3/Local.mk, src/ballet/blake3/fuzz_blake3.c, src/ballet/hmac/Local.mk, src/ballet/hmac/fuzz_hmac.c, src/ballet/keccak256/Local.mk, src/ballet/keccak256/fuzz_keccak256.c, src/ballet/murmur3/Local.mk, src/ballet/murmur3/fuzz_murmur3.c, src/ballet/sha256/Local.mk, src/ballet/sha256/fuzz_sha256.c, src/ballet/sha512/Local.mk, src/ballet/sha512/fuzz_sha384.c, src/ballet/sha512/fuzz_sha512.c
This PR adds fuzzers for the hashing algorithm implementations found in `ballet`:
- `sha256`
- `sha512` (and `sha384`)
- `keccak256`
- `blake3`
- `murmur3`
- `hmac`
=> Fuzzers for hashing algorithms in ballet

src/tango/ip/fd_netlink.c
Getting an warning reported from a user.
This adds the needed info from netlink to diagnose the issue.
=> fd_ip - added diagnostics for unusual LL ADDR length

src/tango/ip/fd_ip.c, src/tango/ip/test_routing.c
This code misbehaved. It's unneeded for now, so disable for now.
=> quic-arp - disable broadcast ips

src/app/fdctl/run/run.c
When manually specifying gossip host, run conf erroneously sets it twice. Fixes run conf to only specify the default if an alternative isn't specified in config
=> run conf: fix double gossip host when set in config toml

src/app/fdctl/Local.mk, src/app/fdctl/fdctl.h, src/app/fdctl/help.c, src/app/fdctl/keygen.c, src/app/fdctl/main1.c, src/app/fdctl/mem.c, src/app/fdctl/topology.c
```
$ build/native/gcc/bin/fdctl help
NOTICE  10-27 15:48:56.962811 2095364 f0   main src/app/fdctl/help.c(56): 
fdctl: Firedancer control binary
usage: fdctl [OPTIONS] <SUBCOMMAND>
Sub Commands:
run        Start up a firedancer validator
configure        Setup the environment needed to start firedancer
monitor        Monitor a locally running firedancer validator
keygen        Generate identity and voting keypairs
ready        Detect if all CNC pieces are ready
mem        Print workspace memory and topology information [ aliases: info, topo ]
help        Print this help message
Options:
--config <PATH>
Path to config TOML file
```
=> fdctl: add help message and vote keygen

config/native.mk
The `x86intrin.h` header that older versions of GCC include is strangely missing some functions. While it would be possible to switch the functions we use to equivalent ones, this is a pain, and who knows what kind of compiler bugs we might stumble on if the AVX512 support is really that half-baked.
=> config: disable AVX512 when using GCC < 10

src/disco/shred/fd_fec_resolver.c, src/disco/shred/fd_shred_dest.c, src/disco/shred/fd_stake_ci.h
The size of an `fd_shred_dest` depends on `FD_SHA256_BATCH_FOOTPRINT` which varies based on the target (no-AVX, AVX, AVX512). The code was using the hardcoded value for AVX, which caused failures. Unfortunately, they were runtime failures because not all the structs expose compile-time footprint calculations.
=> fd_stake_ci: fix size computation for AVX512 and non-AVX platforms

src/tango/quic/fd_quic.c
As additional tiles might join a QUIC object (e.g. to read metrics), the join function should not clear memory.
=> quic: do not clear on join

src/app/fdctl/caps.c
Hello frens. Was setting up my firedancer test node and a resource limit was missing but didn't know which one. Modified the ERR log to log which one is too low.
Example log: `ERR     10-30 19:09:18.536913 76797  f0   main src/app/fdctl/caps.c(158): setrlimit failed (1-EPERM-operation not permitted) for resource RLIMIT_NOFILE`
happy to modify if any of these are irrelevant / if I missed any that we might need
=> caps: log the particular resource limit if one is too low

src/app/fdctl/main1.c
Removing extra space in `fdctl spy` description
=> trivial: removing extra space in cli action description

src/ballet/siphash13/fuzz_siphash13.c
Arg 2 and 3 to `posix_memalign` are flipped. This changes fixes this.
It's been working before because `sizeof(fd_siphash13_t)` and `alignof(fd_siphash13_t)` are both 128.
=> fuzz_siphash13: fix usage of posix_memalign

src/ballet/sha256/fuzz_sha256.c, src/ballet/sha512/fuzz_sha512.c
The SHA512 fuzzer was broken.
Both SHA256 and SHA512 now share the same code.
=> fuzz: fix sha fuzzers

src/app/fdctl/run/run_solana.c
Despite `[ledger.accounts_path]` being a valid configuration option, the path never gets passed onto the labs client. This causes both accounts and ledger to be written to the same disk, which can be painful on nodes with smaller disks for operators.
=> fdctl: pass accounts_path onto labs client

src/util/shmem/fd_shmem_user.c
The call to `munmap` is invalid as it will only be called when `shmem` is set to `MAP_FAILED`. This is not a valid userspace address and `munmap` will fail every time.
=> shmem: Remove invalid call to `munmap` in `fd_shmem_join`

.github/workflows/coverage.yml, .github/workflows/scripts/testcov_gen_index.sh, README.md
This change publishes testing and fuzzing coverage to a Google Cloud Storage bucket.
The [index](https://storage.googleapis.com/firedancer-ci-artifacts-public/index.html) gets rewritten to redirect to the latest revision.
=> coverage: publish to gcloud

src/ballet/txn/fd_txn_parse.c, src/ballet/txn/test_txn_parse.c
I found that (on our two test transactions) a substantial fraction of parse time was spent checking that no account index exceeded the number of accounts in the transaction. I changed the check, and moved it, and that seems to have improved performance substantially: 
- Transaction 1: `80.8ns` to `50.8ns` (-37%)
- Transaction 2: `42.6ns` to `37.9ns` (-11%)
Note: These are pretty lousy benchmarks, because the branch predictor will predict everything exactly. Regardless, this change eliminates some branches, so it should still be a win.
This PR does change the behavior slightly. In particular, previously this account index check was omitted when `out_buf==NULL`. That seems like a mistake. Secondly, previously, transactions with 0 instructions and 0 accounts were accepted when …
=> ballet/txn: small changes to improve parse performance

src/app/fdctl/config.h, src/app/fdctl/main1.c, src/app/fdctl/run/tiles/fd_verify.c, src/tango/tempo/fd_tempo.c, src/tango/tempo/fd_tempo.h
Now that processes are restarted with execve() to get randomized address layout, they lose the fd_tempo_tick_per_ns value.  This isn't much of a problem normally, they will be similar and just used for things like randomizing wait times.
But duration histograms for metrics are an exception.  These histograms have buckets defined in wallclock time (eg, 0-1s, 1s-2s, 2s+).  But they are measured on the tile in ticks (eg, 0-1s/ticks_per_sec, 1s-2s/ticks_per_sec,, 2s/ticks_per_sec+), to enable faster collection without scaling.  The metrics tile that reports to external viewers will rescale to wallclock time.
So the tiles doing collection and the tile doing reporting need to agree on the ticks_per_ns value so they can create the same histogram buckets.  We achieve this by just passing it …
=> fdctl: preserve ticks_per_ns accross processes

src/app/fdctl/config.c, src/app/fdctl/run/tiles/fd_pack.c, src/app/fdctl/run/tiles/fd_shred.c, src/disco/fd_disco_base.h
Without batching, we produce many small FEC sets, which make inefficient use of our parity shred budget. This implements the simplest form of batching, where each batch is still limited to one FEC set.
This change enables relaxing some limits in pack. I'll make those changes in another PR.
=> shred: batch microblocks up to one full FEC set

src/util/shmem/fd_shmem_private.h, src/util/shmem/fd_shmem_user.c
Due to the behavior of `mmap` in the Linux kernel the shared memory mappings in each tile processes will most likely be adjacent to each other. Relevant output from `/proc/pid/maps` is below:
```
7f64c0000000-7f6500000000 rw-s ... 6736764  /mnt/.fd/.gigantic/fd1_verify_dedup.wksp
7f6500000000-7f6540000000 rw-s ... 6736763  /mnt/.fd/.gigantic/fd1_quic_verify.wksp
7f6577200000-7f6577400000 rw-s ... 6736773  /mnt/.fd/.huge/fd1_verify.wksp
```
This makes it such that out of bounds access vulnerabilities can possibly corrupt other shared memory regions causing further unintended behavior.
To mitigate this possible situation we introduce a function `fd_shmem_private_get_random_mappable_addr` which will return a random mappable address for a passed size that can be used with `MAP_FIXED`. Shared …
=> shmem: randomize address of shared memory mappings in tile processes

.github/workflows/functional_tests.yml, book/guide/initializing.md, src/app/fdctl/Local.mk, src/app/fdctl/config.c, src/app/fdctl/configure/sysctl.c, src/app/fdctl/fdctl.h, src/app/fdctl/keys.c, src/app/fdctl/main1.c, src/app/fdctl/run/tiles/fd_net.c, src/app/fdctl/run/tiles/fd_quic.c, src/app/fdctl/topology.h, src/app/fdctl/utility.c, src/app/fddev/Local.mk, src/app/fddev/configure/keys.c, src/app/fddev/main.c, src/disco/fd_disco_base.h, src/test/single-transfer.sh
We are trying to send outgoing packets for 127.0.0.1 to the external facing NIC rather than on the loopback device, which won't work.
This is mostly to support development and testing, although it's conceivable someone would send transactions via. loopback in production as well.
=> quic: support loopback for QUIC connections

src/app/fdctl/run/tiles/fd_verify.c
In `after_frag` the txn is located in shared memory accessible to the dedup tile and the contents are populated the quic tile. We add checks to validate all offset fields and remove double fetches of non-data fields.
=> verify: validate txn fields and remove double fetches

deps.sh
Compiling on debian based machines results in errors right now without manual intervention if a machine doesn't have `clang` installed by default. You get the error below:
```
error: failed to run custom build command for `firedancer-sys v0.3.0 (/home/max/Documents/firedancer/ffi/rust/firedancer-sys)`
Caused by:
process didn't exit successfully: `/home/max/Documents/firedancer/solana/target/release/build/firedancer-sys-0712ccd48b712ce2/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-changed=wrapper_util.h
cargo:rerun-if-changed=../../../src/util
cargo:rerun-if-changed=wrapper_ballet.h
cargo:rerun-if-changed=../../../src/ballet
cargo:rerun-if-changed=wrapper_tango.h
cargo:rerun-if-changed=../../../src/tango
--- stderr
thread 'main' panicked at …
```
=> deps: adding clang as a dependency for debian based machines

.github/workflows/on_daily.yml, config/base.mk, config/with-fuzz.mk, contrib/find_uncovered_fuzz_canaries.py, src/ballet/sbpf/fuzz_sbpf_loader.c, src/util/fd_util_base.h, src/util/sanitize/fd_fuzz.h, src/util/sanitize/test_fuzz_canary_canary.c
This change introduces "fuzz canaries".
Developers should add `FD_FUZZ_MUST_BE_COVERED;` to any code path to ensure that the fuzzer eventually gets there. If the fuzzer never covers a canary, the security team is going to be able to follow-up with a fix or recommendations.
For the time being, warnings are emitted as part of the "All Coverage / Daily" task (please see picture below). In a follow-up PR, the security team will be alerted by email.
Another follow-up PR is going to add fuzz canaries to existing fuzz targets.
Also note that there exists a "negative canary" [0] , which should never be covered. The script expects to find in order to sanity-check itself.
[0] `src/util/fuzz/fd_fuzz_canary_canary.c`
=> fuzz: introduce canaries

src/app/fdctl/monitor/monitor.c, src/app/fdctl/ready.c, src/app/fdctl/run/run.c, src/app/fdctl/topology.c, src/app/fdctl/topology.h
The return fseq objects are placed into the metrics workspace, so that we can map link workspaces as readonly on the consumer side. Cnc objects are also moved to the metrics workspace so that monitoring applications can monitor firedancer just by mapping the one workspace as readonly.
=> map read side of workspaces as readonly

.github/actions/deps/action.yml
It does what it says on the tin.
Unblocks runs like those: https://github.com/firedancer-io/firedancer/actions/runs/7169937502/job/19521481236?pr=1042
=> ci: update apt caches on deps run

.github/workflows/_publish_to_clusterfuzz.yml, .github/workflows/scripts/build_rust_fuzz_highend.sh
If the current fuzz build is `highend`, the `publish_to_clusterfuzz.yml` now builds the rust fuzz targets and places them next to the `highend` fuzz artifacts before the invocation to `firedancer-io/clusterfuzz-action`.
=> fuzz: add rust fuzz targets to highend fuzz artifacts

src/tango/quic/tests/fuzz_quic.c
Quic fuzzer wasn't running due to increased memory requirements
This fixes
=> QUIC - increase fuzz workspace size

src/app/fdctl/run/tiles/fd_verify.c
Not sure if anyone has a better solution to fix this?
https://github.com/firedancer-io/firedancer/actions/runs/7263228554/job/19788066039#step:6:3779
=> fd_verify: explicitly set unused variable to avoid compiler complaints

contrib/container-build/Dockerfile, contrib/container-build/README.md, contrib/container-build/buildit.sh, contrib/container-build/scripts/fdbuild.sh, src/app/fdctl/run/tiles/fd_verify.c
- creates a build container with all build dependencies that will be used for subsequent builds. First build takes slightly longer as it creates the container.
- spits out fdctl and solana bins to `~/build/machinetype`
- can optionally pass a tag, branch, or release to buildit.sh as `./buildit.sh --tag somebranch`
- optionally specify a machine type with `./buildit.sh --machine machinetype` but defaults to linux_gcc_x86_64
=> standardized container build based on rhel8.5

src/ballet/chacha20/Local.mk, src/ballet/chacha20/fd_chacha20_avx.c
Unfortunately, chacha20 has long sequential dependencies and thus very little ILP, so the speedup is not great (4.2 Gbps -> 5.6 Gbps, or 6.0 Gbps with AVX512 on my machine). However, this is easily extendible to a batch implementation, which I'll look into next.
=> ballet/chacha20: Add SSE/AVX implementation

src/tango/quic/fd_quic.c, src/tango/quic/fd_quic_pkt_meta.h, src/tango/quic/fd_quic_stream.h
Stream flow control accounting was incorrect, resulting in double counting
Ack handling didn't clear acks when moving tx_tail, resulting in bytes appearing acked when they weren't
max_stream_data frames had a race condition with peer
handshake_done could be sent unnecessarily (after being acked)
=> QUIC ack and resend fixes

.github/workflows/on_pull_request.yml, .github/workflows/trailing_whitespace.yml
This check produces different results on main vs on PRs.
=> ci: only run trailing whitespace check on PRs

config/machine/linux_clang_icelake.mk, config/machine/linux_gcc_icelake.mk, src/app/fdctl/run/tiles/fd_poh.c, src/ballet/ed25519/avx512/fd_r43x6_ge.c, src/util/simd/fd_avx512_wwi.h, src/util/simd/fd_avx512_wwl.h, src/util/simd/fd_avx512_wwu.h, src/util/simd/fd_avx512_wwv.h, src/util/simd/test_avx512.h, src/util/simd/test_avx512_16x32.c, src/util/simd/test_avx512_8x64.c
Clang and GCC are pickier about `_mm512_rol_epi32` having a compile-time constant argument.  Richie's fix using `__builtin_constant_p` works fine with GCC but not with Clang. The best way to address it is to split into e.g. `wwi_rol` and `wwi_rol_variable`. I modified the tests correspondingly.
There was also an unused variable Clang did not like in the PoH tile, and an incorrect alignment argument in `fd_r43x6_ge.c`.
The reason all these issues have gone undetected is that CI was not building with `FD_HAS_AVX512`, so I've fixed that as well.
Fixes #1188.
=> Misc changes to fix Clang AVX512 compilation

src/app/fdctl/Local.mk, src/app/fdctl/run/tiles/fd_verify.c, src/app/fdctl/run/tiles/fd_verify.h, src/app/fdctl/run/tiles/test_verify.c, src/ballet/ed25519/fd_ed25519.h, src/ballet/ed25519/fd_ed25519_user.c, src/ballet/txn/fd_txn.h
This PR verifies all signatures in a tx.
We added an interface for batch verification (batch signatures over a single message), but the implementation is the naive one. Efficient implementation will be done in an independent PR.
Fixes #1059.
This includes tests for #1059 and #1068.
=> verify: verify all N signatures of transaction

src/app/fdctl/config.c, src/app/fdctl/config.h, src/app/fdctl/config/default.toml, src/app/fdctl/run/run_solana.c
From the new documentation:
>  Under normal operating conditions, a validator should always reach out to a host located on the public internet.
> This configuration item allows Firedancer to gossip with nodes located on a private internet (rfc1918).
=> introduce the `development.gossip.allow_private_addr` configuration item

src/app/fdctl/configure/ethtool.c, src/app/fdctl/run/tiles/fd_bank.c, src/app/fdctl/run/tiles/fd_poh.c, src/disco/mux/fd_mux.c
Some cleanup, plus:
> Clang optimizes extremely aggressively which breaks the
>        atomicity expected by seq_sig_query.  In particular, it replaces
>        the sequence query with a second load (immediately following
>        vector load).  The signature query a few lines down is still an
>        extract from the vector which then means that effectively the
>        signature is loaded before the sequence number.
>        Adding this clobbers of the vector prevents this optimization by
>        forcing the seq query to be an extract, but we probably want a
>        better long term solution.
=> mux: temporary fix for clang strangeness breaking fddev

src/app/fdctl/config.c, src/app/fdctl/config.h, src/app/fdctl/config/default.toml, src/app/fdctl/run/tiles/fd_quic.c, src/disco/topo/fd_topo.h
RETRY functionality couldn't be accessed thru fddev or fdctl
=> Added config for QUIC RETRY

src/ballet/pack/fd_pack.c, src/ballet/pack/test_pack.c, src/ballet/txn/fd_txn.h, src/ballet/txn/test_txn.c
After considering many approaches, I decided to stick with something close to the original design.  Switching to requiring a (very cheap) `fd_txn_acct_iter_idx` means that I no longer need the grossness of the separate control word that is passed by reference.
=> fd_txn: improve performance of iterating over accounts

src/app/fdctl/config.c
When the pack->bank link is unreliable, banks will in rare cases get overrun on their next microblock, if they take too long between when they release the fseq account lock, and then poll for the next fragment.  This is not OK, both because the accounts in the next microblock will get locked indefinitely (and the bank will be locked forever), but also PoH will not see the transaction count it expected from pack and will hang forever.
=> poh: fix rare hang

src/ballet/pack/fd_pack.c
Bug 1: Consider the following situation:
- Transactions 1 and 2 added, which both read account A. This assigns a bit from the fast bitset to account A.
- Transaction 1 (but not 2) scheduled to a microblock.
- Transaction 2 scheduled to a microblock. This decreases the reference count to A to 0, so it sets `BIT_CLEARED` and clears the bit.
- The microblock containing transaction 1 completes. `fd_pack_microblock_complete` handles account A properly because it sees `BIT_CLEARED`, but at the end, it clears `BIT_CLEARED`.
- The microblock containing transaction 2 completes. `fd_pack_microblock_complete` sees that account A does not have `BIT_CLEARED`, so it expects to find it in the account -> bitset map. It doesn't, and crashes with `FD_TEST( q )`.
Bug 2: Consider the following situation:
- …
=> fd_pack: fix two subtle bugs with bitset

src/flamenco/runtime/tests/fd_exec_instr_test.c
Helps with avoiding critical errors and freezes while running the test suite on invalid inputs.
=> Change unsupported feature error to warning

src/app/fdctl/config.c, src/app/fdctl/run/tiles/fd_netmux.c
Fixes #1358
A muxer that doesn't copy packets has a problem, where the mux tile itself might get overrun, but the downstream consumer won't realize because the sequence number that the consumer checks after reading the fragment gets incremented against the mcache, which is different for the consumer and the producer.
There's a few ways to fix this:
* You can keep two sequence numbers, and have the consumer check both of them.
* You can write the sequence number check into the dcache itself (before and at the end of) the packet.
* You can copy the fragments.
For now we do the 3rd option, as it's the easiest to implement.
=> netmux: copy packets to avoid corruption

src/ballet/reedsol/fd_reedsol.c, src/ballet/reedsol/fd_reedsol_private.h
Although `fd_reedsol_private_encode_32_32` only uses 256-bit registers, it assumes the CPU has `ymm16-31`, which is only true for systems with AVX512. I didn't realize there were chips with GFNI but no AVX512, but we've seen it on some consumer hardware. In that case, still use the GFNI arithmetic, but avoid the hand-optimized version. The compiler will have to do more work to rename registers, but it'll compile it just fine for 16 vector registers.
=> fd_reedsol: support CPUs with GFNI but no AVX512

src/app/fdctl/run/tiles/fd_verify.c
The system is throughput constrained heavily by verify tiles, but not by dedup which would still be idle on one core when handling 1M TPS.
This moves work from verify tiles to dedup, which will increase overall system throughput
Fixes #1392
=> verify: remove dedup from verify

src/app/fdctl/run/run_solana.c
In run_solana.c, ip_addr was scoped within an if statement, but the address was stored and used outside the scope.
=> Changed scope of local variable ip_addr

src/app/fdctl/run/tiles/fd_dedup.c
`FD_TCACHE_FOOTPRINT` (the macro version) does not return the right value when `depth` (the second argument) is 0.  This is not an actual issue because the footprint calculation for the tile uses `fd_tcache_footprint`, but it could cause a problem if someone adds another object to the scratch space without noticing.
=> fd_dedup: prevent potential future memory corruption issue

src/ballet/pack/fd_pack.c, src/ballet/pack/fd_pack_cost.h, src/ballet/pack/test_pack.c
Keep track of accounts that transactions write lock so that only they can be cleared. Typically, this is a much smaller set than the full map. Also, fix a bug with the sizing of the writer costs map.
=> fd_pack: optimize ending the block

src/app/fdctl/monitor/monitor.c, src/disco/mux/fd_mux.c
Additionally, this changes slow_cnt to only increment when backpressured. In the normal course of events, with `n` identical consumers, each consumer will be the slowest around 1/n of the time. That's expected and not an issue. Slow is most useful as a way to blame backpressure on a consumer.
=> fdctl: fix monitor reporting of slow cnt

src/flamenco/runtime/program/fd_address_lookup_table_program.c, src/flamenco/runtime/tests/fd_exec_instr_test.c
* Add extra check in address lookup table program for compute units (was causing mismatch with Agave)
* Add error code output for unsupported programs
=> Native program mismatch fixes

src/tango/dcache/fd_dcache.c, src/util/wksp/fd_wksp_admin.c
With a large workspace or dcache, zeroing the entire space can take a long time.  This isn't strictly necessary, since the wksp and dcache implementations do not assume the data region is zeroed.
The underlying shared memory must be zeroed by the kernel when it is first grabbed, so the only way this is non-zero is if we are reusing space in the shared memory that we created previously.  It is OK to expose, but not use, the previous data in this case.
Related to #1391
=> util: don't zero entire wksp or dcache

src/app/fdctl/run/tiles/fd_pack.c, src/app/fdctl/run/tiles/fd_poh.c
When inserting to pack from the extra storage, we forgot to set payload_sz which would occasionally lead to producing bad blocks under heavy load.
Also, fix the computation for `max_remaining_ticks_or_microblocks` which was sometimes running out of hashcnt for the final tick.
=> fdctl: fix two small bugs

src/flamenco/runtime/program/Local.mk, src/flamenco/runtime/program/fd_address_lookup_table_program.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_native_cpi.c, src/flamenco/runtime/program/fd_native_cpi.h, src/flamenco/runtime/tests/Local.mk
1. Adding cpi to bpf deploy. Generally getting the instruction working.
2. Refactor common code previously only used in alut program
3. Adding ledger test
=> flamenco: adding cpi to system program to bpf deploy

src/flamenco/runtime/program/fd_address_lookup_table_program.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_native_cpi.c, src/flamenco/runtime/tests/Local.mk
1. Adding system program transfer CPI for extend instruction in bpf program
2. Native program CPI cleanup
3. Adding ledger test
=> flamenco: adding system program CPI to extend instruction

src/app/fdctl/config/default.toml, src/app/fdctl/fdctl.h, src/app/fddev/bench.c, src/app/fddev/fddev.h, src/app/fddev/spammer.c, src/app/fddev/tiles/fd_benchs.c, src/disco/topo/fd_topo.h, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_pkt_meta.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/templ/fd_quic_transport_params.h
bench code needs the following, but putting these into another PR:
quic_enable - hard coded flag to use quic rather than udp: should be configurable
only supports one connection. Each benchs should have a connection for each fd_quic tile
This PR should help us move forward with the demo
=> added quic support to fddev bench. Numerous QUIC fixes.

src/disco/tvu/fd_tvu.c
Uninitialized checkpoint freq was causing a floating point exception when using other arguments that initialized a capture ctx (e.g. Protobuf instruction dumping)
=> Fix arithmetic exception caused by uninitialized checkpoint freq

.gitignore, src/choreo/bft/fd_bft.c, src/choreo/bft/fd_bft.h, src/choreo/ghost/fd_ghost.c, src/choreo/ghost/fd_ghost.h, src/choreo/ghost/test_ghost.c
This PR updates the vote counting and equivocation handling in fd_bft and fd_ghost. Blocks get marked as equivocating if we have a different bank hash from what is being voted on for a given slot. Also added and cleaned up error checks when running with handholding.
=> feat(choreo): vote counting and equivocation handling for fork choice

src/util/wksp/fd_wksp.h, src/util/wksp/fd_wksp_admin.c
This api provides a way to set a workspace to be read-only. This is useful for security and debugging.
=> add fd_wksp_mprotect api

src/app/fdctl/config.c, src/app/fdctl/configure/workspace.c, src/disco/topo/fd_topob.c, src/disco/topo/fd_topob.h
Adds an explicit function for adding sized and aligned object to topology. This allows us to add objects like blockstore and funk to a topology without special case logic for every single object in a topology.
=> topo: add concrete sized, aligned, topology objs

src/flamenco/features/fd_features_generated.c, src/flamenco/features/fd_features_generated.h, src/flamenco/features/feature_map.json, src/flamenco/runtime/tests/fd_exec_sol_compat.c
Context: https://github.com/anza-xyz/agave/pull/127
We need to update our test ledgers:
- v18-small (fails at slot 2)
- helloworld (fails at slot 101)
=> features: update timely_vote_credits

src/app/fdctl/run/topos/fd_frankendancer.c, src/app/fddev/spammer.c, src/disco/topo/fd_topob.c, src/disco/topo/fd_topob.h
The `fd_topo_t` type is getting a bit big to put on the stack. This addresses the major case were that was causing issues.
=> topo: fd_topob_new uses caller-owned address

src/util/net/fd_net_headers.h
Without this the linker complains about the symbol when it actually gets used.
=> util: static linkage for fd_net_create_packet_header_template

src/flamenco/runtime/program/fd_vote_program.c
Case if `start = 0, end = 1`, and `slot` is lower than all values in the deque. When mid = 0, `end = mid - 1` which causes an underflow and thus a segfault / infinite loop.
Similarly, if `slot` is greater than all deque values, we may try to access a value at `vote_state->votes[len]` which would cause an out of bounds memory access.
=> Fix underflow error in binary search

src/flamenco/runtime/program/fd_vote_program.c
#1733 Fixed an issue with underflows during the binary search but also introduced an underflow issue when `deq_fd_landed_vote_t_cnt( vote_state->votes )` returns 0.
Closes [issue](https://github.com/firedancer-io/auditor-internal/issues/54).
=> Fix underflowing in contains_slot when votes count is 0

src/app/fddev/main1.c, src/disco/topo/fd_topo.h, src/disco/topo/fd_topo_run.c
`int for_tpool;`
when set this a call to `run_tile_thread()` will not spawn a thread so the tpool can handle the thread spawning later
`int   (*main                    )( void );`
When not NULL this function is called instead of `fd_mux_tile()`.
=> Add two fields to fd_topo_run_tile_t:

src/app/fdctl/run/tiles/fd_sign.c
Under ASan, sign tile freaks out when ASan changes the stack configuration. This fixes that.
=> tiles: sign tile supports asan

src/util/tile/fd_tile.h, src/util/tile/fd_tile_threads.cxx
`fd_tile_private_map_boot` will allow a tile to boot a tpool on the CPUs specified by `tile_to_cpu`. These CPUs have tiles running on them with `for_tpool = 1` from https://github.com/firedancer-io/firedancer/pull/1742.
=> add fd_tile_private_map_boot() to fd_tile.h for later tpool use in fddev

src/flamenco/runtime/tests/fd_exec_sol_compat.c
Memset `smem` to 0 before the beginning of every sol_compat execution
=> Fix fuzzer / conformance memory issue

.github/workflows/clusterfuzz.yml
fixes the broken CI job for clusterfuzz-upload. Also simplified it so the `lib` target gets built at the same time as the fuzz-tests.
=> `ci`: fix clusterfuzz upload github action

src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_system_program_nonce.c
1. has_nonce check used nonce at root txn instead of parent funk txn leading to wrong account state
2. double publishing for nonce accounts on non failing transactions
3. wrong encoding length on advance nonce instruction
=> flamenco: various nonce check related fixes

src/app/fdctl/run/tiles/fd_net.c, src/app/fdctl/run/topos/fd_firedancer.c, src/app/fdctl/run/topos/fd_frankendancer.c, src/disco/topo/fd_topo.h, src/waltz/quic/tests/fd_quic_test_helpers.c, src/waltz/xdp/fd_xdp_ctl.c, src/waltz/xdp/fd_xdp_ctl_help, src/waltz/xdp/fd_xsk.c, src/waltz/xdp/fd_xsk.h, src/waltz/xdp/fd_xsk_private.h, src/waltz/xdp/test_xsk.c
Now the only way to get the error on the boxes with the strange driver is to initialize xdp with skb mode, then manually change the mode to drv mode before running, which is fine.
=> fd_xsk, fdctl: make zero-copy mode configurable, disabled for skb mode

src/flamenco/runtime/info/fd_instr_info.c, src/flamenco/runtime/tests/fd_exec_instr_test.c
This check was added within the fuzz harness since we used to abort on a instruction account lamport sum overflow, but that is no longer the case, so this check is incorrect. 
We should be checking for overflows within the new lamport sum function, and returning an error as appropriate.
=> fuzz, flamenco: Remove lamport overflow check in fuzz harness

src/flamenco/runtime/tests/fd_exec_instr_test.c
* Reject cases where running a native program but owner is not NativeLoader
* Reject cases where the owner / address fields are not provided in the instruction context (Agave fails to parse these messages)
=> fuzz, flamenco: fuzz harness fixes

src/app/ledger/main.c, src/disco/tvu/fd_tvu.c, src/flamenco/runtime/context/fd_capture_ctx.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h
1. deprecating checkpt_slot option
2. adding cli option for checkpointing at last rooted slot upon mismatch
=> flamenco: checkpoint on mismatch

src/flamenco/vm/fd_vm_interp_dispatch_tab.c
Because we flush the intermediate CU accounting state in CALL_IMM, we need to also update the ic. Before this change, ic was getting reset to 0 in every CALL_IMM.
=> flamenco: Update ic in CALL_IMM instruction

src/app/fdctl/run/tiles/fd_replay.c, src/app/fdctl/run/tiles/fd_store_int.c, src/app/fdctl/run/topos/fd_firedancer.c, src/disco/topo/fd_topo.h, src/disco/tvu/fd_store.h, src/disco/tvu/fd_tvu.c, src/flamenco/gossip/fd_gossip.c
When we start using funk checkpoints or urls, the snapshot name will no longer have the number
=> Stop relying on snapshot file name for slot number

src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/info/fd_instr_info.c, src/flamenco/runtime/info/fd_instr_info.h, src/flamenco/runtime/program/fd_native_cpi.c, src/flamenco/runtime/program/fd_stake_program.c, src/flamenco/runtime/tests/run_ledger_tests.sh, src/flamenco/runtime/tests/run_ledger_tests_all.txt, src/flamenco/vm/fd_vm_syscalls.c
Solana represents total lamports as a u128 but we did as a ulong and it resulted in overflow. This replaces the lamport summation with a fd_uwide which represents a u128 as two ulongs
=> flamenco: add uwide support for lamport calculation

src/app/fdctl/config.c
For a multiline array, this was moving the pointer ahead by 1 (during the recursive call), resulting in a string that misses the `"` marks which results in an error.
=> toml: fix multi-line array parsing

contrib/test/test_firedancer_testnet.sh
For yet-to-be-determined reasons `entrypoint2.testnet.solana.com` and `entrypoint3.testnet.solana.com` are flaky. We'll use multiple entrypoints for now.
=> CI - use multiple entrypoints for test_firedancer_testnet.sh

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_common.h, src/waltz/quic/fd_quic_conn.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/fd_quic_proto.h, src/waltz/quic/templ/fd_quic_encoders_decl.h, src/waltz/quic/templ/fd_quic_frame_handler_decl.h, src/waltz/quic/templ/fd_quic_parse_frame.h, src/waltz/quic/tests/test_frames.c, src/waltz/quic/tests/test_quic_layout.c, src/waltz/quic/tests/test_quic_server.c, src/waltz/quic/tls/fd_quic_tls.c
Some code cleanup and internal API restructuring in preparation for the
QUIC conformance testing suite.
- Remove unused stream_tx_buf_sz and base_timeout vars from fd_quic_conn_t.
- Forward declare fd_quic_pkt_t type
- Remove static function declarations (fd_quic_frame_handler_decl.h)
from fd_quic_proto.h, which keep causing annoying "static function
declared but not defined/used" issues.
- Remove now useless template includes from unit tests
- Remove redundant identity config in test_quic_server (already done
by fd_quic_new_anonymous)
- Remove FD_LOG_NOTICE function call from remotely reachable code path
(security issue)
=> quic: internal polishing

src/flamenco/txn/Local.mk, src/flamenco/txn/fd_txn_generate.c, src/flamenco/txn/fd_txn_generate.h
Transaction generation for sending votes etc
=> flamenco: adds txn generation methods

src/flamenco/runtime/tests/fd_exec_instr_test.c
This was causing sysvars to not get loaded and thus unsupported sysvar errors
=> Fuzz harness fix

src/flamenco/types/fd_type_names.c, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json, src/flamenco/types/fd_types_custom.c, src/flamenco/types/gen_stubs.py
1) fixed a underflow issue with dequeue initialization of empty arrays
2) fixed variable sized objects to handle varints in primitives
3) handwrote a compactTowerSync deserializer 
4) Fixed some UINT_MAX checks which have the same "effect" as the optional root
=> towerSync: hand written deserializer for compact form

src/flamenco/runtime/context/fd_exec_slot_ctx.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_exec_sol_compat.c
* Fix bad magic / memory leaks caused by incorrect free operations in slot context
* Change fuzz harness to use libc allocators
* Reduce workspace page requirements
=> fuzz, runtime, flamenco: fix fd_map_giant bad magic and change fuzz harness to use libc alloc

src/flamenco/runtime/sysvar/fd_sysvar_cache.c, src/flamenco/runtime/sysvar/fd_sysvar_cache.h, src/flamenco/runtime/tests/fd_exec_instr_test.c
In the Agave fuzz harness, we load default sysvars if there was any failure in decoding the account data. In FD if the data for a sysvar account is corrupt, we load it anyways but don't set the sysvars. We should set default sysvar values if they don't exist.
We now set the slot bank slot as well.
=> fuzz, flamenco: fix default sysvar cache loading and add slot bank slot

src/flamenco/runtime/program/fd_vote_program.c, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.json
1) update_commission was not allowing decreased commission updates if the feature was enabled 
2) the defintiion of a epoch_schedule was invalid which was allowing firedancer
to process an invalid schedule instead of rejecting it in the same way solana did
3) Hacked the fuzz executor to correctly filter out an invalid epoch_schedule account
=> vote_update_comission: Fix update_commission and epoch schedule definition

src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json
frozen_status was defined as a uchar which would allow us to incorrectly process invalid bools
=> frozen_hash_status: Fix object definition to match v2.0

src/flamenco/runtime/tests/run_ledger_tests_all.txt, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
When we set the writable flag for an account during a CPI setup, we previously checked the caller account before we set the flag. Instead we need to set the flag without checking the caller and error out after the fact during the vm prepare
=> VM: updating is writable check in CPI

src/flamenco/runtime/fd_account_old.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_pubkey_utils.c, src/flamenco/runtime/fd_pubkey_utils.h, src/flamenco/runtime/fd_runtime.h, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.h, src/flamenco/runtime/sysvar/fd_sysvar_cache.c, src/flamenco/runtime/sysvar/fd_sysvar_cache.h, src/flamenco/runtime/tests/run_ledger_tests_all.txt
=> flamenco: bpf loader rewrite

.github/workflows/tests.yml, contrib/test/ci_tests.sh, src/app/fdctl/Local.mk, src/app/fdctl/run/topos/fd_firedancer.c, src/disco/consensus/Local.mk, src/flamenco/fd_flamenco.c, src/flamenco/runtime/tests/Local.mk, src/flamenco/vm/Local.mk
* We should build `fdctl` during our CI runs
* Based on requirements, we cannot build `fdctl` on `minimal`, `noarch64` or `noarch128`, hence the minimal capable build is updated to `linux_gcc_x86_64`
* We currently don't require secp256k so, added build conditions wherever that library is called during `all` target
=> ci: build fdctl

src/flamenco/runtime/program/fd_config_program.c
Agave's config program implementation dedupes keys by considering both pubkey AND signer status
```    
let total_new_keys = key_list.keys.len();
let unique_new_keys = key_list.keys.into_iter().collect::<BTreeSet<_>>();
```
=> flamenco, config: Check signer status equivalent for dedup

config/everything.mk
Changes the build path of headers from
build/native/gcc/include/app/...
to
build/native/gcc/include/firedancer/app/...
This improves the way third-party code includes Firedancer headers,
e.g.
#include <firedancer/app/...>
=> config: prefix header install path with 'firedancer'

src/flamenco/runtime/fd_account_old.h, src/flamenco/runtime/program/fd_bpf_loader_serialization.c, src/flamenco/runtime/program/fd_bpf_loader_v2_program.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt
There was no check for an ownership in the deserialize which was causing a hash mismatch. Added other error checks as well
=> flamenco: adding error checks to bpf deserialize

src/app/fdctl/external_functions.c, src/app/fdctl/run/tiles/fd_shred.c, src/app/fdctl/run/tiles/fd_store.c
The shred tile does some of the `is_trusted` checks, but importantly does not do any of the duplicate shred checks, so we need to do these. Because we don't handle repair yet, it's not possible to move all the checks to the shred tile yet.
=> fd_store: pass is_trusted==false for shreds that come from the network

src/ballet/sbpf/fd_sbpf_loader.c, src/ballet/sbpf/fd_sbpf_loader.h, src/ballet/sbpf/fuzz_sbpf_loader.c, src/ballet/sbpf/test_sbpf_load_prog.c, src/ballet/sbpf/test_sbpf_loader.c, src/flamenco/runtime/program/fd_bpf_loader_v2_program.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_bpf_program_util.c, src/flamenco/vm/fd_vm_tool.c
The Agave ELF loader introduced additional checks that would fail on (certain) existing mainnet programs. Since it is impossible to retroactively enforce these checks on already deployed programs, a guard flag is used to enable these checks only when deploying programs. This PR implements the equivalent for FD.
=> deploy_mode flag in ELF Loader

src/flamenco/runtime/tests/run_ledger_tests_all.txt
This ledger test is not needed and it can cause a race condition with the other folder of the same name causing CI to be flaky
=> ci: removing ledger test that is strictly a subset

src/app/ledger/main.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt, src/flamenco/vm/fd_vm_context.c
In the address to host translation, we currently don't check against if we are in a gapped region in memory. This adds the check along with a ledger test that tests this case. It is a temporary holdover before moving over and implementing this check in vm-belt-sanding
=> flamenco, vm: adding memory gap checks for address host translation

src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
the commit for "flamenco: add uwide support for lamport calculations" added an error path to fd_execute_instr that forgets to decrement txn_ctx->instr_stack_sz. Not 100% sure if that error condition is triggerable in practice, but if it is then this would probably break stuff (buffer overflow on txn_ctx->instr_stack)
^ from slack
=> flamenco: decrement instr stack on fd_execute_instr error case

src/util/alloc/fd_alloc.c, src/util/alloc/test_alloc.c, src/util/scratch/fd_scratch.h, src/util/scratch/test_scratch.c, src/util/wksp/fd_wksp_admin.c, src/util/wksp/fd_wksp_io.c, src/util/wksp/fd_wksp_private.h, src/util/wksp/fd_wksp_user.c, src/util/wksp/test_wksp_user.c
1. Style fixes across deep asan uses (scratch, alloc, wksp)
2. Adding unpoisoning on scratch_prepare
3. Removing junk byte memsetting in scratch
4. wksp: poisoning/unpoisoning pinfo on idle stack push/pop
5. updating poisoning/unpoisoining on allocations and frees (poisoning data region + unpoisoning pinfo array)
=> util: deepasan updates

src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt
Missing CU consume for heap size before entry into VM. Porting over change into belt sanding and adding a ledger test
=> flamenco: adding heap cu consume before bpf execution

src/ballet/sbpf/fd_sbpf_loader.c
Addressing the crashes in https://github.com/firedancer-io/auditor-internal/issues/91
The check is basically a copy of https://github.com/firedancer-io/firedancer/blob/32b9530a2115b282b6bb8078b077b81c9cd9019e/src/ballet/sbpf/fd_sbpf_loader.c#L964
=> sbpf: bounds check entry_pc against rodata_sz

src/flamenco/runtime/context/fd_exec_txn_ctx.c, src/flamenco/runtime/context/fd_exec_txn_ctx.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_native_cpi.c, src/flamenco/runtime/sysvar/fd_sysvar_instructions.c, src/flamenco/runtime/sysvar/fd_sysvar_instructions.h, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/vm/fd_vm_syscalls.c
This PR adds transaction instruction tracing, in the same way that Agave does. We keep a list of all instructions that were executed in the current trace.
We need to do this for `sol_get_processed_sibling_instruction`, which requires the full instruction trace.
In cases where we create an instruction info object on the fly, such as CPIs, we now need to ensure this has the same lifetime as the transaction. To do this, we allocate all instruction info objects out of a memory pool, which is owned by the transaction. This also avoids an expensive memcpy when saving traces.
=> flamenco: add instruction tracing

src/app/fdctl/monitor/monitor.c, src/app/fdctl/run/run.c, src/app/fdctl/run/run.h, src/app/fdctl/run/tiles/fd_bank.c, src/app/fdctl/run/tiles/fd_blackhole.c, src/app/fdctl/run/tiles/fd_dedup.c, src/app/fdctl/run/tiles/fd_gossip.c, src/app/fdctl/run/tiles/fd_metric.c, src/app/fdctl/run/tiles/fd_net.c, src/app/fdctl/run/tiles/fd_netmux.c, src/app/fdctl/run/tiles/fd_pack.c, src/app/fdctl/run/tiles/fd_poh.c, src/app/fdctl/run/tiles/fd_quic.c, src/app/fdctl/run/tiles/fd_repair.c, src/app/fdctl/run/tiles/fd_replay.c, src/app/fdctl/run/tiles/fd_replay_thread.c, src/app/fdctl/run/tiles/fd_shred.c, src/app/fdctl/run/tiles/fd_sign.c, src/app/fdctl/run/tiles/fd_store.c, src/app/fdctl/run/tiles/fd_store_int.c, src/app/fdctl/run/tiles/fd_verify.c, src/app/fdctl/run/tiles/fd_verify.h, src/app/fdctl/run/topos/fd_firedancer.c, src/app/fdctl/run/topos/fd_frankendancer.c, src/app/fddev/configure/blockstore.c, src/app/fddev/tiles/fd_benchg.c, src/app/fddev/tiles/fd_bencho.c, src/app/fddev/tiles/fd_benchs.c, src/disco/tiles.h
We are moving some shared tile functionality to the disco folder. The types therefore need to move.
- disco: move tiles types to disco
- chore: move over to new tiles hdr
=> disco: move tile types header to disco

src/flamenco/runtime/program/fd_vote_program.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt
Previously on filtering votes, we were forward iterating through an increasing array and removing each value as an index from a deque. This can lead to the index being shifted leading to incorrect behavior. 
There is a ledger test that demonstrates this case on transaction sig: 5dAiW3rhfkm2gpWnnNigUDURNwwQx2usJJQaSsuDdarBJZjVEwKsq3MNCLFGmeMXtPPCqarPmKEbPb7m99xKPotF.
Fixing nits + adding comments/perma links in relevant function as well
=> flamenco: fixing index shifting for lockout deque in vote program

src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
https://github.com/firedancer-io/auditor-internal/issues/95
https://github.com/anza-xyz/agave/blob/574bae8fefc0ed256b55340b9d87b7689bcdf222/programs/bpf_loader/src/lib.rs#L566
authority_key and authority_address are both `Option<Pubkey>`, so they can be equivalent when they're the same `Some` or when they're both `None`.
=> flamenco: only memcmp authority_key and authority_address when they are not NULL

src/app/fdctl/configure/ethtool.c, src/app/fdctl/run/run.c
Another way of fixing the logfile stdout issue would be to make the logger call `dup` on `STDOUT_FILENO` instead, and use that file descriptor for logging. I'm open to switching to this approach instead.
=> fdctl: more small quality-of-life fixes

src/flamenco/runtime/tests/fd_exec_instr_test.c
During context creation, borrowed account data is initialized through workspace allocation. However, since we use the libc allocator for proceeding data allocations that do not get freed, we need to keep track of which addresses were allocated in the workspace. Then, any new data allocations made during execution can be freed in `_context_destroy` to avoid memory leaks.
=> fuzz, flamenco: fix memory leaks with borrowed account data allocations

src/waltz/quic/fd_quic.c
fd_quic_ack_merge loops thru linked list of acks. On some it calls fd_quic_ack_join. fd_quic_ack_join can modify the links, meaning that it invalidates cur_ack in the caller.
This fix refetches cur_ack
=> quic - fix ack handling to avoid infinite loop

src/waltz/quic/fd_quic.c
https://github.com/firedancer-io/firedancer/pull/2078 introduced a NULL pointer dereference.
This fixes that.
=> quic - fix NULL pointer dereference

src/app/fdctl/run/run.c, src/util/sandbox/fd_sandbox.c, src/util/sandbox/test_sandbox.c
fd_sandbox always defines 'SYS_{...}' macros even when the current
kernel already defines them.  This patch adds ifndef guards to
unbreak Linux 6.8 builds.
Fixes #2086
=> sandbox: fix build on newer kernels

src/util/simd/fd_sse_vf.h, src/util/simd/test_sse_2x64.c, src/util/simd/test_sse_4x32.c
Fixes compatibility with Ivy Bridge CPUs, which have SSE, but not
FMA.
=> simd: mask vf_fma if target doesn't support FMA

src/util/tmpl/test_sort.c
test_sort.c had some type confusion issues where ulong literals
were used in place of floats.  Also used INFINITY which is U.B.
in the Firedancer programming model.
Fixes #2089
=> util: fix test_sort on Clang 18

deps.sh
Allows deps.sh to succeed even if a package was not found.
Fixes #2085
=> deps.sh: use dnf install --skip-broken flag

src/flamenco/fd_flamenco_base.h, src/flamenco/types/Local.mk, src/flamenco/types/fd_cast.h, src/flamenco/types/test_cast.c
This adds `fd_rust_cast_double_to_ulong ` for casting from double to unsigned long the same way as rust.
https://doc.rust-lang.org/rust-by-example/types/cast.html
https://github.com/firedancer-io/auditor-internal/issues/104
https://github.com/firedancer-io/auditor-internal/issues/105
=> flamenco: add fd_rust_cast_double_to_ulong to flamenco/types/fd_cast.h

src/app/fdctl/run/tiles/fd_sign.c, src/ballet/ed25519/fd_curve25519.h
GCC 14 considers the FD_FN_SENSITIVE attribute as part of the
function signature.  We were declaring functions with the attribute
and then assigning them to function pointers without it.
Since the attribute is only available on GCC 14 but we've been
using older versions, we've never noticed that the build is broken.
Fixes #2087
=> Fix GCC 14 build

src/disco/bank/Local.mk, src/disco/bank/fd_rwlock.h, src/disco/bank/fd_txncache.c, src/disco/bank/fd_txncache.h, src/disco/bank/test_txncache.c
The status cache has two main issues,
(1) It's not particularly concurrent, and causes slowdowns when running
with highly parallel bank execution.
(2) It has unbounded memory consumption, and can cause out of memory
conditions when it needs to store large numbers of transactions.
It is rewritten in Firedancer for performance.  The general design is there are two operations which need to be highly concurrent, insert and query, and everything else is rare and happens between slots and can largely just lock the whole thing.
The base case for insert is optimized to two always-uncontended, and one very lightly contended compare and swap.  Query is fully lockless.
The transaction result storage is combined between the snapshot service cache, and the query lookup cache, which more than halves …
=> bank: rewrite status cache

src/app/fdctl/run/tiles/fd_replay.c, src/choreo/ghost/fd_ghost.c, src/choreo/ghost/fd_ghost.h, src/choreo/ghost/test_ghost.c, src/choreo/tower/fd_tower.c, src/disco/tvu/fd_tvu.c
- Introduce fd_ghost_init to the API for initializing a ghost.
- Make parent a required argument for node_insert
given init will handle the special case of initializing the root.
- Change the key to use slot instead of slot_hash. This leverages the
invariant that a vote will only be upserted after successful execution
by the vote program, so the bank hash is implied to be our own.
- Reimplement publish (renamed from prune) to not use an additional buffer
as well as provide a generally cleaner and better commented impl.
- Rework the pretty-print API to support functionality like in the demo
directly (vs. having to be done in the caller).
- Add more tests relating to all the above.
=> refactor(ghost): init, node insert, slot key, publish, print, more tests

src/flamenco/runtime/tests/fd_exec_instr_test.c, src/util/tmpl/fd_deque_dynamic.c, src/util/tmpl/fd_queue.c, src/util/tmpl/fd_queue_dynamic.c, src/util/tmpl/fd_set_dynamic.c, src/util/tmpl/fd_stack.c
UBSAN gets confused on our use of code like 
`(ulong)&(((DEQUE_(private_t) *)NULL)->deque)` 
which equivalent to 
`offsetof(DEQUE_(private_t), deque)`
This PR changes all of those in `util/tmpl` which removes a large number of UBSAN false positives.
=> use offsetof to reduce UBSAN false positives

src/app/fdctl/fdctl.h, src/app/fddev/dump.c
- Properly dump links that are not a tile's primary out
- Allow a few comma separated link names on command line
- Print number of frags dumped from each link
=> fddev/dump: new features for fddev dump

config/extra/with-brutality.mk, config/extra/with-clang.mk, config/extra/with-x86-64.mk
Fixes a bug where Clang specific diagnostic flags are overwritten
by '-Wall'.
=> config: fix clang ordering bug

config/base.mk, config/extra/with-hosted.mk, config/machine/macos_clang_m1.mk
librt provides shm, mq, timer, aio utils which are only available
on hosted targets.  To improve portability, remove them from the
base build configuration.
=> config: only link librt on hosted builds

src/waltz/aio/Local.mk, src/waltz/quic/tests/Local.mk
- Removes mentions of non-existent fd_aio API from fd_quic build rules
- Fix typo that included fd_aio.o in fd_util instead of fd_waltz
=> waltz: fd_aio build fixes

src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h, src/flamenco/runtime/sysvar/fd_sysvar_clock.c, src/flamenco/runtime/sysvar/fd_sysvar_rent.c
https://github.com/firedancer-io/auditor-internal/issues/105
also remove `fd_rent_exempt` since it doesn't appear to be used anywhere
=> flamenco: cast safely with fd_rust_cast_double_to_ulong

config/machine/native.mk
Fixes check-define so the false case declares an empty variable.
Unbreaks native builds.
=> config: fix check-define

src/app/fddev/rpc_client/Local.mk, src/ballet/pack/Local.mk, src/choreo/ghost/Local.mk, src/choreo/tower/fd_tower.c, src/choreo/voter/Local.mk, src/disco/bank/Local.mk, src/disco/shred/Local.mk, src/disco/tvu/Local.mk, src/flamenco/genesis/Local.mk, src/flamenco/gossip/Local.mk, src/flamenco/repair/Local.mk, src/flamenco/runtime/sysvar/Local.mk, src/flamenco/snapshot/Local.mk, src/flamenco/stakes/Local.mk, src/funk/Local.mk, src/util/fibre/Local.mk, src/waltz/udpsock/Local.mk
We have lots of code that assumes a hosted environment (i.e.
workspaces, file system, etc.).  This code shouldn't try to compile
on non-hosted targets.
=> Add missing FD_HAS_HOSTED checks

contrib/test/instr-fixtures.list, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
https://github.com/firedancer-io/auditor-internal/issues/119
Ubsan throws an error if we try to memcpy null pointer with zero length
=> flamenco: bpf loader null memcpy guard

contrib/tool/c.vim, src/util/fd_util_base.h, src/util/tpool/fd_tpool.cxx, src/util/tpool/fd_tpool.h, src/util/tpool/test_tpool.c
This uses the same HPC, low latency, high scalability, NUMA aware, deterministic, fine-grained load-balanced, player-coach distribution strategy used by `fd_tpool_exec_all_block`.  On a dual socket 40-core Icelake at 2.3 GHz, the overhead to dispatch and synchronize to a single thread was ~4 ns and overhead to dispatch and synchronize a kernel to 64 threads (0-31 on socket 0, 32-63 on socket 1), was ~2.2 us.
But it requires a lot less boilerplate to use.  Example:
```
... define a computational kernel
FD_FOR_ALL_BEGIN( vec_add, 1L ) {
double const * restrict x = (double const *)_a0;
double const * restrict y = (double const *)_a1;
double       * restrict z = (double       *)_a2;
for( long i=block_i0; i<block_i1; i++ ) z[i] = x[i] + y[i];
} FD_FOR_ALL_END
... have tpool threads [t0,t1) …
```
=> Helpers to simplify implementing HPC thread parallelism

src/util/rng/Local.mk, src/util/rng/fd_rng.h, src/util/rng/fd_rng_secure.c, src/util/rng/test_rng.c
Adds secure RNG for Linux, FreeBSD, and macOS.
=> rng: add fd_rng_secure API

src/flamenco/capture/Local.mk, src/flamenco/capture/fd_solcap_writer.h, src/flamenco/capture/fd_solcap_writer_stub.c
Allows executing Solana transactions on non-hosted targets.
=> capture: add a stub implementation of fd_solcap_writer_t

src/util/shmem/fd_shmem_admin.c
Always compile shmem's cstr helpers, not just on hosted platforms.
=> shmem: always compile cstr utils

config/extra/with-lz4.mk, config/extra/with-x86-64.mk, deps.sh, src/flamenco/snapshot/fd_snapshot_istream.h, src/util/checkpt/Local.mk, src/util/checkpt/fd_checkpt.c, src/util/checkpt/fd_checkpt.h, src/util/checkpt/fd_restore.c, src/util/checkpt/test_checkpt_mmio.c, src/util/checkpt/test_checkpt_stream.c, src/util/fd_util.h, src/util/fd_util_base.h
This implements low level APIs installed to facilitate high performance workspace checkpointing and fast snapshots.
- Currently needs proper updating of deps.sh to include the appropriate lz4 library (will work without it though ... compressed frames will not be supported).
- Also added a missing FD_HAS_ZSTD default to fd_util_base.h to match FD_HAS_LZ4 and fixed an #if / #ifdef confusion in fd_snapshot_istream.h.
=> Low level fast parallel compressed checkpointing

deps.sh
Upgraded deps, so that snappy compiles on mac.
For rocksdb, removing `haswell` leads to uninitialized issues on avx512, so added the `-Wno-uninitialized`
=> deps: snappy, rocksdb to compile on mac

src/ballet/bigint/fd_uint256_mul.h
Provides an alternative to the x86-only _subborrow_u64 intrinsic
using __builtin_subcll.
=> bn254: fix support for non-x86

src/flamenco/runtime/program/fd_compute_budget_program.c
This was feature gated by `remove_deprecated_request_unit_ix`, which has been activated on all networks.
=> flamenco, runtime: remove support for RequestUnitsDeprecated instruction

src/flamenco/runtime/program/fd_bpf_loader_v2_program.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_bpf_program_util.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/vm/fd_vm_base.h, src/flamenco/vm/fd_vm_tool.c, src/flamenco/vm/syscall/fd_vm_syscall.c
As of the activation of `disable_deploy_of_alloc_free_syscall`, which is activated on all networks, programs can no longer be deployed which use the `sol_alloc_free_` syscall.
=> flamenco, vm: implement disable_deploy_of_alloc_free_syscall

src/flamenco/vm/Local.mk, src/flamenco/vm/fd_vm.c, src/flamenco/vm/fd_vm_base.h, src/flamenco/vm/instr_test/jump.instr, src/flamenco/vm/syscall/Local.mk, src/flamenco/vm/syscall/test_vm_syscalls.c, src/flamenco/vm/test_vm_instr.c, src/flamenco/vm/test_vm_interp.c, src/flamenco/vm/test_vm_util.c, src/flamenco/vm/test_vm_util.h
This a feature-flag-guarded check, which means `fd_vm` will now attempt to access `instr_ctx` (which means assigning it to NULL is not safe).  Had to refactor the unit tests to initialize a barebones instruction context
=> flamenco, vm: add reject callx r10 check in vm_validate

src/app/fdctl/Local.mk, src/disco/bank/fd_rwlock.h, src/disco/topo/Local.mk, src/disco/tvu/fd_pending_slots.c, src/disco/tvu/fd_replay.c, src/flamenco/gossip/fd_gossip.c, src/flamenco/repair/fd_repair.c, src/flamenco/runtime/fd_bank_hash_cmp.c, src/flamenco/runtime/fd_readwrite_lock.h, src/flamenco/snapshot/Local.mk
Closes #2178
Unfortunately, excessive use of tpool breaks basic functionality like fd_vm on targets without threads. Fixing that is a larger change that is out of scope for this PR.
=> Fix broken build on platforms without threads

src/flamenco/runtime/tests/fd_exec_sol_compat.c
Fuzzers crash when feeding in a Protobuf message that cannot be decoded due to wksp allocations not being cleaned up properly
=> fuzz, flamenco: fix wksp memory leaks when failing to decode protobufs

.github/workflows/clusterfuzz.yml, .github/workflows/coverage_report_clusterfuzz.yml
Submodules need to be fetched so that fdctl's version.h [generator script](https://github.com/firedancer-io/firedancer/blob/7541b4bb0645a311922132f60959f03e30aa0bf7/src/app/fdctl/with-version.mk#L15) can correctly determine FIREDANCER_VERSION_PATCH
This fixes the clusterfuzz ci scripts
=> ci: fix clusterfuzz publish script

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_enum.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/templ/fd_quic_frame_types_templ.h, src/waltz/quic/tests/fd_quic_sandbox.c
ack->tx_time should have been updated upon acking. This PR fixes that
We were not enforcing the frame type rules. This PR fixes that also
=> Avoid unnecessary acks, enforce frame type restrictions

contrib/test/instr-fixtures.list, src/flamenco/runtime/context/fd_exec_instr_ctx.h, src/flamenco/runtime/fd_account.c, src/flamenco/runtime/fd_account.h, src/flamenco/runtime/fd_account_old.h, src/flamenco/runtime/fd_borrowed_account.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_system_program.c, src/flamenco/runtime/program/fd_vote_program.c
A follow up to this pr will be to replace the logic in the rest of the native programs with these updated APIs and a total tearout of fd_account_old
Also fixes: 
https://github.com/firedancer-io/auditor-internal/issues/107
https://github.com/firedancer-io/auditor-internal/issues/119
=> flamenco: borrowed account scoping macro + fd_account api cleanup

src/flamenco/nanopb/Local.mk, src/util/tmpl/Local.mk
This allows flamenco to be used as a library
=> flamenco, util: add missing add-hdr declarations 

src/app/fdctl/run/tiles/fd_gossip.c, src/app/fdctl/run/tiles/fd_replay.c, src/app/fdctl/run/topos/fd_firedancer.c, src/disco/topo/fd_topo.h
This PR creates 2 links: a `gossip->replay` link passes contact information (IP/port of TPU vote) to replay tile and a `replay->net` link helps the replay tile send vote txns. 
I wonder whether we should merge this PR -- most of the code should be removed later and moved to the new tile that Liam is working on. It also doesn't hurt to merge it because the code will only be executed if `consensus.vote = true` in the toml.
=> replay: get leader contact info and send vote txns to the leader TPU

src/flamenco/runtime/tests/Local.mk, src/flamenco/runtime/tests/fd_exec_instr_test.h, src/flamenco/runtime/tests/fd_exec_sol_compat.c, src/flamenco/runtime/tests/fd_vm_validate_test.c, src/flamenco/runtime/tests/fd_vm_validate_test.h, src/flamenco/runtime/tests/generated/vm.pb.c, src/flamenco/runtime/tests/generated/vm.pb.h, src/flamenco/vm/fd_vm.c, src/flamenco/vm/fd_vm_base.h
- Adds fuzzing harness for `fd_vm_validate`
- Some changes to the validate function:
- Shift overflow checks for `BPF_ARSH` (0xc4) and ` BPF_ARSH64` (0xc7)
- New error code for shift overflow (`FD_VM_SH_OVERFLOW`)
- Boundary checks
- New error code (`FD_VM_ERR_BAD_TEXT`)
- Text size alignment checks
- New error code (`FD_VM_TEXT_SZ_UNALIGNED`) 
- Empty `text_cnt` checks
- Additional immediate checks for LDQ (0x18) instructions
=> flamenco, fuzz: fuzz `fd_vm_validate`

src/waltz/quic/fd_quic.c, src/waltz/quic/templ/fd_quic_frames_templ.h, src/waltz/quic/templ/fd_quic_templ.h
The quic/templ plumbing generates a 'handle_frame' prototype for
each structure that appears in fd_quic_frames_templ.h.  There are
some structs in this file that aren't frames, and we have to define
dummy frame handlers for these.
This commit moves these structs into 'fd_quic_templ.h' and removes
the dummy frame handler functions.
=> quic: remove invalid frame handler prototypes

src/waltz/quic/crypto/fd_quic_crypto_suites.c, src/waltz/quic/crypto/fd_quic_crypto_suites.h, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn_id.h, verification/stubs/fd_quic_crypto.c
- Unifies all cryptographically secure RNG through fd_rng_secure.
- Adds fd_conn_id_rand helper function
- Fixes missing error handling on RNG failure
=> quic: polish RNG handling

src/util/fd_util.h, src/util/spad/Local.mk, src/util/spad/fd_spad.c, src/util/spad/fd_spad.h, src/util/spad/test_spad.c
By popular demand, this is a more general implementation of the non-alloca parts of util/scratch (and it probably makes sense at some point to convert the util/scratch equivalents to use this under the hood).
From the documentation, a spad is a scratch pad that behaves very much like a thread's stack:
- Spad allocations are very fast O(1) assembly.
- Spad allocations are grouped into a frames.
- Frames are nested.
- Pushing and popping frames are also very fast O(1) assembly.
- All allocations in a frame are automatically freed when the frame is popped.
Unlike a thread's stack, the most recent allocation can be trimmed, the most recent sequence of allocations be undone, operations on a spad can by done more than one thread, threads can operate on multiple spads and, if the spad is backed …
=> High performance persistent shared scratch pads

src/app/fdctl/Local.mk, src/app/fdctl/config.c, src/app/fdctl/config.h, src/app/fdctl/config_parse.c, src/app/fdctl/config_parse.h, src/app/fdctl/test_config_parse.c
- Ensure fdctl_cfg_from_env zero-initializes config_t
- Fix incorrect return code in fdctl_pod_to_cfg
- Add unit test rejecting invalid config keys
- Add fdctl_cfg_validate API to validate fields from default.toml
- Add unit test asserting that parsing default.toml works
- Add unit test selectively overriding a field
=> fdctl: fix config bugs

src/disco/shred/fd_shred_cap.c
Previously, an assignment was confused for an equality check
=> Fix nshredcap_hdr read size check

src/waltz/quic/fd_quic.c
TPU only uses short-lived streams so we shouldn't ever see a
STOP_SENDING frame from a peer.  This patch changes frame handling
logic to ignore but ACK STOP_SENDING frames instead of dropping
the packet.
=> quic: gracefully ignore STOP_SENDING frame

src/flamenco/runtime/fd_rocksdb.c, src/flamenco/runtime/program/fd_bpf_loader_v2_program.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
We are not supposed to assign a callee instruction as a signer if it is a derived signer. This was causing CU mismatches
=> vm, flamenco: removing extraneous signer assignment in CPI

src/waltz/quic/fd_quic_conn_id.h
Padding is included in the hash. In the past the padding had been forced to zero. This allows a multiple of 8 to be used for all the operations.
A change introduced code that did not clear the pad, resulting in hash mismatches.
This fix clears the whole structure, including the padding
=> quic - changed fd_quic_conn_id_rand to clear whole structure

src/app/fdctl/config.c
fd_toml_parse can return negative numbers.  Thus we shouldn't
print 'Invalid config at line -2'.
Error details are logged to warning log anyways.
=> fdctl: fix misleading TOML error message

src/flamenco/runtime/program/fd_vote_program.c
This fix corresponds to the `credits_for_vote_at_index` function in agave 1.18.15: https://github.com/anza-xyz/agave/blob/v1.18.15/sdk/program/src/vote/state/mod.rs#L527
=> fix(flamenco): a bank hash mismatch caused by vote credits in the vote program

src/flamenco/vm/syscall/fd_vm_syscall_cpi.c
Check that the callee program account is executable in cpi, not the caller. The caller will have already been checked further up in the pipeline. This mirrors Agave's semantics.
=> flamenco, vm: fix executable check in cpi

src/ballet/x509/fd_x509_mock.c, verification/proofs/x509_mock/Makefile, verification/proofs/x509_mock/cbmc-viewer.json, verification/proofs/x509_mock/fd_x509_mock_harness.c
Proves that the fd_x509_mock parser is free of U.B. using CBMC.
=> x509: add CBMC proof for parser

.github/workflows/clusterfuzz.yml
This change splits the builds for clusterfuzz and solfuzz.
The solfuzz build should not use ubsan.
The builds are not sequentially dependent.
=> solfuzz-publish without ubsan

src/app/fdctl/run/tiles/fd_replay.c, src/app/fdctl/run/topos/fd_firedancer.c, src/disco/bank/fd_txncache.c, src/disco/poh/fd_poh_tile.c, src/flamenco/runtime/fd_runtime.c
Fixes an issue where we push stakes too early to poh tile and where pack gets corrupted frags and fixes some status cache issues.
=> firedancer: fix epoch transition and pack topo

.github/actions/deps/action.yml, .github/workflows/tests.yml, deps.sh
Adds multiple compiler support to CI. You can configure different compiler versions for tests. Also will make sure deps are build with the same compiler, or a compiler of your request.
=> ci: unit tests for compiler versions

src/flamenco/runtime/fd_borrowed_account.h
While working on test-vectors, we realized that [try_borrow_instruction_account()](https://github.com/anza-xyz/agave/blob/v2.0.1/sdk/src/transaction_context.rs#L647) can fail on `get_index_of_program_account_in_transaction`, and thus returns [NotEnoughAccountKeys](https://github.com/anza-xyz/agave/blob/v2.0.1/sdk/src/transaction_context.rs#L551).
=> Fix try_borrow_instruction_account return code

src/flamenco/runtime/program/fd_address_lookup_table_program.c
we were just adjusting the compute meter instead of checking to see if we had enough cu to execute at all
=> alut_fixes: modernize cu consumption

src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/tests/generated/invoke.pb.c, src/flamenco/runtime/tests/generated/invoke.pb.h, src/flamenco/runtime/tests/generated/txn.pb.c, src/flamenco/runtime/tests/generated/txn.pb.h
Seed address field for accounts was not getting set correctly
=> flamenco: fix segfault when dumping instructions

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/tests/test_quic_tls_hs.c, src/waltz/quic/tls/fd_quic_tls.c, src/waltz/quic/tls/fd_quic_tls.h
Removes the 'peer_transport_params' buffer from handshake state.
Instead, parse the peer's transport parameters as soon as we
receive them.  Introduces a new callback to do so.
=> quic: don't buffer peer's transport params

src/flamenco/runtime/context/fd_exec_slot_ctx.h, src/flamenco/runtime/fd_hashes.c, src/flamenco/runtime/fd_runtime.c
```
[Replay]
slot:             281357641
bank hash:        Fpyqu9KBdZ755yaT3a6cMWWR5xr1rBJ6Q1HRJuDBGA2w
parent bank hash: 3L2Zim8wh1Z27jT8Xg3Y6xYgQ8euqNDx9i95bVLpj5Sv
accounts_delta:   AEUc5ZixZ8MpR5kt2DGmRmKckBZLoXb78QDtsuKiHrQY
signature_count:  12395
last_blockhash:   9Kh3zRE4frzcnoDKCQBymSawt8wcm8u5ipNtkzZgN2cZ
NOTICE  07-15 17:27:22.731496 256445 5    0    src/app/ledger/main.c(318): replay completed - slots: 31, elapsed: 28.419037 s, txns: 107324, tps: 3776.482597, sec/slot: 0.916743
```
Agave uses parent slot signature count to determine fees. We were incorrectly passing in the signature count of the current slot which would be default to 0 at the current point in time
=> flamenco: update fee calculator to use parent signature count

src/waltz/quic/fd_quic.c, src/waltz/quic/tests/test_quic_tls_hs.c, src/waltz/quic/tls/fd_quic_tls.c, src/waltz/quic/tls/fd_quic_tls.h
Fixes https://github.com/firedancer-io/firedancer/issues/2351 by storing self transport params in the decoded form.  Now encodes transport params on demand.
Depends on #2361  #2362
=> quic: improve handling of self transport params

src/waltz/quic/crypto/fd_quic_crypto_suites.c, src/waltz/quic/crypto/fd_quic_crypto_suites.h, src/waltz/quic/fd_quic.c, src/waltz/quic/templ/fd_quic_encoders.h, src/waltz/quic/tests/fuzz_quic_wire.c, src/waltz/quic/tests/test_quic_crypto.c
Account for ethernet frames with padding
Disable PING keep alive
Encryption of short packet number. Not used, but helps testing of decryption of short packet numbers
=> QUIC - various fixes

src/waltz/quic/fd_quic.c
Fixes an issue where the instance-wide fd_quic_transport_params_t instance is modified ad-hoc by connection logic.
In theory, this could result in data from one connection leaking bleeding into another.
=> quic: don't mutate shared transport parameters 

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/tls/fd_quic_tls.h
Previously, an fd_quic server retained the tls_hs object for the
lifetime of a connection.  The fd_quic client freed it as soon as
it saw a 'handshake_done' frame.
With this patch, the server now frees the tls_hs object as soon as
the client ACKs the 'handshake_done' frame sent by the server.
Technically, the server can free it as soon as it sends it.  This
can be optimized in a future patch.
Changes:
- Move 'handshake_{complete,done_send,done_ackd},hs_data_empty'
into a bit field
- Set 'conn->handshake_done_ackd' when a handshake_done frame is
ACKed by the client (previously, this flag was always 0)
- Document APIs that accept a NULL tls_hs object
- Remove unused function 'fd_quic_handshake_complete'
=> quic: free server-side tls_hs when peer ACKs handshake_done

src/flamenco/runtime/sysvar/fd_sysvar_clock.c
sysvar_clock_read was not checking the cache before hitting the db.  This is an issue for test drivers that only set the cache
=> flamenco: add cache check to clock_read

src/ballet/ed25519/fd_curve25519.c
Removing redundant code, in particular no need to change any test.
When we added ristretto, we added the function `fd_f25519_sqrt_ratio()`. This already handles all the cases and returns whether the input was a square (i.e. sqrt exists) or not.
=> ed25519: simplify decompress code

.github/workflows/ledgers.yml, src/flamenco/runtime/tests/run_ledger_test.sh, src/flamenco/runtime/tests/run_ledger_tests_all.py
* The max pages that can be used for a test (given the current list in `run_ledger_tests_all.txt`) is 45+32=77 and if we run 4 of them in parallel, we need a total page count of 308, hence bumped the limit in the action
* If we add a high core count box with the same memory, it would try to schedule many parallel runs and might fail to allocate memory, hence introduced the function to set the number of batches getting executed and defaulted to 4
* Set the dump dir outside the repository directory in CI so that we can save a minute by not having to re-download the ledgers
=> ledger: increase parallelism and specify directory

src/flamenco/runtime/program/fd_address_lookup_table_program.c
address lookup table was masking out the returned error code
=> alut_error_mask: Fix alut error mask bug

src/flamenco/runtime/tests/fd_exec_instr_test.c
Otherwise, we get deep asan crashes during fuzzing, due to the dynamic array `txn_descriptor->instr` being out of bounds.
=> fix txn_descriptor allocation size

contrib/quic/agave_compat/src/main.rs, src/app/fdctl/run/tiles/fd_quic.c, src/app/fddev/tiles/fd_benchs.c, src/app/fddev/txn.c, src/waltz/quic/tests/fd_quic_test_helpers.c
- Reduce TPU/QUIC stream limit to FD_TXN_MTU
- Fixes empty stream size limit in anonymous QUIC test instances
- Set RX stream limit to 0 for 'fddev txn' and 'benchs'
(These tiles only send)
Closes https://github.com/firedancer-io/firedancer/issues/2456
=> Fix QUIC RX stream size limits

src/waltz/quic/fd_quic.c
fddev bench wasn't working because fd_quic.c was using tx_initial_max_stream_data instead of rx_initial_max_stream_data
This fixes it
=> quic: fix type on max_stream_data: tx -> rx

src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_exec_sol_compat.c, src/flamenco/runtime/tests/fd_exec_sol_compat.h, src/flamenco/runtime/tests/test_exec_instr.c, src/flamenco/runtime/tests/test_exec_sol_compat.c
For all targets...
* Migrate from libc to wksp allocators for fuzzing / CI tests
* Add leak detection for fuzzing / CI tests (now aborts on a wksp leak)
Tested so far in...
- CI 
- Instruction fuzzing
=> fuzz, flamenco: migrate sol compat targets to wksp allocators + add wksp leak detection

src/waltz/quic/crypto/fd_quic_crypto_suites.c, src/waltz/quic/fd_quic.c
The fd_quic client does all the necessary computatations to verify
a QUIC Retry Integrity Tag (RFC 9001).  But it ignores the result.
This was probably not a problem, but this patch updates the retry
handling logic to validate tags as recommended by the spec.  This
improves resiliency against connection tampering attempts by
unauthenticated attackers.
=> quic: validate Retry Integrity tags client-side

src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c
Agave does not reclaim accounts at the tx execution level. This causes mismatches between our transaction fuzzing / replay harnesses.
=> flamenco: decouple account reclaiming from txn execution pipeline

book/snippets/ethtool-gro.ansi
The embedded ansi codes were causing `bun run build` to hang
=> book: fix ethtool-gro.ansi

src/flamenco/vm/syscall/fd_vm_syscall_pda.c
Agave uses [1,255] bump seeds, whereas we use [0,255].
Reported by Ben Hawkes
=> flamenco, vm: fix try_find_program_address iteration count

src/flamenco/runtime/fd_executor.c
Should not be using the old sysvar cache to get rent
=> flamenco: don't use old sysvar cache to get rent

src/waltz/quic/Local.mk, src/waltz/quic/crypto/fd_quic_crypto_suites.c, src/waltz/quic/crypto/fd_quic_crypto_suites.h, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_retry.h, src/waltz/quic/tests/test_quic_retry_unit.c
- Clean up and document fd_quic_retry_integrity_tag_{encrypt,decrypt}
- Add a simple benchmark
=> quic: benchmark retry handling

src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt
agave checks the last 150 blockhashes by using `<=`
```
fn is_hash_index_valid(last_hash_index: u64, max_age: usize, hash_index: u64) -> bool {
last_hash_index - hash_index <= max_age as u64
}
```
To handle this on our end, we need to replace using the recent blockhashes with the block hash queue and do a check against the 151 most recent block hashes
=> flamenco: update blockhash check to use blockhash queue

src/flamenco/vm/syscall/fd_vm_syscall_util.c
As already speculated in the FIXME comment, the log should not have a newline. Otherwise, we observe a log mismatch with agave.
=> remove newline from sol_log_compute_units

src/flamenco/vm/syscall/fd_vm_syscall_util.c, src/flamenco/vm/syscall/test_vm_syscalls.c
Currently, these are example logs from Firedancer and agave:
```
Program log: 5d724c44c0a108c8 ac246eae6b5f6c8a 7bd2aac7cd318b02 b8fb78d524538540 7a3034c712804303
Program log: 0x5d724c44c0a108c8, 0xac246eae6b5f6c8a, 0x7bd2aac7cd318b02, 0xb8fb78d524538540, 0x7a3034c712804303
```
=> match sol_log_64 output

src/util/bits/fd_bits.h
UBSan generally reports pointer arithmetic errors, such as applying
offsets to NULL pointers.  fd_ptr_if allows the compiler to evaluate
both the truthy and falsy expression before evaluating the condition.
Thus, UBSan always reports errors for both expressions, even if a result
is not taken.
With this patch, only the taken expression is evaluated.
=> Fix fd_ptr_if UBSan false positives

src/flamenco/vm/syscall/fd_vm_syscall_util.c, src/flamenco/vm/syscall/test_vm_syscalls.c
To quote from an agave doc comment:
> any program-generated output is guaranteed to be prefixed by "Program log: "
https://github.com/firedancer-io/solana/blob/a5c7c999e2060971d9369bde13e05247c9ddd415/program-runtime/src/stable_log.rs#L41
=> add 'Program log: ' prefix to sol_log to match agave

src/ballet/shred/fuzz_shred_parse.c
Adds support for chained and resigned variants.
=> shred: update fuzz_shred_parse.c

src/waltz/quic/fd_quic.c, verification/proofs/quic/process_packet/fd_quic_process_packet_harness.c
- Validate that sub-packet memory ranges are within bounds
- Remove DECODE_UINT32 macro
- Fix unreachable 'force version negotiation' branch
=> quic: improve process_packet harness

src/flamenco/runtime/tests/fd_exec_instr_test.c
The txn fuzzer may generate larger-than-expected raw transactions
=> fuzz: set higher cap for raw txn alloc

src/flamenco/runtime/sysvar/fd_sysvar_last_restart_slot.c, src/flamenco/runtime/sysvar/fd_sysvar_last_restart_slot.h, src/flamenco/vm/syscall/fd_vm_syscall.c, src/flamenco/vm/syscall/fd_vm_syscall.h, src/flamenco/vm/syscall/fd_vm_syscall_runtime.c
We've implemented the sysvar but not the syscall. This will be activated on mainnet in the next epoch.
=> flamenco, vm: implement last restart slot syscall

contrib/ledger-gen/run_cluster.py, contrib/ledger-gen/src/ledgers.rs, contrib/ledger-gen/src/main.rs, contrib/ledger-gen/src/stake.rs, src/flamenco/features/fd_features_generated.c, src/flamenco/features/fd_features_generated.h, src/flamenco/features/feature_map.json, src/flamenco/runtime/program/fd_stake_program.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json
agave has added two new stake instructions: https://github.com/anza-xyz/agave/pull/1928
=> runtime: move stake and move lamports instructions

src/app/ledger/main.c, src/flamenco/features/fd_features_generated.c, src/flamenco/features/feature_map.json, src/flamenco/runtime/fd_acc_mgr.c, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_bpf_loader_serialization.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt
1. Fixing handling for lookup table accounts, we previously didn't iterate over them
2. Setting rent epoch for accounts that don't exist, instead of defaulting to 0
3. removing set_exempt_rent_epoch_max feature flag guard
=> flamenco: better rent epoch handling

src/app/fddev/tiles/fd_benchg.c
Previously, transactions contained a single compute budget `set_cu_price` instruction. For some reason, the VM set the transaction's CU limit to 0. (Strangely different behavior from how transaction cost is estimated). "Executing" the compute budget program instruction costs 150 CUs, so the transaction was failing with `ComputationalBudgetExceeded`.
=> bench: make bench transactions succeed

src/ballet/txn/fd_txn.h, src/ballet/txn/fd_txn_parse.c, src/flamenco/runtime/fd_blockstore.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/types/fd_types_custom.c
allow_zero_signatures was an ugly hack added by the runtime team,
only used for testing.  We have since moved on to better testing
so we can remove this hack.
=> txn: remove allow_zero_signatures flag

config/extra/with-security.mk
The relro link flag protects more memory regions as read-only post
startup.  Makes binary sizes and startup times slightly worse.
Also fixes some instances of link flags not being set correctly.
Closes https://github.com/firedancer-io/auditor-runtimeverification/issues/54
=> config: enable -z relro

.github/workflows/clusterfuzz.yml, config/everything.mk
Fixes unnecessary nesting of executables in the fuzz-test dir.
Previously: OBJDIR/fuzz-test/fuzz_example/fuzz_example
Now:        OBJDIR/fuzz-test/fuzz_example
=> config: flatten fuzz-test dir

src/app/fdctl/run/tiles/fd_gossip.c, src/app/fdctl/run/tiles/fd_quic.c, src/app/fdctl/run/tiles/fd_sender.c, src/app/fdctl/run/tiles/fd_shred.c, src/app/fdctl/run/tiles/fd_sign.c, src/disco/consensus/test_gossip_echo_vote.c, src/disco/keyguard/Local.mk, src/disco/keyguard/fd_keyguard.h, src/disco/keyguard/fd_keyguard_authorize.c, src/disco/keyguard/fd_keyguard_client.c, src/disco/keyguard/fd_keyguard_client.h, src/disco/keyguard/fd_keyguard_match.c, src/flamenco/gossip/fd_gossip.c, src/flamenco/gossip/fd_gossip.h, src/flamenco/repair/fd_repair.c, src/flamenco/repair/fd_repair.h, verification/proofs/keyguard/ambiguity/fd_keyguard_ambiguity_proof.c, verification/proofs/keyguard/authorize/Makefile, verification/proofs/keyguard/authorize/fd_keyguard_authorize_proof.c
Previously, support for ed25519_sign(sha256(x)) signing was
implemented ad-hoc in a way that broke ambiguity proofs.
This patch adds the signature scheme as an explicit param to the
signing request body.  Also removes various arbitrary hardcoded
parameters and edge cases from the sign tile.
=> keyguard: fix support for multiple signing methods

src/flamenco/vm/fd_vm_private.h
in practice the input region can never be larger than UINT_MAX, but removing the downcast to help AR
=> flamenco: removing downcast to uint

src/flamenco/runtime/program/fd_stake_program.c
solana does not fail if this line returns an error:
```
let vote_state = vote_account.get_state::<VoteStateVersions>();
```
=> flamenco: remove return on failed fd_vote_get_state

contrib/test/run_test_vectors.sh, src/ballet/ed25519/avx512/fd_f25519.h, src/ballet/ed25519/fd_curve25519_scalar.h, src/ballet/sha256/fd_sha256.c, src/ballet/utf8/fd_utf8.c, src/flamenco/runtime/fd_acc_mgr.c, src/flamenco/runtime/program/fd_address_lookup_table_program.c, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_bpf_program_util.c, src/flamenco/runtime/program/fd_config_program.c, src/flamenco/runtime/program/fd_stake_program.c, src/flamenco/runtime/program/fd_system_program.c, src/flamenco/runtime/program/fd_vote_program.c, src/flamenco/runtime/program/fd_zk_elgamal_proof_program.h, src/flamenco/runtime/program/zksdk/fd_zksdk.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_exec_instr_test.h, src/flamenco/runtime/tests/fd_exec_sol_compat.c, src/flamenco/runtime/tests/fd_vm_validate_test.c, src/flamenco/runtime/tests/fd_vm_validate_test.h, src/flamenco/runtime/tests/test_exec_instr.c, src/flamenco/types/fd_bincode.h, src/util/fd_util_base.h, src/util/wksp/fd_wksp_user.c
=> test-vectors: fix asan/ubsan complains

src/app/fdctl/run/tiles/fd_quic.c, src/app/fdctl/run/tiles/fd_shred.c
Ensure that incoming UDP packets can fit at least a minimum size transaction.
=> Drop tiny TPU/UDP packets

src/flamenco/runtime/fd_executor_err.h
So far we had to handle special logic to check precompiles result, as the error code is different in firedancer than agave.
With this change (and corresponding change in solfuzz-agave), we no longer need special comparisons.
All precompiles only return success/fail, one single error code.
=> precompiles: simplify return err code

src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h, src/flamenco/runtime/tests/fd_exec_instr_test.c
We should record any sanitization errors in txn parsing so we stay conformant with Agave.
=> fuzz, flamenco: record sanitization errors in txn parsing

src/ballet/bn254/fd_bn254.c, src/flamenco/vm/syscall/fd_vm_syscall_crypto.c
- Harden fd_bn254 to deal with overlapping in and out
- Indirect output write via a buffer in the syscall handler
Reported-by: Ben Hawkes <hawkes@isosceles.com>
=> vm: fix aliasing in sol_alt_bn128_compression

src/app/fdctl/config/default.toml, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/tests/fd_quic_test_helpers.c, src/waltz/quic/tests/fuzz_quic.c, src/waltz/quic/tests/fuzz_quic_wire.c
Added a fixed minimum of 16 streams per connection, and fixed the code
Changed the weighting scheme to use a power law, so connections with very few streams will be assigned some with priority
Changed packet metadata to track what value was used for MAX_STREAMS. This is important, or an update can get lost, and the server won't know the client still needs the update.
max_data in packet metadata wasn't being set. Not terribly relevant as we initialize it to an extreme value.
Set `default.toml` quic connections and streams to decent values which actually work with `fddev bench`
=> quic - fixed bugs relating to stream pool assignments and MAX_STREAMS frames, changes to defaults.toml

src/waltz/quic/templ/fd_quic_frame_types_templ.h
Thanks to Immunefi user @ret2happy for reporting this bug. Fixes https://github.com/firedancer-io/auditor-internal/issues/181
=> quic: fix frame_type validation

src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_exec_sol_compat.c, src/flamenco/runtime/tests/test_exec_sol_compat.c, src/flamenco/vm/fd_vm_base.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c
~~Introduces a "stubbed" version of `libfd_exec_sol_compat` that wraps around `fd_execute_instr` for CPI syscall fuzzing.~~
Supporting CPI syscalls implements the following:
- Performing a full `_instr_context_create` (i.e, `is_syscall = false`) specifically for CPI calls 
- Summing up account lamports during `_instr_context_create`
- Capturing of data from input_data_regions into SyscallEffects
- Tool to dump `SyscallContext` at CPI entrypoint
Further cleanup:
- Fixed scratch frame mismanagement, particularly use-after-free when writing to output buffer
=> flamenco, fuzz: Fuzz VM CPI syscalls

contrib/test/run_test_vectors.sh, src/app/fdctl/run/tiles/fd_replay.c, src/app/ledger/main.c, src/flamenco/runtime/context/fd_exec_slot_ctx.h, src/flamenco/runtime/context/fd_exec_txn_ctx.c, src/flamenco/runtime/context/fd_exec_txn_ctx.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_precompiles.c, src/flamenco/runtime/program/fd_precompiles.h, src/flamenco/runtime/program/fd_system_program.h, src/flamenco/runtime/program/fd_system_program_nonce.c, src/flamenco/runtime/tests/fd_exec_instr_test.c
1. Adding various prep checks: fixing blockhash check, robust fee collection, duplicate accounts, etc.
2. Tearing out old code
3. Refactoring checks to maintain order with agave
future work would be to combine a lot of the duplicate loops in the txn ctx and propagate the errors forward to maintain txn error ordering with agave
=> flamenco: transaction setup code optimization + rewrite

src/util/tmpl/fd_deque.c, src/util/tmpl/fd_deque_dynamic.c, src/util/tmpl/test_deque.c, src/util/tmpl/test_deque_dynamic.c
Adding by popular demand (hat tip to Josh and the folks at Asymmetric Research).  This mimics some implicitly specified behaviors in the Rust equivalent APIs and simplifies replicating that behavior in C/C++. Specifically, push_head_wrap will implicitly deque the tail element first if the deque is full (and vice vice for push_tail_wrap).
Additionally, made it clearer that max==0 run-time sized deques are supported (including unit test coverage so it doesn't get accidentally broken in the future) and stubbed out the handholding checks for the new API to help AR with various testing tasks.
=> util: Added APIs for deque wrapping push_head / push_tail

.github/workflows/clusterfuzz.yml, src/flamenco/runtime/tests/Local.mk, src/flamenco/runtime/tests/fd_exec_instr_test.c
For certain fuzz harnesses (namely, the CPI syscall), we want to control the scope of the fuzzer (which is coverage-guided) by stubbing out certain functions. This PR uses ld's `--wrap` functionality to stub out `fd_execute_instr`. 
This is currently a simple stub, but the plan is to simulate the effects of an `fd_execute_instr` call so that the CPI clean up stage isn't effectively a NO-OP. Wrap allows us to redefine functions in a separate translation unit, which would give the fuzz harnesses more control over what it can do (particularly, access to static variables within TUs).
=> flamenco, fuzz: stub out fd_execute_instr with --wrap

src/flamenco/runtime/tests/fd_exec_instr_test.c
Closes [#187](https://github.com/firedancer-io/auditor-internal/issues/187) and [#189](https://github.com/firedancer-io/auditor-internal/issues/189)
=> fuzz, flamenco: use slot context valloc for slot ctx fields

src/flamenco/runtime/fd_executor.c
Should return a negative number so nonce decoding failures return the correct error
Closes [#190](https://github.com/firedancer-io/auditor-internal/issues/190)
=> flamenco: fd_executor_is_system_nonce_account incorrect return code

contrib/test/instr-fixtures.list, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.json
Booleans are decoded differently than uchars - if the byte value is not 0 or 1, the decoding fails.
=> flamenco: fix epoch rewards "active" type (+ other Agave bool types)

src/waltz/tls/fd_tls_estate.h
This was not a real bug. A handshake will never get this big, but it is good practice to do casting right.
Drive-by: comment typos
=> quic: fix casting precedence in fd_tls_transcript_load

contrib/test/instr-fixtures.list, src/flamenco/runtime/program/fd_bpf_loader_v3_program.c, src/flamenco/runtime/program/fd_native_cpi.c
* Using correct buffer data len
* Modifying inherited signer and writable status in native program CPI calls
=> flamenco: various BPF loader v3 mismatch fixes

src/waltz/quic/tls/fd_quic_tls.c
fixes https://github.com/firedancer-io/auditor-internal/issues/194
=> quic: fix fd_quic_tls_init param name

src/flamenco/runtime/context/fd_exec_instr_ctx.c, src/flamenco/runtime/context/fd_exec_txn_ctx.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/program/fd_bpf_loader_serialization.c, src/flamenco/runtime/program/fd_native_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
1. removing bad stack allocation for instr infos (would've led to bad memory accesses in process sibling syscall)
2. fixing bug in CPI that doesn't error out for unknown accounts
=> flamenco: allocating all instr infos from txn_ctx

contrib/test/instr-fixtures.list, src/flamenco/types/fd_types_custom.c
In Agave's custom tower sync decoding logic, they check if the lockout offsets do not overflow
=> flamenco: new tower_sync decode logic to check for overflows

src/app/fdctl/run/tiles/fd_quic.c, src/app/fddev/tiles/fd_benchs.c, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic.h, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_pkt_meta.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/tests/fd_quic_sandbox.c, src/waltz/quic/tests/fd_quic_test_helpers.c, src/waltz/quic/tests/fuzz_quic_wire.c, src/waltz/quic/tests/test_quic_txns.c
Not required for Solana TPU protocol.
No plans to implement the 'repair over QUIC' protocol.
=> quic: remove support for bidirectional streams

src/flamenco/runtime/sysvar/fd_sysvar.c, src/flamenco/runtime/sysvar/fd_sysvar.h, src/flamenco/runtime/sysvar/fd_sysvar_clock.c, src/flamenco/runtime/sysvar/fd_sysvar_epoch_rewards.c, src/flamenco/runtime/sysvar/fd_sysvar_epoch_schedule.c, src/flamenco/runtime/sysvar/fd_sysvar_fees.c, src/flamenco/runtime/sysvar/fd_sysvar_last_restart_slot.c, src/flamenco/runtime/sysvar/fd_sysvar_recent_hashes.c, src/flamenco/runtime/sysvar/fd_sysvar_rent.c, src/flamenco/runtime/sysvar/fd_sysvar_slot_hashes.c, src/flamenco/runtime/sysvar/fd_sysvar_slot_history.c, src/flamenco/runtime/sysvar/fd_sysvar_stake_history.c
The updater used in Agave for updating sysvar account balance retains the initial lamport balance to calculate the new balance.
Closes [#195](https://github.com/firedancer-io/auditor-internal/issues/195)
=> flamenco: use correct lamports value for updating sysvar accounts

src/flamenco/runtime/tests/fd_exec_instr_test.c
New field was added into the txn context which was not getting reset in between execs
=> fuzz, flamenco: reset instr info cnt state

src/flamenco/runtime/context/fd_exec_txn_ctx.c
Reset the instr info cnt in txn ctx setup
=> flamenco: reset instr info cnt for txns

src/flamenco/runtime/fd_runtime.c
At the epoch boundary, we need to first update the feature account and then update the in-memory map, not the other way around.
=> flamenco, runtime: correctly handle features getting activated at epoch boundary

src/flamenco/runtime/fd_runtime.c
This is always set, whereas there are some scenarios when we calculate rewards and the blockstore does not contain a parent block.
=> flamenco, rewards: correctly look up latest block hash

config/machine/linux_clang_haswell.mk
Fixes build failure on main. Some low end Haswell CPUs don't support hardware AES.
=> config: enable -maes for linux_clang_haswell

src/flamenco/snapshot/fd_snapshot.c
We need to clear the epoch bank every time, otherwise the incremental snapshot will try and populate a data structure which is already full.
=> flamenco, runtime: fix loading incremental snapshots

src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_address_lookup_table_program.h
Also properly propagate errors from `fd_execute_txn_prepare_start`
=> flamenco: make ALUT decode errors conformant + prevent OOB memory accesses

src/flamenco/runtime/program/fd_precompiles.c
Missing feature flag check when calling secp256k1 verify
=> flamenco: add missing feature flag check for 0 signatures in secp256k1 verify

src/flamenco/runtime/program/fd_system_program_nonce.c
`limited_deserialize` will perform the deserialization if the instr data is _at least_ n bytes.
=> flamenco: fix limited deserialize adjacent logic in fd_check_transaction_age

src/util/net/fd_pcapng.c, src/util/net/fd_pcapng.h, src/util/net/test_pcapng.c
fd_aio_pcapng was generating captures with invalid timestamps.
Defaults fd_pcapng_fwrite APIs to always use nanosecond precision,
removing the user's ability/responsibility to set tsresol.
=> Fix pcapng timestamp resolution

src/waltz/quic/fd_quic.c, src/waltz/quic/tests/Local.mk, src/waltz/quic/tests/test_quic_bw.c
- Change test_quic_bw to send many small streams to approximate TPU behavior
- Reenable test_quic_bw test in CI
- Fix deadlock where fd_quic_close_conn causes a connection to be leak if the connection is not already scheduled
- Don't handle frames for DEAD connections
- Fix bug where metrics.conn_closed_cnt is double counted
=> quic: fix test_quic_bw

src/app/ledger/main.c, src/app/rpcserver/fd_rpc_service.c, src/app/rpcserver/fd_rpc_service.h, src/app/rpcserver/main.c, src/flamenco/runtime/fd_rocksdb.c
sample commands:
build/native/gcc/bin/fd_ledger --cmd ingest --rocksdb /data/asiegel/firedancer/dump/testnet-281688085/rocksdb --index-max 5000000 --end-slot 281688085 --page-cnt 30 --funk-page-cnt 16 --snapshot /data/asiegel/firedancer/dump/testnet-281688085/snapshot-281688080-6NHAVEju9WSsz7LQ3sLS9Yn2Tk9J7QByHRFEQLvXKqHG.tar.zst --checkpt /data/asiegel/test-bstore.wksp --checkpt-funk /data/asiegel/test-funk.wksp --copy-txn-status 1
build/native/gcc/bin/fd_rpcserver --offline 1 --port 8123 --restore-funk /data/asiegel/test-funk.wksp --restore-blockstore /data/asiegel/test-bstore.wksp
=> Support for offline rpc service

contrib/test/txn-fixtures/program-tests.list, src/flamenco/runtime/fd_account.h
Agave modifies a copy of the variable here, and then increments the actual variable later. We mistakenly perform a double add and incorrectly throw an error
=> flamenco: fix account resize delta double add

src/ballet/http/fd_hcache.c
Check for reservation failure and abort.  Otherwise the ensuing print with a max length of INT_MAX could overrun buffer.
=> hcache: avoid potential buffer overrun

src/ballet/http/fd_http_server.c
We were occasionally not getting websocket frame headers in some of our websocket clients.  Turns out that if it's a PINGing client, then every time we check for the need to send a PONG, there's a chance that the server would prematurely start sending websocket payload without a corresponding websocket header.
=> http: fix missing websocket header

contrib/test/txn-fixtures/program-tests.list, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c
Agave implements several checks for program accounts that we were missing
=> flamenco: implement load_transaction_accounts runtime checks

src/app/fddev/tests/test_fddev.c
This was causing some flakiness as we increased the `hashes_per_tick` in the default TOML recently.
=> integration-test: disable poh speed test

src/waltz/quic/fd_quic.c, src/waltz/quic/templ/fd_quic_transport_params.c, src/waltz/quic/templ/fd_quic_transport_params.h, src/waltz/quic/templ/test_quic_transport_params.c
- **quic: remove redundant variable for zero-length transport params**
- **quic: ensure unknown transport params are accepted**
=> Improve fd_quic_transport_params test coverage

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic.h, src/waltz/quic/fd_quic_conn.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_pkt_meta.c, src/waltz/quic/fd_quic_private.h, src/waltz/quic/fd_quic_stream.c, src/waltz/quic/fd_quic_stream.h, src/waltz/quic/tests/fd_quic_sandbox.c, src/waltz/quic/tests/fuzz_quic_wire.c, src/waltz/quic/tls/fd_quic_tls.c
Removes identifiers, parameters, and functions that are not used.
=> quic: remove dead code

src/waltz/quic/tls/fd_quic_tls.h
Reduces the size of fd_quic_tls_hs_t from 17.7kB to 3.4kB.
This allows an approx ~5x greater max concurrent handshake setting
with the same amount of memory.
The new TLS buffer size is now 2048 bytes. This is plenty even for
large QUIC transport parameters.
=> quic: reduce fd_quic_tls_hs buffer size

contrib/test/syscall-fixtures/cpi.list, src/flamenco/runtime/program/fd_native_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Agave performs this check in `InvokeContext::prepare_instruction`
NOTE: this needs to be log collected, without which we cannot generate a (passing) fixture
=> flamenco, vm: check if callee program exists

contrib/test/instr-fixtures/bpf-loader-v3.list, src/flamenco/runtime/program/fd_bpf_loader_program.c
Bpf loader was not correctly limited the input data size to 1232 bytes
=> bpf loader v3 limited deserialize

contrib/test/txn-fixtures/program-tests.list, src/flamenco/runtime/tests/fd_exec_instr_test.c
Load default sysvars in txn harness similar to how bank does it in Agave.
=> fuzz, flamenco: load default sysvars properly in FD harness

src/flamenco/runtime/context/fd_exec_txn_ctx.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/tests/fd_exec_instr_test.c
Rent epochs for unknown accounts should be set at the txn level
=> flamenco: Rent epoch logic optimizations

src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/tests/fd_exec_sol_compat.c
Rent epoch setting logic is now conformant with Agave's logic, with hyperlinks included.
=> flamenco: make rent epoch logic conformant with Agave

src/app/fdctl/run/tiles/fd_pack.c
Assuming `now` is in `[LONG_MIN, LONG_MAX]` but never wraps around, then `x = (ulong)now+TIME_OFFSET` is in `[0, ULONG_MAX]`. We want to compute `x-transaction_lifetime_ticks`, but saturating at 0 instead of underflowing.  The right way to do that is `max(x, transaction_lifetime_ticks) - transaction_lifetime_ticks`, which is in `[0, ULONG_MAX-transaction_lifetime_ticks]`.
=> pack: fix typo that prevented transactions from ever expiring

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/templ/fd_quic_parse_frame.h, src/waltz/quic/templ/fd_quic_union.h, src/waltz/quic/tests/fd_quic_sandbox.c, src/waltz/quic/tests/test_quic_layout.c, verification/proofs/quic/handle_v1_one_rtt/fd_quic_handle_v1_one_rtt_harness.c
frame_union was only 56 bytes large.  Remove it and use stack
memory instead.
=> quic: remove frame_union

src/app/fddev/configure/genesis.c, src/flamenco/features/fd_features_generated.c, src/flamenco/features/feature_map.json, src/flamenco/runtime/tests/fd_exec_sol_compat.c, src/flamenco/runtime/tests/fd_vm_test.c, src/flamenco/vm/fd_vm.c, src/flamenco/vm/instr_test/jump.instr, src/flamenco/vm/syscall/test_vm_syscall_curve.c, src/flamenco/vm/syscall/test_vm_syscalls.c, src/flamenco/vm/test_vm_instr.c, src/flamenco/vm/test_vm_interp.c, src/flamenco/vm/test_vm_util.c, src/flamenco/vm/test_vm_util.h
The feature reject_callx_r10 is enabled on all clusters and thus should be hardcoded
Depends on https://github.com/anza-xyz/agave/pull/2414
=> Hardcode reject_callx_r10 feature

contrib/test/vm_interp-fixtures.list, src/flamenco/vm/fd_vm_interp_core.c
Due to the way Agave performs instruction metering, the FD interpreter is always off by 1 (that is, it deducts 1 CU too little) when faulting. To fix this, the PR makes the following adjustments to the interpreter.
1. Add +1 to the ic accumulator in `FD_VM_INTERP_FAULT`
2. Refactor `FD_SBPF_OP_EXIT` (0x95) normal exit path (`sigexit`):
a. Skip  ic accumulation on normal exit . `FD_SBPF_OP_EXIT` is a branching instruction, so the ic is current on `sigexit`
b. Skip pc increment, Agave does not perform this.
=> flamenco, vm: (precise faulting) fix off-by-1 error when deducting CUs on faults to match Agave

book/guide/tuning.md, src/app/fdctl/config.c, src/app/fdctl/config.h, src/app/fdctl/config/bench-icelake-80core.toml, src/app/fdctl/config/bench-zen3-32core.toml, src/app/fdctl/config/default.toml, src/app/fdctl/config_parse.c, src/app/fdctl/run/tiles/fd_store.c, src/app/fdctl/run/topos/fd_frankendancer.c, src/disco/topo/fd_topo.h
Note that there are no shreds for slot 0, so setting `disable_blockstore_from_slot = 1` has exactly the same effect as `disable_blockstore = true`.
=> store: disable blockstore starting from a certain slot

contrib/test/txn-fixtures/program-tests.list, src/flamenco/runtime/tests/fd_exec_instr_test.c
Slot hashes size was 0 by default
=> fuzz: fix default slot hashes size

src/flamenco/runtime/program/fd_bpf_loader_program.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_vm_test.c, src/flamenco/vm/fd_vm.h, src/flamenco/vm/fd_vm_interp.c, src/flamenco/vm/fd_vm_interp_core.c, src/flamenco/vm/fd_vm_private.h, src/flamenco/vm/syscall/fd_vm_cpi.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c, src/flamenco/vm/syscall/fd_vm_syscall_pda.c, src/flamenco/vm/syscall/fd_vm_syscall_runtime.c, src/flamenco/vm/syscall/fd_vm_syscall_util.c
Correctly set `check_align` in the vm based on if the deprecated loader is used.
Also correctly sets alignment values for all the memory address translations in the vm.
=> flamenco, vm: correctly set check_align in vm

src/waltz/quic/fd_quic.c
quic tile was spending far too much time servicing idle connections. This was due to service_interval in config not being set, and defaulting to the minimum, which is far too low.
This change replaces the minimum with a more reasonable value
=> quic - set min timeout per connection to 1s

src/app/fdctl/run/tiles/fd_quic.c, src/disco/quic/fd_tpu_reasm.c, src/disco/quic/fd_tpu_reasm_private.h
Fixes a assertion failure when closing a conn with streams that
got overrun.
Adds more logging to assertion failures and hardens the
fd_tpu_reasm_cancel function.
=> Fix UAF in fd_quic tile

src/waltz/ip/fd_ip.c
Allows us to work around some arp issues
=> arp - accept NUD_PERMANENT entries

src/waltz/quic/tests/fuzz_quic_wire.c
fd_quic_decode_one_rtt(one_rtt) requires one_rtt->dst_conn_id_len
to be initialized.  The fuzzer fails to do this.  Production code
in fd_quic.c already uses fd_quic_decode_one_rtt correctly.
Thanks to ImmuneFi User gln for reporting this bug.
=> quic: fix uninitialized read in fuzz_quic_wire

src/flamenco/runtime/sysvar/fd_sysvar_clock.c
fd_calculate_stake_weighted_timestamp never sets treap prio when
inserting items.  prio was filled from uninitialized stack memory,
which has sub-ideal probabilistic properties.
=> Fix treap usage in fd_calculate_stake_weighted_timestamp

src/flamenco/snapshot/fd_snapshot_http.c, src/flamenco/snapshot/fd_snapshot_loader.c
fd_snapshot_loader_new doesn't zero initialize, but
fd_snapshot_loader_delete unconditionally calls fd_snapshot_http_delete,
which is U.B. in some cases.
Adds zero initialization and moves fd_snapshot_loader_t->http to
the class dynamic region for performance.
=> Fix fd_snapshot_loader_delete uninitialized read

src/choreo/tower/fd_tower.c, src/choreo/voter/test_voter.c, src/disco/consensus/test_gossip_echo_vote.c, src/flamenco/runtime/program/fd_vote_program.c, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json
Switch to flat representation for (compact_)vote_state_update->timestamp
Fixes https://github.com/firedancer-io/auditor-internal/issues/180
=> Fix stack memory UAF in fd_tower_to_tower_sync

src/flamenco/capture/fd_solcap_yaml.c
`meta.solana_txn_err` is of type `uint64_t`
=> solcap: fix format string specifier

src/flamenco/runtime/fd_account.c, src/flamenco/runtime/fd_runtime.c
BorrowedAccount::touch() is a no-op in recent Agave versions. Update Firedancer code to be less confusing about the behavior of touch by updating comments and removing redundant statements.
=> runtime: remove "touch" verbiage

src/flamenco/runtime/fd_runtime.c
Transactions that failed in the sanitization phase would allocate and set up borrowed account metadata, but that metadata was not getting freed. Closes https://github.com/firedancer-io/auditor-internal/issues/222
=> flamenco: fix memory leak when cleaning up transactions that failed sanitization

src/ballet/sbpf/fd_sbpf_loader.c, src/flamenco/features/fd_features_generated.c, src/flamenco/features/feature_map.json
Feature gate cleaned up here: https://github.com/anza-xyz/agave/pull/3000
Also noticed we were checking for syscall <> bpf function collisions on the wrong key (raw target pc instead of pc_hash) in 32b relocations and missing the check entirely in `fd_sbpf_hash_calls`
=> ballet, elf: cleanup `err_on_syscall_bpf_func_collision` feature gate + collision checks

src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_config_program.h, src/flamenco/runtime/tests/run_ledger_tests_all.txt, src/flamenco/runtime/tests/test_exec_instr.c, src/flamenco/runtime/tests/test_exec_sol_compat.c
1. mocking executable flag for non-writable, non-instruction accounts
2. fixing double counting owners size bug
3. collecting rent from writable accounts
=> flamenco: various transaction loading fixes

src/flamenco/vm/fd_vm_base.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Realized there were existing mappings for these error codes. We don't need new ones
=> flamenco: CPI use syscall error codes in preflight checks and check instr

src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Lamport checks are performed at the instruction level thanks to this PR: https://github.com/firedancer-io/firedancer/pull/2934
We don't need them at the CPI level anymore
=> flamenco: remove lamport checks in CPI

src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
With `__wrap_fd_execute`, we can simulate the execution of a CPI by modifying account states with a provided `InstrEffects` message. 
Separate PR for dumping of account states in replay: https://github.com/firedancer-io/firedancer/pull/2931
~~## 2. Dumping account state in CPI calls~~
~~To generate seed corpus with execution effects, the CPI dump tool was modified to capture post-CPI instruction account data.~~
~~Also added a script that temporarily applies a patch file that dumps CPI state during CPI syscall.~~
=> flamenco, fuzz: CPI execution mocking

src/flamenco/vm/fd_vm_private.h, src/flamenco/vm/syscall/fd_vm_syscall_curve.c
- order of invalid length vs access violation
- order of exec vs mem mapping in syscall curve family
- msm special case with points_len==0
=> syscalls: fix fuzz issues

contrib/test/vm_interp-fixtures.list, src/flamenco/vm/fd_vm_interp_core.c
CU errors were being overwritten in the vm fault handler, causing a discrepancy in the error types propagated.
=> vm: fix propagation of cu errors in vm

src/flamenco/runtime/fd_runtime.c
Some records in Funk do not correspond to real accounts. We should not try and collect rent from these.
=> flamenco, runtime: don't try and collect rent from non-fd_account_mgr accounts

src/flamenco/runtime/tests/fd_exec_instr_test.c
When `num_required_signatures==128` the inserted value in the raw metadata conflicts with the V0 message tag, causing false mismatches between FD and Agave
=> fuzz: cap signature count in transaction fuzzing runs

src/app/fdctl/config/default.toml, src/waltz/quic/fd_quic.c, src/waltz/quic/tests/Local.mk, src/waltz/quic/tests/test_quic_idle_conns.c
Also adds a test which simply keeps a specified number of connections open and idle.
=> Fix stream handling to ensure all connections always have at least a minimum number of streams

src/choreo/tower/Local.mk, src/choreo/tower/test_tower.c
Adds a unit test for tower. This test fills a tower with votes for sequential slots, and then checks the case for a vote which pops expired votes and the case where a new root is published.
=> test_tower unit test

src/app/fddev/tiles/fd_benchs.c, src/app/fddev/txn.c, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic.h, src/waltz/quic/fd_quic_enum.h, src/waltz/quic/tests/arp/test_quic_arp_client.c, src/waltz/quic/tests/arp/test_quic_arp_server.c, src/waltz/quic/tests/fd_quic_stream_spam.c, src/waltz/quic/tests/fd_quic_stream_spam.h, src/waltz/quic/tests/test_quic_bw.c, src/waltz/quic/tests/test_quic_client_flood.c, src/waltz/quic/tests/test_quic_conn.c, src/waltz/quic/tests/test_quic_drops.c, src/waltz/quic/tests/test_quic_hs.c, src/waltz/quic/tests/test_quic_key_phase.c, src/waltz/quic/tests/test_quic_retry_integration.c, src/waltz/quic/tests/test_quic_streams.c, src/waltz/quic/tests/test_quic_txns.c
fd_quic_stream_send previously accepted a gather list of chunks.
All those chunks are then sent over the same stream.
This commit simplifies the API to instead only take one chunk.
A bug is fixed in fddev/txn.c that incorrectly sends multiple txns
over the same stream.
Otherwise, all other callers only sent one chunk per call anyways.
=> quic: remove fd_quic_stream_send gather list

.github/workflows/tests.yml
There is little value in testing noarch64 on two GCC versions.
GCC 12 has plenty of coverage on other targets.
=> ci: only test noarch64 on GCC 8.5

src/waltz/quic/fd_quic_conn.c
The bad line makes every connection allocate enough memory for a stream_map containing every stream in the pool plus some overhead per stream. This is unnecessary since only a tiny fraction of the streams are allowed in each connection stream_map.
=> quic - removed incorrect line setting stream_cnt to stream_pool_cnt

src/app/fdctl/config/default.toml
`max_concurrent_handshakes` is no longer bound to the value of `max_concurrent_connections`. So this PR fixes the description and sets the value to a conservative number.
=> quic - changed defaults.toml max_concurrent_handshakes description and value

src/ballet/bn254/fd_bn254.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json, src/flamenco/vm/fd_vm.h, src/flamenco/vm/fd_vm_private.h, src/flamenco/vm/test_vm_base.c
All vm memory regions need to be 8-byte aligned. This has consensus implications - Agave's vm checks that host physical addresses are aligned during address translation. If the host address is unaligned than address translation will fail. We need to match this behaviour.
Direct mapping means that we have to ensure that the account data region of borrowed accounts are therefore 8-byte aligned.
=> flamenco, runtime: align all vm regions to 16-bytes

src/flamenco/log_collector/fd_log_collector.h
Before this change, the compiler would not detect format string bugs like this example. (Not in the live codebase, introduced locally for demonstration)
```c
/* Max msg_sz: 22 - 4 + 44 + 10 = 72 < 127 => we can use printf */
fd_log_collector_printf_dangerous_max_127( ctx, "Program %s invoke [%s]", ctx->program_id_base58, ctx->depth+1 );
```
This is because the compiler does not know that it should check format strings on the `fd_log_collector_printf_dangerous_max_127` function.
As such, the compile succeeds (`MACHINE=linux_clang_haswell EXTRAS="no-agave" make -j`).
This change adds the [format attribute](https://gcc.gnu.org/onlinedocs/gcc-3.2/gcc/Function-Attributes.html) to the `fd_log_collector_printf_<...>` functions.
After the change, compilation will spot the example bug.
``` …
```
=> Add format attributes to fd_log_collector_printf_<...> functions

src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_vm_test.c, src/flamenco/runtime/tests/fd_vm_test.h
This makes the fuzz harness match the memory layout of Firedancer, so we can more accurately detect memory bugs.
=> flamenco, fuzz: align vm input regions in test harness

src/ballet/bn254/fd_bn254.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_vm_test.c, src/flamenco/runtime/tests/fd_vm_test.h, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json, src/flamenco/vm/fd_vm.h, src/flamenco/vm/fd_vm_private.h, src/flamenco/vm/test_vm_base.c
=> syscalls: fix more fuzz mismatches

src/flamenco/log_collector/fd_log_collector.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c
As we start digging into CPI mismatches I figured we'd extend `fd_log_collector_msg_many` to take it a variable number of arguments. Works fine on existing invocations, and also tested locally on a call with >2 msgs (to be pushed in a separate PR).
=> flamenco, log: use variadics in fd_log_collector_msg_many

src/disco/gui/fd_gui.c, src/disco/gui/fd_gui.h, src/disco/gui/fd_gui_printf.c
We are seeing slots starting off in an optimistically confirmed state in the GUI, rather than the completed state that a slot should usually start from.  This is because of a bug relating to the timing of replay completion relative to optimistic confirmation and the handling of slot states in the GUI when those two events happen out of order, i.e. when a higher slot is optimistically confirmed before replay completes for a lower slot.  This PR fixes that.
=> gui: fix slot completed updates

src/ballet/sbpf/fd_sbpf_loader.c, src/ballet/sbpf/fd_sbpf_loader.h, src/flamenco/runtime/program/fd_bpf_loader_program.c, src/flamenco/runtime/program/fd_bpf_program_util.c, src/flamenco/runtime/program/fd_bpf_program_util.h
Previously we copied the _joined_ calldests map from the loaded program into the validated program object. This did not include the private dynamic set header, so many operations on the copied set were UB.
Instead, we keep around a reference to the underlying memory for the calldests map, which we can then safely copy into the validated program.
=> flamenco, runtime: fix copying calldests into program cache

src/flamenco/runtime/tests/fd_exec_sol_compat.c
Log level should be specified in `fd_sol_compat_init()` to enable logging during debugging via conformance
=> fuzz: specify log level in `fd_sol_compat_init()` for debugging / fuzzing

src/flamenco/vm/fd_vm_interp_core.c
The `pc>=text_cnt` check happens in `FD_VM_INTERP_INSTR_EXEC`, _after_ `fd_vm_trace_event_exe` is called. This leads to an OOB in the tracing code. Moving the call to create the trace event after the check guarantees that pc is always valid.
=> flamenco, vm: fix OOB in tracing code

src/flamenco/runtime/program/fd_vote_program.c
We implemented this feature correctly for 4/6 vote instructions.
Side note: we should look into why the fuzzer didn't catch this
=> flamenco, runtime, vote: disable compact vote state updates when deprecate_legacy_vote_ixs and enable_tower_sync_ix are enabled

src/flamenco/runtime/sysvar/fd_sysvar_slot_hashes.c
Slot hashes does not have a consistent sysvar cache update policy, which is causing some seg-faults in CI.
We need to document and specify well-defined cache update behaviours, which I will do in a follow-up PR.
=> flamenco, runtime: don't read slot hashes from sysvar cache

.github/workflows/clusterfuzz.yml
This should fix the CI build for the "Clusterfuzz" fuzzers
=> `ci`: set BUILDDIR such that clusterfuzz.yml fuzzer binaries end up in `clang-fuzz/`

src/waltz/quic/fd_quic.c, src/waltz/quic/templ/fd_quic_parse_util.h, src/waltz/quic/templ/fd_quic_templ.h, src/waltz/quic/tests/fuzz_quic_wire.c, src/waltz/quic/tests/test_quic_layout.c
`common_hdr` had wrong documentation that said it could be used for short packets. The existing prod code did that but did not read any of the non-matching fields. `fuzz_quic_wire` had a minor bug because of it. After consulting with @ripatel-fd this PR removes `common_hdr` in favor of bit fiddling functions. Furthermore, it renames src/waltz/quic/templ/fd_quic_templ.h -> src/waltz/quic/templ/fd_quic_pkt_templ.h as per the TODO comment in the old src/waltz/quic/templ/fd_quic_templ.h
=> quic: remove common_hdr

src/util/net/fd_pcapng.c, src/util/net/fd_pcapng.h, src/util/net/test_pcapng.c
- Return a mutable pointer in fd_pcapng_iter_next to allow for in-place packet mangling
- Fixes bug in parser where link_type is always zero
=> fd_pcapng usability fixes

src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_system_program.c, src/funk/fd_funk_rec.c, src/util/net/fd_pcap.c
These are instances where a parenthesis of an FD_LIKELY/FD_UNLIKELY was closed to early
=> fix bugs in conditions

src/app/fdctl/caps.c, src/ballet/http/fd_http_server.h, src/ballet/http/test_http_server.c, src/disco/topo/fd_pod_format.h
Similar to https://github.com/firedancer-io/firedancer/pull/3131, this PR adds format attributes to functions that take a format string. This enables checking format strings at compile time. The now annotated functions were discovered with a CodeQL query, that discovers such functions. Credits to @marctrem for the query idea. We will run this query periodically to check for regressions / new non-annotated printf like functions.
Adding these attributes uncovered a minor bug in test code, also fixed in this PR.
=> add format attributs to printf like functions

src/waltz/quic/fd_quic.c
Most fd_quic users run a main loop like so:
```
for(;;) {
fd_quic_service( ... );
fd_quic_process_packet( ... );
}
```
fd_quic_service's execution time is currently unbounded which can
starve RX from cycles at high concurrent connection counts.
Improves performance for all connection counts (from 1 to ~40k)
=> quic: only service one conn in fd_quic_service

src/app/fddev/Local.mk, src/app/rpcserver/fd_block_to_json.c, src/disco/stem/fd_stem.c
- Guard zstd dependency in fd_block_to_json
- Only compile fd_stem when SSE is enabled
- Only compile fddev when SSE is enabled
=> Fix noarch128 build

src/ballet/pack/fd_compute_budget_program.h
[Extra instruction data is allowed (see the raw display for the first compute budget program instruction)](https://explorer.solana.com/tx/LmYGjnLLGoaCboZgqSTMRWscoh9F3hjPKCSvFeooPEMuYsx5vWAnj7iEtvi84pxbNt46f2RVRBk8XQ48P2fFnM4), and if a transaction requests more than 1.4M CUs, it's [silently capped at 1.4M, not rejected](https://explorer.solana.com/tx/cwrG3dQxR4ZfowNbLJgtGK53SuMaHh8YFpDHPQhZvguEPnuHVb4DtY7Q8nxEAzhKs8RGqtcyddXfYREvLsZ8tUa).
=> pack: fix a few places our parsing was too strict

src/waltz/quic/fd_quic.c
The length is already checked during parsing: FD_TEMPL_MBR_ELEM_VAR in fd_quic_decode_{initial,handshake}
This is not a security fix, but a minor performance improvement.
I additionally checked that the fuzzer is never hit the error case.
=> quic: remove unnecessary conn_id length checks

src/app/fdctl/run/tiles/fd_quic.c, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_pkt_meta.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/tests/fd_quic_sandbox.c, src/waltz/quic/tests/fuzz_quic_wire.c
- Remove dead FD_QUIC_OPT defines
- Remove support for multiple SCIDs
- Reduce fd_quic tile conn ID cnt from 16 to 4
- Remove conn->version field (we only support and test v1)
- Remove unused FD_QUIC_PKT_META_STATUS enum
- Remove unused FD_QUIC_TYPE_{INGRESS,EGRESS} enum
=> quic: remove unused code

src/waltz/quic/Local.mk, src/waltz/quic/crypto/fd_quic_crypto_suites.c, src/waltz/quic/fd_quic_pcap_main.c, src/waltz/quic/templ/Local.mk, src/waltz/quic/templ/fd_quic_union_decl.h
Adds the scaffold of a tool that can analyze a TPU/QUIC packet
capture.  So far implements:
- pcap reader
- pcapng reader
- Ethernet support
- QUIC initial parser
- TLS key log file parser
- Machinery to associate DCIDs with encryption keys
Also removes some unused fd_quic files
=> quic: add fd_quic_pcap tool scaffold

src/app/fdctl/config/default.toml
The current fd_quic TPU server code allocates no pkt_meta after
completing a handshake.  Therefore, the max_inflight_quic_packets
setting can be decreased.  Adjusts documentation accordingly.
=> quic: decrease default max_inflight_quic_packets fdctl option to 64

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_conn_id.h
Decreases the fd_quic_conn_t footprint by about 600 bytes.
Removes support for the NEW_CONNECTION_ID frame.  fd_quic only ever
uses the first available connection ID anyways, and doesn't
implement RETIRE_CONNECTION_ID.  The conn ID state is thus dead
weight.
=> quic: only support one DCID

config/machine/linux_gcc_power9.mk, src/app/backtest/Local.mk, src/app/rpcserver/Local.mk, src/choreo/eqvoc/Local.mk, src/flamenco/runtime/program/zksdk/Local.mk, src/flamenco/types/Local.mk, src/funk/Local.mk, src/funk/fd_funk_filemap.c, src/util/fd_util_base.h, src/waltz/quic/Local.mk
Adds an experimental target to ensure the code base stays portable
=> Add Power9 build target

src/util/tmpl/fd_map_giant.c
Removes a leftover debugging instruction
=> Fix stray int3 in fd_map_giant.c

src/waltz/quic/crypto/fd_quic_crypto_suites.c, src/waltz/quic/fd_quic.c, src/waltz/quic/templ/fd_quic_encoders.h, src/waltz/quic/templ/fd_quic_encoders_footprint.h, src/waltz/quic/templ/fd_quic_parse_util.h, src/waltz/quic/templ/fd_quic_transport_params.c, src/waltz/quic/templ/fd_quic_transport_params.h, src/waltz/quic/templ/test_quic_transport_params.c, src/waltz/quic/tests/test_quic_ack_tx.c, src/waltz/quic/tests/test_quic_proto.c
Incorporates bits from #3277 
**quic: simplify fd_quic_conn_tx header encoding**
The QUIC protocol uses a variable-size encoding for the 'length'
field in the packet header.  Because of this, fd_quic_conn_tx
serialized packet content before the packet header.  This required
some messy logic to estimate the worst-case header size to leave
enough space.
QUIC varints also have multiple valid encodings, which we can use
to our advantage.  The number '2' can be encoded as 0x02, 0x4002,
or 0x80000002.
This commit patches fd_quic_conn_tx to serialize the header first,
with a dummy length using a two byte encoding.  After serializing
frames, we can then update the length field in-place without
changing the size of the header.
Removes some associated complexity like enum wrapper function …
=> quic: optimize varint encoder

src/util/sandbox/fd_sandbox.c
Not a security issue, but fails build on some Clang versions
=> Fix integer conversion in fd_sandbox.c

contrib/test/test-vectors-fixtures/cpi-fixtures/cpi.list, src/flamenco/runtime/context/fd_exec_txn_ctx.c, src/flamenco/runtime/context/fd_exec_txn_ctx.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c
Error code mismatch on a CPI fixture.  FD errors out as missing account, and agave errors out as account not executable.  This is due to a mismatch in account borrowing behavior.  FD does extra dead account check that agave doesn't.  This commit fixes that.
=> flamenco: allow dead accounts to be borrowed

contrib/test/test-vectors-fixtures/cpi-fixtures/cpi.list, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Error code mismatch on a CPI fixture because FD does instruction translation after preflight checks, whereas agave does it before anything else in cpi_common.
=> flamenco: instruction translation should happen before preflight checks

src/app/fdctl/run/tiles/fd_net.c, src/disco/topo/fd_topo_run.c, src/waltz/xdp/fd_xdp1.c, src/waltz/xdp/fd_xdp1.h
Reverts firedancer-io/firedancer#3349
3349 does not correctly implement routing for return packets which leads to QUIC connection failures.
=> Revert "xdp: update bpf maps with multihome ips"

src/app/fdctl/run/tiles/fd_quic.c
The removed checks are already implied by checks at the start of the function. There was no bug.
=> quic: remove duplicate tile count checks

src/waltz/quic/fd_quic.c, src/waltz/quic/templ/fd_quic_frame.c
=> quic: fix FD_QUIC_FRAME_TYPES off-by-one

src/flamenco/runtime/tests/fd_exec_instr_test.c
txn ctx is scratch allocated, which caused a flood of warnings when trying to free it from the wksp in txn context destroy
=> fuzz, ci: remove txn log flood

src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Now the preflight checks are gone, we need to use a saturating multiply here.
=> flamenco, vm: check for overflow in total acount infos size

contrib/tango.lua, src/app/fdctl/run/tiles/fd_quic.c, src/app/fdctl/run/tiles/fd_sign.c, src/app/fdctl/run/topos/fd_firedancer.c, src/app/fdctl/run/topos/fd_frankendancer.c, src/disco/keyguard/fd_keyguard.h, src/disco/keyguard/fd_keyguard_authorize.c
Agave TPU clients ignore the server's TLS public key.
Thus, we can generate a random throwaway key on startup instead of
reusing the identity key.  This improves our security architecture
and removes a potential performance bottleneck with the keyguard tile.
=> quic: use random TLS public key

src/flamenco/fd_flamenco_base.h
Move part of the FD_BASE58_ENC_{32,64}_ALLOCA macro to an inline
function to suppress a null compare warning introduced in GCC 14.
=> Fix GCC 14 support

src/app/fdctl/run/tiles/fd_replay.c, src/app/ledger/main.c, src/ballet/txn/fd_txn.h, src/flamenco/runtime/context/fd_exec_txn_ctx.h, src/flamenco/runtime/fd_acc_mgr.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_exec_instr_test.h, src/flamenco/runtime/tests/fd_exec_sol_compat.c, src/flamenco/runtime/tests/test_exec_instr.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
- Include space for spad allocator metadata block, i.e. fd_spad_t
- Include alignment padding on each individual borrowed account
=> flamenco: size out worst case space for spad-backed borrowed accounts

src/flamenco/snapshot/fd_snapshot_http.c
Names can be NULL, while counting towards num_headers
https://github.com/firedancer-io/firedancer/blob/54f665991b4c4bfb178c5f8cf7dcdc76feee8068/src/ballet/http/picohttpparser.c#L333-L334
=> snapshot: fix NULL cmp in http header parsing

src/waltz/quic/fd_quic.c
This fixes an issue whereby the client initiates a key phase change, but it doesn't complete properly, and we lose the connection.
Also, it removes a line that broke the build.
=> quic - fix key phase change

src/app/fdctl/run/tiles/fd_verify.c, src/disco/quic/fd_tpu.h, src/disco/quic/fd_tpu_reasm.c, src/disco/quic/fd_tpu_reasm_private.h, src/disco/quic/test_tpu_reasm.c
Consumers of fd_tpu_reasm frags were using an incorrect range for bounds checking data chunks.  The range was set too low.
Thank you to @ptaffet-jump for finding this bug.
=> quic: fix fd_tpu_reasm bounds check

src/flamenco/snapshot/fd_snapshot_http.c
#3395 manifested a latent bug in the original strcmp which included the colon which isn't actually parsed out into header.name
=> fix(http): header name comparison

contrib/test/test-vectors-fixtures/syscall-fixtures/try_find_program_address.list, src/flamenco/vm/fd_vm_private.h, src/flamenco/vm/syscall/fd_vm_syscall_pda.c
keven approved of restructuring of the vm accessor
=> syscall_pda_cus: cus were not correctly updated in the case of an error

src/waltz/quic/templ/fd_quic_parse_util.h, src/waltz/quic/tests/test_quic_proto.c
If a value beyond 2^62-1 was supplied to fd_quic_varint_encode, it would assume the 62 low order bits contained the value.
This fix defensively limits the value to at most 2^62-1, thereby avoiding truncation.
=> quic - ensure varint encoding handles overflow properly

src/app/ledger/main.c
Sometimes we get a ledger where the first few slots are skipped slots.  We should seek to the first rooted slot rather than erroring out when the first slot isn't rooted.
=> ledger: update rocksdb slot seek logic

src/app/fdctl/configure/configure.h, src/app/fdctl/configure/ethtool-channels.c, src/app/fdctl/configure/ethtool-gro.c, src/app/fdctl/configure/hugetlbfs.c, src/app/fdctl/configure/sysctl.c, src/app/fdctl/main.c, src/app/fdctl/run/run.c, src/app/fddev/configure/blockstore.c, src/app/fddev/configure/genesis.c, src/app/fddev/configure/keys.c, src/app/fddev/configure/kill.c, src/app/fddev/configure/netns.c, src/app/fddev/main1.c
Fixes a symbol collision reported by the mold linker
mold: warning: symbol type mismatch: sysctl
>>> defined in build/native/gcc/lib/libfd_fdctl.a(sysctl.o) as STT_OBJECT
>>> defined in /lib64/libc.so.6 as STT_FUNC
=> fdctl: fix symbol collision with configure stages

src/waltz/quic/templ/fd_quic_templ.h
This structure is unused and incorrectly defined.
Reported-by: two-heart <seven-master@hotmail.de>
=> quic: remove zero_rtt structure

src/app/fdctl/run/tiles/fd_quic.c, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.h
Add a unique local identifier for QUIC connection objects (conn_uid)
conn_uid can trivially be converted into a conn_idx.
=> quic: add conn UID

.github/workflows/codeql.yml
This works arrounda arround GitHub bug https://github.com/github/codeql-action/issues/1572 and our use case does not require results upload
=> ci: fix codeql action in merge queue

src/flamenco/runtime/fd_acc_mgr.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt
- Rent state transition check should based be on post deposit balance
- Check should be based on post burn fees
- Allow a leader to be created if dead and purged because we see mainnet leaders that have 0 balance, for example: 9e7XGRqQqEvppx4Lkj6P1S7k65yWQpf3vcNzWecKSzDd CYkkaM5KwoxaFtZcximkm1DFYnABdiUUUvJg1WURDRsh
- Make sure capitalization is always properly adjusted on check failure
=> flamenco: fix fee deposit checks

src/flamenco/runtime/sysvar/fd_sysvar_epoch_rewards.c
When distributing partitioned epoch rewards, there are multiple updates to the epoch rewards sysvar within a single slot, which updates the sysvar account but NOT the sysvar cache. When a subsequent update is performed within a single slot, the update ends up happening on a stale cache entry and causing the updated stale value to get written back into the account, causing a mismatching epoch rewards sysvar account. We should make sure to restore the sysvar cache before we perform subsequent updates on a sysvar within a single slot.
=> flamenco: keep sysvar cache in sync with multiple epoch rewards sysvar updates within a slot

src/app/fdctl/config.h, src/app/fdctl/config/default.toml, src/app/fdctl/config_parse.c, src/app/fdctl/run/tiles/fd_quic.c, src/app/fdctl/run/topos/fd_firedancer.c, src/app/fdctl/run/topos/fd_frankendancer.c, src/disco/topo/fd_topo.h
- Remove unused max_inflight_quic_packets config option
(Now hardcoded at 16 packets per connection.  We shouldn't ever
send more than ~8 ACK-eliciting packets over the lifetime of a
connection)
- Better error detection for incorrect config parameters
- Fix oversz scratch_footprint calculation
- Validate scratch_footprint on startup
- Remove redundant fd_quic_ctx_t->depth variable
- Log errno code for getrandom() startup error
- Remove defunct code for multiple input links
- Tighten bounds checks for the input link dcache
(This adds an assumption that the input frag buffer is a dcache,
but this is better than assuming that the input frag buffer is in
a wksp, which is not true in contexts like CBMC.  This reveals a
gap in the fd_topo APIs, which should teach a tile about the frag
buffer …
=> Belt-sand QUIC tile

src/flamenco/runtime/fd_runtime_init.c
Log lthash values using the correct macro so that we don't waste days walking down the wrong bugs
=> lthash_logging_fix: Fix lthash logging

src/app/fddev/tiles/fd_benchs.c, src/app/fddev/txn.c, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic.h, src/waltz/quic/tests/arp/test_quic_arp_client.c, src/waltz/quic/tests/fd_quic_test_helpers.c, src/waltz/quic/tests/fd_quic_test_helpers.h, src/waltz/quic/tests/test_quic_bw.c, src/waltz/quic/tests/test_quic_client_flood.c, src/waltz/quic/tests/test_quic_conformance.c, src/waltz/quic/tests/test_quic_conn.c, src/waltz/quic/tests/test_quic_drops.c, src/waltz/quic/tests/test_quic_hs.c, src/waltz/quic/tests/test_quic_idle_conns.c, src/waltz/quic/tests/test_quic_key_phase.c, src/waltz/quic/tests/test_quic_retry_integration.c, src/waltz/quic/tests/test_quic_streams.c, src/waltz/quic/tests/test_quic_tls_hs.c, src/waltz/quic/tests/test_quic_txns.c, src/waltz/quic/tls/fd_quic_tls.c, src/waltz/quic/tls/fd_quic_tls.h
Also clean up usages of fd_log_wallclock as the fd_quic clock src
=> quic: remove unused sni option

src/waltz/quic/crypto/fd_quic_crypto_suites.c, src/waltz/quic/crypto/fd_quic_crypto_suites.h, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic.h, src/waltz/quic/fd_quic_conn.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_pkt_meta.h, src/waltz/quic/tests/Local.mk, src/waltz/quic/tests/test_quic_key_phase.c
Fixes conn failure if more than 'inflight_pkt_cnt' ACKs are sent during a key update.
Simplifies key update logic overall.
Internals:
- Always keep precomputed updated keys and secrets around
- Don't track key phase information in pkt_meta
- Immediately commit key update secrets once an incoming packet
with a different key phase passes encryption
- Rationale: If packets with an old key phase get reordered past
the packet that updated the key phase, those old packets will
just fail decryption without any side effects
- The RFC and the old code used more complex methods for hardening
key updates against reordering (e.g. using ACKs) but those are
not necessary if key updates are only followed, not initiated
- Simplify key update initiation (only for testing)
- Fix test_quic_key_phase and …
=> quic: rewrite key update logic

.github/workflows/codeql.yml, contrib/codeql/BuiltinExpectScopeTooNarrow.ql, contrib/codeql/NonAnnotatedFormatFunction.ql, contrib/codeql/RedundantNullCheck.ql, contrib/codeql/UnclearOperatorPrecedence.ql, contrib/codeql/filter.qll
analyse big fddev x86 build (instead noarch unit-test), fix included filter, fix query metadata, unify build by using existing workflows, move to on-prem (speeding up the query, despite much bigger compile target, from 10m 20s to 4m 32s)
=> ci: codeql ci improvements

contrib/test/test-vectors-fixtures/txn-fixtures/program-tests.list, src/flamenco/runtime/sysvar/fd_sysvar_instructions.c
we need to do this because the fuzzer can provide incorrect starting balances for the intructions sysvar. What we do now is still correct behavior because this is when the account is setup in both Agave and Firedancer. The account always has default values when data is serialized into it.
=> flamenco: resetting starting balance for instructions sysvar

src/flamenco/runtime/context/fd_exec_slot_ctx.c, src/flamenco/runtime/fd_blockstore.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt
These values are involved in the computation of new derived lamports_per_signature values in sysvar.  We derive incorrect lamports_per_signature if these two are not initialized properly.
Also bump the limit on the number of microblocks per block in the blockstore.  The runtime has no similar limits and can handle blocks with a large number of microblocks just fine.  There's no reason for the blockstore to have such a limit.
=> flamenco: init parent_signature_cnt and lamports_per_signature to non 0

src/app/fdctl/fdctl.h, src/app/fdctl/run/tiles/fd_quic_tile.c, src/app/fdctl/run/tiles/fd_quic_tile.h, src/app/fddev/fddev.h, src/app/fddev/main1.c, src/app/fddev/quic_trace/Local.mk, src/app/fddev/quic_trace/fd_quic_trace.h, src/app/fddev/quic_trace/fd_quic_trace_frame.c, src/app/fddev/quic_trace/fd_quic_trace_main.c, src/app/fddev/quic_trace/fd_quic_trace_rx_tile.c, src/waltz/quic/templ/fd_quic_frame.c, src/waltz/quic/templ/fd_quic_frame.h
Adds a command to trace incoming QUIC STREAM frames to stdout.
Introduces scaffold to allow other processes to join fdctl quic tile
data structures.
- Add fd_quic_tile.h
- Add a magic number to fd_quic_ctx_t
- Rename tiles/fd_quic.c => tiles/fd_quic_tile.c to fix object name
collision with waltz/fd_quic.c.
Closes #3461
=> Add fddev quic-trace command

src/app/fdctl/config.c, src/app/fdctl/run/run.c, src/app/fdctl/run/tiles/fd_quic_tile.c, src/app/fdctl/run/tiles/fd_verify.c, src/app/fdctl/run/topos/fd_firedancer.c, src/app/fdctl/run/topos/fd_frankendancer.c, src/app/fddev/bench.c, src/app/fddev/dump.c, src/disco/quic/fd_tpu.h, src/disco/quic/fd_tpu_reasm.c, src/disco/quic/fd_tpu_reasm_private.h, src/disco/quic/test_tpu_reasm.c, src/disco/topo/fd_topo.c, src/disco/topo/fd_topo.h, src/disco/topo/fd_topob.c, src/disco/topo/fd_topob.h
Simplifies and hardens shared memory access patterns for consumers
of the quic tile.  Frag buffers produced by the quic tile (via
fd_tpu_reasm) are moved to a separate dcache object and the reasm
internal state is moved to tile scratch memory.
Closes #3524
=> tpu: separate out tpu_reasm buffers into dcache

src/flamenco/vm/fd_vm.c, src/flamenco/vm/fd_vm.h, src/flamenco/vm/fd_vm_interp_core.c, src/flamenco/vm/fd_vm_private.h, src/flamenco/vm/instr_test/v2/int_math.instr
[SIMD-0166](https://github.com/solana-foundation/solana-improvement-documents/blob/c5fba114ae4081ad39080f3c6bb62ee7e4dea9f3/proposals/0166-dynamic-stack-frames.md): SBPF Dynamic stack frames
Implementation details:
- Enabling dynamic stack frames automagically disables gaps. This should be coherent with the work done for direct mapping.
- Minor cleanup of the register checks, including R11. Agave has a specific error for R10 that we don't have, but since all errors are mismatched I don't think we really need to add one.
- Stack alignment set to 64, I made comments in SIMD-0166 about that. If we decide to reduce it, we just need to change it in the macro.
=> SIMD-0166: SBPF dynamic stack frames

contrib/test/test-vectors-fixtures/syscall-fixtures/memmove.list, src/flamenco/vm/fd_vm_private.h, src/flamenco/vm/syscall/fd_vm_syscall_util.c
had oob case for direct mapping, non input region, overlapping memmove
=> flamenco: patch for oob memmove

src/flamenco/runtime/fd_rocksdb.c
band-aid fix to get ledger tests running in CI again. will put up a better fix this weekend.
=> flamenco, replay: don't set smr to be the latest slot on ledger replay

.github/workflows/coverage_report.yml, .github/workflows/coverage_report_clusterfuzz.yml
The coverage report job sometimes takes slightly longer than 30 mins which is the current limit.
=> ci: increase coverage report timeout to 60 mins

src/app/ledger/main.c, src/flamenco/runtime/fd_rocksdb.c, src/flamenco/runtime/fd_runtime.c
Changing `fd_ledger` to use the same blockstore publishing APIs as the live replay path.
- Use `fd_blockstore_publish` instead of manually calling `fd_blockstore_slot_remove`.
- Use on-demand block ingest all the time in ledger replay.
The first PR in a series of PRs aimed at making the logic inside live and offline more similar.
=> flamenco, ledger: correctly use blockstore APIs

src/ballet/pack/fd_pack_cost.h
With the activation of `migrate_config_program_to_core_bpf`, the config program should no longer be considered a builtin by pack.
=> pack: don't include config program in list of builtins

contrib/test/run_test_vectors.sh
We need to regenerate fixtures.
Will be re-enabled in https://github.com/firedancer-io/firedancer/pull/3627
=> vm: temp disable vm-interp tests

.github/workflows/tests.yml, config/extra/with-fuzz-stubs.mk, config/extra/with-fuzz.mk, contrib/test/ci_tests.sh, contrib/test/run_test_vectors.sh, src/flamenco/runtime/tests/Local.mk
Creates a `fuzz-stubs` extra that builds stubbed fuzz binaries for CPI fuzz harness. This is then used in our CI test workflows. Additional changes to `run_test_vectors.sh` to (optionally) pickup the stubbed binary.
=> flamenco, fuzz: add stubbed binaries to CI for CPI test vectors

src/app/ledger/main.c, src/flamenco/runtime/fd_runtime.c
We use `fd_bpf_scan_and_create_bpf_program_cache_entry_tpool` in live, so we should use it in ledger replay also
=> app, ledger: use fd_bpf_scan_and_create_bpf_program_cache_entry_tpool in ledger replay

src/app/fdctl/run/tiles/fd_replay.c, src/choreo/forks/fd_forks.c, src/flamenco/runtime/context/fd_exec_slot_ctx.h, src/flamenco/runtime/fd_runtime.c
This is updated inconsistently depending on the execution path taken. Looking this up is relatively cheap, so we do that instead.
=> flamenco, runtime: don't store leader pointer in slot context

book/guide/tuning.md, src/ballet/base58/fd_base58_tmpl.c, src/funk/fd_funk_val.h
remove redundant words in comment
=> chore: remove redundant words in comment

contrib/test/test-vectors-fixtures/cpi-fixtures/cpi.list, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
User-provided pubkeys should never span multiple regions, these should ~~be skipped.~~ error out
=> flamenco, vm: skip pubkeys which span multiple regions

src/app/fdctl/run/tiles/fd_rpcserv.c, src/app/fdctl/run/topos/fd_firedancer.c, src/flamenco/runtime/fd_blockstore.c, src/flamenco/runtime/fd_blockstore.h
Also includes some bugfixes like:
- passing blockstore-file to rpcsrv 
- null check for parent chain (originally when user queries for the first block after snapshot, it would fail to find parent and err)
=> refactor(blockstore): API for persisting finalized blocks to archival file

contrib/codeql/AccountDerefBeforeModify.ql
Query idea credits: @ripatel-fd
=> codeql: deref borrowed acc metadata before modifying check

src/disco/rpcserver/fd_rpc_service.c, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types_custom.c, src/flamenco/types/fd_types_custom.h, src/flamenco/types/gen_stubs.py, src/util/tmpl/fd_redblack.c, src/util/tmpl/test_redblack.c, src/util/tmpl/test_redblack2.c
Fixes an issue where fd_redblack produces externally linked symbols
even if the implementation style is set to 'local use only'.
=> Fix fd_redblack symbol visibility

src/app/fdctl/run/tiles/fd_gossip.c
The filter was applied too early, causing the gossip tile to ignore all links except net-gossip
=> tile, gossip: re-position in_idx filter condition in after_frag

src/util/tmpl/Local.mk, src/util/tmpl/fd_map_para.c, src/util/tmpl/fd_pool_para.c, src/util/tmpl/test_map_para.c
By popular demand, this is a generator for composable concurrent persistent shared map implementations.  Much as fd_pool_para was a building block to implement more advanced concurrent data structures like this, this is a building block to support potential funk optimizations.
Because non-trivial concurrent data structures are extremely tricky to implement, test and optimize, this has more detailed documentation and unit testing than usual.  See the code itself for details but from the (already lengthy) summary in fd_map_para:
----
Generate prototypes, inlines and/or implementations for concurrent persistent shared maps based on chaining.  A map can store a practically unbounded number of elements.  If sized on creation for the maximum number of mapped elements, typical map operations are …
=> Concurrent persistent shared map implementation

src/app/fdctl/config.h, src/app/fdctl/config_parse.c, src/app/fdctl/run/tiles/fd_gossip.c, src/app/fdctl/run/tiles/fd_replay.c, src/app/fdctl/run/tiles/fd_store_int.c, src/app/fdctl/run/topos/fd_firedancer.c, src/disco/restart/fd_restart.c, src/disco/restart/fd_restart.h, src/disco/topo/fd_topo.h
This PR fixes the following issues of the initial wen-restart implementation in PR #2923.
1. Add `tower_checkpt` in toml config and checkpoint the latest sent tower into a file
2. Use the latest sent tower for the last_voted_fork_slot message, which is the right thing to do
3. Use a memory-mapped file for funk, so we won't need to checkpoint funk at a special point of time
4. Handle stake weights correctly for 2 epochs instead of just the epoch of the funk root
5. Remove redundant fields from `fd_restart_t` such as the tower root
6. Implement RunLengthEncoding and its decoding for the bitmaps
7. Send all wen-restart messages periodically and refactor the related code a bit
8. Throw an error if the repair from heaviest_fork_slot skips the funk root slot
9. Add some boundary checks to …
=> Address some FIXMEs for wen-restart

src/app/fdctl/run/tiles/fd_replay.c, src/app/ledger/main.c, src/flamenco/runtime/Local.mk, src/flamenco/runtime/fd_blockstore.c, src/flamenco/runtime/fd_blockstore.h, src/flamenco/runtime/test_archive_block.c
test_archive_block tests:
- when blocks written greatly exceed block_idx
- when blocks written greatly exceed file size 
- rereading from an archive file and continuing to update the archive
- rereading from an archive file that has overwritten blocks / wrapped around blocks
=> blockstore: archival file as a circular buffer

src/flamenco/gossip/fd_gossip.c, src/flamenco/types/fd_type_names.c, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json
Adds support for verifying prune messages sent with a sign data prefix. Until all nodes in the cluster support this, this prefix is not used. We are adding support to be ready for when messages are signed using this prefix.
Tested against a local cluster, receiving and verifying prune messages with and without the prefix.
See https://github.com/anza-xyz/agave/pull/1472
=> gossip: add support for prune signed data prefix

src/flamenco/runtime/tests/fd_vm_test.c, src/flamenco/vm/fd_vm.c, src/flamenco/vm/fd_vm_base.h, src/flamenco/vm/fd_vm_interp_core.c, src/flamenco/vm/fd_vm_private.h, src/flamenco/vm/test_vm_interp.c, src/util/bits/fd_sat.h, src/util/bits/test_sat.c
https://github.com/solana-foundation/solana-improvement-documents/pull/178
Added unit tests for static syscalls. I'll add test-vectors when simd-0179 is also completed as many tests depend on both.
=> simd-0178: static syscalls

src/flamenco/runtime/fd_acc_mgr.c
the check is already present in fd_acc_mgr_view_raw. + stylistic fixes arround it
=> flamenco: remove redundant check in fd_acc_mgr_view

src/app/ledger/main.c, src/flamenco/runtime/fd_hashes.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_bpf_program_util.c, src/funk/fd_funk_archive.c, src/funk/fd_funk_rec.c, src/funk/fd_funk_rec.h, src/funk/fd_funk_txn.c, src/funk/test_funk_common.c, src/funk/test_funk_common.h, src/funk/test_funk_common.hpp, src/funk/test_funk_part.c, src/funk/test_funk_rec.c, src/funk/test_funk_val.c
Now funk records when removed will not lose their data and will be published into the root of funk. However, they will contain the erase flag. This will dneote that they will be tombstones. This is needed for snapshotting as well as for debugging
=> funk: leaving tombstones in published records

contrib/test/test-vectors-fixtures/txn-fixtures/program-tests.list, src/flamenco/runtime/context/fd_exec_instr_ctx.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
`fd_instr_borrowed_account_view()` checks for account existence with `fd_acc_exists()`which is not correct. Additionally, a borrowed account's meta will never be null (`fd_executor_setup_borrowed_accounts_for_txn()` will always set up a sentinel value for the metadata)
=> flamenco: fix improper usages of instr borrowed account view

src/util/fd_util_base.h, src/util/tpool/fd_tpool.cxx, src/util/tpool/fd_tpool.h, src/util/tpool/test_tpool.c
As per the discussion in issue #3710, gave the fd_tpool API stronger compiler memory fencing guarantees and updated FD_SPIN_PAUSE documentation to be explicit about its current (lack of) fencing guarantees.
In the process, this fixes a latent bug caused by missing compiler memory fence on targets without FD_HAS_X86.  The missing fence could cause the the compiler to "optimize" the tpool worker task dispatch outer loop into an infinite loop for worker threads in tpools containing 2 or more tiles within the same process on targets without FD_HAS_X86.
With this, in the vast majority of circumstances (e.g. not writing low level concurrency tests/benchmarks), normal code (i.e. single threaded non-conflicting) should "just work" without use of volatile, FD_VOLATILE, FD_COMPILER_MFENCE, …
=> Stronger fd_tpool compiler memory fencing guarantees

src/app/ledger/main.c, src/app/shredcap/main.c
Using a zero-sized map caused undefined behaviour in several places, such as scratch footprint calculation.
This caused the ledger tests not to be able to allocate memory correctly on some machines.
=> app, ledger, shredcap: don't initialize blockstore with a zero idx_max

src/disco/topo/fd_topo.c
otherwise we print uninitialized memory
Before:
=> topo: don't print agave affinity for full client topo

src/app/ledger/main.c, src/ballet/shred/fd_deshredder.c, src/ballet/shred/fd_deshredder.h, src/flamenco/runtime/fd_blockstore.c, src/flamenco/runtime/fd_blockstore.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h, src/flamenco/runtime/tests/run_ledger_tests_all.txt
Agave has this notion of a batch of data shreds.  The presence of one of the COMPLETE flags in a data shred marks the end of a batch. Moreover, bincode deserialization of microblocks is performed on a per-batch basis.  Precisely a single array of microblocks is expected to be deserialized from a batch.  Trailing bytes in each batch are ignored by default.
Block parsers in both the runtime and the blockstore lack the notion of a batch, and consequently do not properly handle blocks with trailing bytes, such as
https://explorer.solana.com/block/308445708
which has 7335 trailing bytes in the last batch.
=> flamenco, blockstore: deserialize per-batch and allow trailing bytes

src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_vm_test.c
Some unit tests were allocating pb_bytes_array_t incorrectly.
=> Fix pb_bytes_array_t alignment

src/app/fdctl/run/tiles/fd_store_int.c, src/flamenco/runtime/fd_blockstore.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h
Re-working the live transaction iterator to support iterating over batches, not just entire blocks. This enables us to correctly support shreds with trailing bytes in the live client, and will be useful for when we move to a streaming architecture.
Also re-wrote the original iterator to be easier to understand and documented.
=> flamenco: add support for entry batches to live replay

src/flamenco/runtime/tests/fd_vm_test.c, src/flamenco/runtime/tests/fd_vm_test.h
Cleans up
- misaligned vm->rodata
- bad function pointer cast
=> flamenco, fuzz: fix ubsan errors on vm interp harness

src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Account info refcells should not be allowed to be stored in accounts in direct mapping. This is a new restriction that was introduced since direct mapping was last activated. See https://github.com/anza-xyz/agave/pull/3471
=> flamenco, vm: check for account info being stored in account

src/app/fdctl/run/tiles/fd_replay.c, src/app/fdctl/run/tiles/fd_store_int.c, src/app/ledger/main.c, src/choreo/forks/fd_forks.c, src/disco/store/fd_store.c, src/flamenco/runtime/fd_blockstore.c, src/flamenco/runtime/fd_blockstore.h, src/flamenco/runtime/fd_rocksdb.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/shredcap/fd_shredcap.c
https://github.com/firedancer-io/firedancer/pull/3734 caused an issue in live, because there was a path where the read lock was never being released. The PR was reverted.
This PR restores the original PR #3734, with a fix to handle the above bug.
Tested locally by running against testnet repeatedly.
=> fix(disco, store): fix and document locking

src/flamenco/runtime/program/fd_bpf_loader_serialization.c, src/flamenco/vm/fd_vm.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
We are missing the `check_account_info_pointer` CPI checks in direct mapping, which check that the vaddrs provided by the user correspond to the correct locations.
=> flamenco, vm: add check_account_info_pointer cpi security checks

book/api/cli.md
This pull request corrects a typographical error in the `cli.md` file, where "configuation" was used instead of the correct spelling "configuration."
- Corrected "configuation" to "configuration" in the `cli.md`.
- `book/api/cli.md`
Fixing typographical errors in documentation improves clarity and reduces potential confusion, especially for users referring to setup or configuration instructions.
- N/A
This is a minor documentation fix that does not affect the functionality of the code.
=> Fix typo Update cli.md

src/app/fdctl/fdctl.h, src/app/fddev/quic_trace/fd_quic_trace.h, src/app/fddev/quic_trace/fd_quic_trace_main.c, src/app/fddev/quic_trace/fd_quic_trace_rx_tile.c, src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_pretty_print.c, src/waltz/quic/fd_quic_pretty_print.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/templ/fd_quic_pretty_print.h, src/waltz/quic/templ/fd_quic_pretty_print_decl.h
Added prety printing --dump option to fddev quic-trace
=> quic - pretty print quic trace

src/flamenco/runtime/fd_executor.c
We were using a different hashing function to Agave for the hash of the message when querying the status cache, which potentially causes false cache misses after loading from a snapshot.
Ran against testnet.
=> flamenco, runtime: add domain prefix to txncache message hashes

src/util/tmpl/Local.mk, src/util/tmpl/fd_map_para.c, src/util/tmpl/fd_map_slot_para.c, src/util/tmpl/fd_pool_para.c, src/util/tmpl/test_map_para.c, src/util/tmpl/test_map_slot_para.c
By popular demand, this is a generator for concurrent persistent shared maps based on linear probing.  Much as fd_pool_para and fd_map_para are building blocks to implement more advanced concurrent data structures, this is a building block to support upcoming funk optimizations.
For example, it is straightforward to use this to declare an in-memory map that can support O(10s) billion accounts with theoretical minimum asymptotic footprint and that can be lockfree massively concurrently queried by sig-verify tiles to determine where accounts for incoming unvalidated transactions are located (e.g. hot/in memory, cold/in a cold store, non-existent, ...) to discard invalid transactions even before spending cryptographic computational resources and such that the pack
and exec tiles can quickly …
=> Yet another concurrent persistent shared map implementation

src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_vm_test.c
Use spad debugging variants to track violations on spad memory (namely alloc overflow)
=> flamenco, fuzz: use spad debugging variants in harness setup and teardown

src/app/fdctl/config.h, src/app/fdctl/config_parse.c, src/app/fdctl/run/tiles/fd_repair.c, src/app/fdctl/run/tiles/generated/repair_seccomp.h, src/app/fdctl/run/tiles/repair.seccomppolicy, src/app/fdctl/run/topos/fd_firedancer.c, src/disco/topo/fd_topo.h, src/flamenco/repair/fd_repair.c, src/flamenco/repair/fd_repair.h
We periodically cache the known good repair peers to a file, so that we can request from these when we restart. This reduces startup times.
=> flamenco, repair: cache good repair peers to file

src/flamenco/runtime/program/fd_compute_budget_program.c
=> flamenco: remove warning log from compute budget program

src/flamenco/runtime/tests/fd_exec_instr_test.c
changes to `fd_txn_borrowed_account_modify_idx` now require a (barebones) txn_descriptor set up to correctly invoke
=> flamenco, fuzz: setup txn descriptor for CPI fuzzer

src/app/fdctl/run/run.c
Fixes https://github.com/firedancer-io/firedancer/issues/3787
The voting private key does not need to be specified for the validator to start and a lot of operators only have the pubkey handy (which the Agave validator takes as a valid argument). This should also allow the validator to start without setting the voting key which translates to a non-voting validator.
=> fdctl: remove vote key path check

contrib/checkptify/autodownload.py
It's best practice to use pythonic commands when possible
=> chore: replace basic operations with `os`

src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_system_program_nonce.c, src/flamenco/runtime/sysvar/fd_sysvar_recent_hashes.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/snapshot/fd_snapshot.c, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json
Agave's implementation derives the recent block hashes from the block hash queue. This PR aims to mirror that implementation to maintain conformance and reduce redundancy. There is no need to maintain recent hashes in the slot bank.
=> flamenco: remove redundant recent blockhashes from slot bank

src/app/fdctl/run/tiles/fd_repair.c, src/app/fdctl/run/tiles/fd_replay.c, src/disco/geyser/test_geyser.c, src/disco/rpcserver/fd_block_to_json.c, src/disco/rpcserver/fd_rpc_service.c, src/disco/store/fd_store.c, src/flamenco/runtime/fd_blockstore.c, src/flamenco/runtime/fd_blockstore.h, src/flamenco/runtime/fd_rocksdb.c, src/flamenco/shredcap/fd_shredcap.c
Introduce entry batch support to the blockstore and replay in a backwards-compatible way. We continue to deshred and assemble entire blocks, but also add windowing metadata to support a caller copying out shreds and assembling smaller chunks (entry batches) so they don't have to wait for the whole block.
=> feat(blockstore): entry batch windowing

src/app/fdctl/run/tiles/fd_replay.c, src/choreo/tower/fd_tower.c
1. Correct the indentation.
2. Add comments explaining the functionality of each part of `after_frag`.
3. Remove a redundant frontier modification and put `FD_TEST(fork->slot == curr_slot);` to test that that code is no-op.
=> Cleanup after_frag in the replay tile

src/flamenco/runtime/fd_account.h
Compare to agave logic, and observe the `as i64`:
```rust
/// Returns an error if the account data can not be resized to the given length
#[cfg(not(target_os = "solana"))]
pub fn can_data_be_resized(&self, new_length: usize) -> Result<(), InstructionError> {
let old_length = self.get_data().len();
// Only the owner can change the length of the data
if new_length != old_length && !self.is_owned_by_current_program() {
return Err(InstructionError::AccountDataSizeChanged);
}
// The new length can not exceed the maximum permitted length
if new_length > MAX_PERMITTED_DATA_LENGTH as usize {
return Err(InstructionError::InvalidRealloc);
}
// The resize can not exceed the per-transaction maximum
let length_delta = (new_length as i64).saturating_sub(old_length as i64);  // <--------------
if self …
```
=> runtime: fix fd_account_can_data_be_resized substraction signedness

src/app/fdctl/config.h, src/app/fdctl/config/default.toml, src/app/fdctl/config_parse.c, src/app/fdctl/run/run_agave.c
Allows snapshotting to be turned off per #3944. Also allows for a scenario if you want full snapshots but not incremental snapshots, whereby the originally passed `--full-snapshot-interval-slots` would have been ignored.
=> agave: allow disabling snapshots

src/ballet/pack/fd_pack_cost.h, src/ballet/pack/test_pack.c
The cost for built-ins will change to 3,000 lamports in SIMD-170. In order for our blocks not to be rejected when `apply_cost_tracker_during_replay` is activated, we need to charge this higher amount before the feature gate is activated.
=> pack: SIMD-170: set conservative limits for builtins

src/ballet/pack/fd_pack_cost.h
`migrate_address_lookup_table_program_to_core_bpf` will be activated on testnet in the next few epochs. We should therefore not charge ALT programs as if it was a builtin, in the same way we treated the config program.
=> pack: don't charge ALT as a builtin

src/app/fdctl/run/tiles/fd_store_int.c, src/disco/store/fd_store.c
This PR fixes a wrong initialization of `ctx->store->pending_slots` in the store_int tile which leads to memory corruption and the `stake_ci` null pointer dereference issue.
=> storei: fix a memory corruption issue

contrib/docker/ubuntu2004/Dockerfile
Without fetch param, it will generate the following error : 
[+] Building 0/1 line 333: cd: /firedancer/opt/git/zstd/lib: No such file or directory
=> Add fetch param to deps.sh

src/flamenco/runtime/fd_runtime.c
The blockstore read lock would never be released in this path.
=> blockstore: release read lock

src/util/sandbox/fd_sandbox.c
Nit, but if we were to encounter a kernel that has > 63 caps, `struct __user_cap_data_struct   data[2] = { { 0 } }` would be too small
=> sandbox: limit cap_last_cap to <= 64

src/app/fdctl/run/tiles/fd_replay.c, src/app/ledger/main.c, src/disco/consensus/test_consensus.c, src/flamenco/snapshot/fd_snapshot.c, src/flamenco/snapshot/fd_snapshot.h, src/flamenco/snapshot/fd_snapshot_restore.c, src/flamenco/snapshot/fd_snapshot_restore.h, src/flamenco/snapshot/test_snapshot_restore.c
- don't initialize the slot context and status cache from the full snapshot when loading with an incremental snapshot.
- use the base slot of the full snapshot to verify the filename of the incremental snapshot
=> snapshot: fix incremental snapshot loading

src/disco/consensus/test_consensus.c, src/flamenco/repair/fd_repair.c, src/flamenco/repair/fd_repair.h, src/flamenco/repair/fd_repair_tool.c
- remove un-used concept of permanent repair peer, which simplifies the code
- wait until we have stake weights before sampling repair peers. these are sent quickly now, as we propagate them to repair as soon as we load the manifest from the incremental snapshot, rather than waiting for the full snapshot to load.
-- this means that _all_ repair peer selection is stake-weighted.
- use stake-weighted random sampling to select repair sticky peers
note that this isn't perfect stake-weighting, because it is influenced by the order of peer discovery. it's not clear yet if this is a problem
this algorithm results in higher-staked peers being selected with lower latencies
=> repair: tweak peer selection

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/fd_quic_enum.h, src/waltz/quic/fd_quic_pkt_meta.h, src/waltz/quic/fd_quic_private.h, src/waltz/quic/tests/test_quic_bw.c
In normal running the client keeps sending us streams, and we send acks. Because acks aren't "mandatory ack" we don't get an RTT from them. So also added code to periodically (once per minute) throw in a ping.
Calculates smoothed_rtt and var_rtt (rttvar) according to spec. Uses these to set expiry on packets.
Follow up could include an implementation of the PTO (Probe Time Out) algorithms from the spec.
=> QUIC - RTT handling code, improved packet expiry

contrib/test/test-vectors-fixtures/txn-fixtures/program-tests.list, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Adds error propagation for all cpi-related syscall and instr errors.
=> flamenco: propagate all cpi syscall and instr errors

book/guide/tuning.md
While playing around with frankendancer layout configs, it was not clear why our core count and configured tile count were mismatching until we looked into the code to see these other tile types.
=> Update tuning page with 4 other tiles in fd_frankendancer.c

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_private.h, src/waltz/quic/tests/test_quic_conformance.c
Currently, unfinished streams in send_streams that have no data ready to transmit are simply skipped over. However, this leaves those 'stale' streams in send_streams for every iteration of generating stream frames. This change ensures that unfinished but data-less streams are moved from send_streams into used_streams.
=> Quic: Move unfinished streams from send_streams to used_streams

contrib/test/test-vectors-fixtures/txn-fixtures/program-tests.list, src/flamenco/runtime/context/fd_exec_txn_ctx.c
Fixes incorrect behavior in cases where a user upgrades + invokes a program in the same txn
=> fuzz, flamenco: fix executable account fetching bug for writable program accounts

contrib/test/test-vectors-fixtures/cpi-fixtures/cpi.list, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Use slice translator for byte array to allow for zero length translations
Implement W-permissioned translation on account info data length field
Re-translate with post length when updating caller
Log privilege escalation error messages in prepare_instruction
=> flamenco: more cpi fixes

src/flamenco/runtime/sysvar/fd_sysvar_epoch_schedule.c
Compare with agave logic:
https://github.com/firedancer-io/agave/blob/a00f1b5cdea9a7d5a70f8d24b86ea3ae66feff11/sdk/epoch-schedule/src/lib.rs#L189-L200
```rust
pub fn get_first_slot_in_epoch(&self, epoch: u64) -> u64 {
if epoch <= self.first_normal_epoch {
2u64.saturating_pow(epoch as u32)
.saturating_sub(1)
.saturating_mul(MINIMUM_SLOTS_PER_EPOCH)
} else {
epoch
.saturating_sub(self.first_normal_epoch)
.saturating_mul(self.slots_per_epoch)
.saturating_add(self.first_normal_slot)
}
}
```
=> sysvar: fix fd_epoch_slot0 < to <=

contrib/test/test-vectors-fixtures/cpi-fixtures/cpi.list, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Hoist translate_instruction final checks into the right place
Move MaxInstructionTraceLengthExceeded check to right before instruction execution
=> flamenco: cpi fixes

src/waltz/quic/fd_quic.c, src/waltz/quic/tests/fd_quic_test_helpers.c, src/waltz/quic/tests/fd_quic_test_helpers.h
Fixes drops caused by the old reorder emulation by adding an extra buffer space. Respects reordering and avoids starvation via weighted coin toss. 
Also fixes a previous bug in calculating margin of safety on pkt_meta expiry.
=> Quic: Fix NetEm Reorder, and pkt_meta->expiry margin sign

src/waltz/quic/fd_quic.c
Fixes another instance of the QUIC flood bug
=> quic: hardcode default loss timeout

src/flamenco/gossip/fd_gossip.c
To follow Agave's CRDS filter policy changes: https://github.com/anza-xyz/agave/commit/d68b5de6c0fc07d60cf9749ae82c2651a549e81b
Nodes should never push unverifiable entries, so receiving one is problematic. We also (potentially) save on some sigverify cycles which is always a plus.
=> gossip: short-circuit on CRDS verify fail

src/util/sandbox/test_sandbox.c
- test_sandbox checks for max_mnt_namespaces==1 but fd_sandbox
sets it to 2
- test_sandbox checks for RLIMIT_NICE=1 but fd_sandbox sets it to 1
=> Fix bugs in test_sandbox

src/app/fdctl/external_functions.c, src/app/fdctl/run/tiles/fd_bank.c, src/ballet/txn/fd_txn.h, src/disco/pack/fd_compute_budget_program.h, src/disco/pack/fd_microblock.h, src/disco/pack/fd_pack.c, src/disco/pack/fd_pack.h, src/disco/pack/fd_pack_cost.h, src/disco/pack/test_compute_budget_program.c, src/disco/pack/test_pack.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/tests/fd_pack_test.c
The pack tile maintains compute cost for transactions in order to properly fill block. This PR some issues with the current calculation
- Use loaded accounts data cost
- Use the correct number of units for simple votes
- Use default 200k units for config program, which will be migrated to BPF
=> pack: fix compute units

contrib/test/test-vectors-fixtures/cpi-fixtures/cpi.list, src/flamenco/vm/syscall/fd_vm_cpi.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Add the equivalent of CallerAccount.  This allows us to do a read-only translation on AccountInfo, matching the translation permission in Agave. Additionally, translations are now properly cached or delayed, rather than repeated unconditionally.
=> flamenco: cpi fixes numero cuatro

src/flamenco/runtime/fd_account.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c
This mirrors https://github.com/anza-xyz/agave/pull/2202
Also gate account executable check in cpi prepare_instruction behind the remove_accounts_executable_flag_checks flag.
=> flamenco: implement lift_cpi_caller_restriction

src/flamenco/runtime/fd_blockstore.c, src/flamenco/runtime/fd_blockstore.h, src/flamenco/runtime/fd_rocksdb.c
solves the occasional seg fault when inserting into txn_map
=> blockstore: add locks on txn map modification

src/app/fdctl/config/default.toml
Addresses https://github.com/firedancer-io/firedancer/issues/4127
Applies this [patch](https://github.com/firedancer-io/agave/compare/3ef78d374c..jherrera/gui-fetch-peer-info~6) to `firedancer: gui, send peer table information`
=> gui: fetch validator config at startup

src/util/spad/fd_spad.c, src/util/spad/fd_spad.h, src/util/spad/test_spad.c
Adds fine-grained deep asan support in spad by making all allocations in spad have a minimum alignment of 8 bytes when DEEPASAN is enabled / a minimum alignment of 4 bytes when MSAN is enabled.
Also note that manual asan poisoning must be on 8-byte aligned addresses, but can be done on arbitrary sizes.
Currently, an MSAN build does not compile... will have to punt this to a later issue.
=> util: fine grained deep asan support in spad

src/disco/net/fd_net_tile.c
Fixes slight latency increases (~200ns) with some XDP configs.
The XDP skb path seems to only consume fill ring entries when
receiving a packet.  The fill ring is thus mostly full for these
configs.
Consider a scenario where ksoftirqd consumes a packet, consumes
a fill ring descriptor, and allocates a RX ring descriptor.
When the net tile concurrently runs on a different CPU, it might
have seen the updated cache line carrying the RX producer seqno,
but not yet the FILL consumer seqno (data race).
In this case, the net tile will refuse to consume the RX frag as
it doesn't have space to return that frag to FILL (since FILL
appeared full to it).  The net tile then starts spinning (about 30
iterations or so on EPYC 7502P).
By doubling the FILL ring depth, the net tile will always have
enough …
=> Double the XDP fill ring depth

src/app/fdctl/configure/hugetlbfs.c
Fixes https://github.com/firedancer-io/firedancer/issues/4195
=> hugetlbfs: fix parsing error when mounted with a gid

src/flamenco/vm/syscall/fd_vm_syscall_macros.h, src/flamenco/vm/syscall/fd_vm_syscall_runtime.c
These should be done on the host addresses, not the virtual addresses. This is the only place remaining where this was incorrect.
=> flamenco, vm: correct overlap checks in get_processed_sibling_instruction

src/app/fdctl/run/tiles/fd_replay.c, src/app/fdctl/run/topos/fd_firedancer.c, src/disco/restart/fd_restart.c, src/disco/restart/fd_restart.h, src/disco/topo/fd_topo.h
This PR extends PR #3830 and achieves the following while moving wen-restart into a separate tile.
1. Generate a snapshot at the end of wen-restart; Insert a hard fork and calculate a new shred version.
2. Fix tower checkpoint by checkpointing all the voted slots from the last voted slot back to the ghost root; Some of these slots may not be in the tower.
3. Improve the code style.
=> Complete the implementation of wen-restart

src/app/fdctl/config_parse.c, src/util/sandbox/fd_sandbox.c
In fd_toml.c, `fd_toml_parse_boolean`, the value (0 or 1) gets inserted with `fd_pod_insert_int`, which does zig-zag encoding. Because we weren't doing zig-zag decoding on the parse side, true was returned as `2`, not `1`.
=> sandbox: fix dumpable option

src/app/fdctl/run/tiles/fd_gui.c, src/app/fdctl/run/tiles/fd_plugin.c, src/app/fdctl/run/tiles/fd_poh.c, src/app/fdctl/run/topos/fd_frankendancer.c, src/disco/gui/fd_gui.c, src/disco/plugin/fd_plugin.h
- Add link for validator info messages
- fix message size calculation in plugin
- send info messages as they are found in accounts db (rather than all at one at the end)
agave [diff](https://github.com/firedancer-io/agave/compare/5f63d808b5..jherrera/gui-fetch-peer-info-2~7)
=> gui: add validator icons/names

src/app/fdctl/run/tiles/fd_pack.c, src/disco/plugin/fd_bundle_crank.c, src/disco/plugin/fd_bundle_crank.h
Previously, the tip_receiver was not getting set in the cached copy of the on-chain state. This caused a loop:
- Start slot 0 in `[Not Ready]`
- Schedule an IB, transition to `[Pending]`
- IB completes successfully, transition to `[Ready]`
- Prior to scheduling a bundle, determine that it needs to be cranked because the tip_receiver doesn't seem right.
- Insert IB, schedule it instead of the bundle, transition to `[Pending]`
- Repeat until the end of the slot.
At the start of the next slot, when we get an updated copy of the on-chain state from the poh tile, this problem goes away.
=> pack: fix bundle issue in slot 0 of rotation

src/flamenco/runtime/tests/run_ledger_tests_all.py
Ensures that we don't use too many cores on large boxes, which causes us to use an excessive amount of memory on boxes with large core counts. This limits the ledger tests to using 5 batches of 10 cores.
Ledger replay in CI is 8m 19s with this change.
=> flamenco, tests: limit number of cpu cores used in run-runtime-test

.github/workflows/clusterfuzz.yml
we need to know the llvm version; the `buildpwd` file should be generated from inside the compilation step (which is actually inside of a docker image)
=> modify coverage build step for solfuzz

src/flamenco/gossip/fd_gossip.c
Couple of independent fixes to improve Gossip performance
- [flamenco, gossip: bump CRDS value expiration time](https://github.com/firedancer-io/firedancer/commit/e25aea7d32c756d6e5767c0d118722e05b2e1abc)
- CRDS values were initially discarded after 1 min. While this was fine for regularly updated entries (vote, contact info), epoch slots suffered as they aren't updated often (we see roughly 500 new entries in testnet per minute). This meant the table discarded useful epoch slot values too early, and therefore each pull request constructed bloom filters without these entries, causing a replenish spam from other validators. By extending the expiry window from 1 minute to 1 hour (Agave's equivalent is roughly 1 epoch, which we haven't tested), we hold on to these epoch slot entries longer …
=> Flamenco, Gossip: epoch slot fixes

src/app/fdctl/run/tiles/fd_shred.c
A shred tile looks at the shred signature within during_frag to determine if it is responsible for that shred. If not, it sets ctx->skip_frag=1. 
In after_frag, where it does the actual processing, it currently does not check skip_frag. Therefore, the FEC resolver receives the old frag that's in shred_buffer again. While this doesn't affect correctness, it does waste a few cycles until the resolver dedupes. 
This PR checks skip_frag at the top of after_frag, early exiting if possible.
=> shred: read skip_frag

src/flamenco/runtime/sysvar/fd_sysvar_clock.c
If there are no votes, the clock timestamp should retain its previous value.
=> flamenco, clock: correctly update clock when no votes are present

src/app/fdctl/run/tiles/fd_restart.c
When querying the transaction map in funk with `fd_funk_txn_query`, we need the transaction ID, i.e., the `xid` argument. Previously, `xid.ul[0]` is used to store the slot number and `xid.ul[1]` is used to store part of the block hash for this slot. Recently, the use of `xid` has changed and we now need to make both `xid.ul[0]` and `xid.ul[1]` be the slot number when querying the funk transaction map.
=> Fix funk_txn query in restart tile

contrib/test/test-vectors-fixtures/vm-interp-fixtures/vm_interp-fixtures.list, src/flamenco/vm/fd_vm_interp_core.c
Agave only executes the slow path partial store when the memory region is an `UnalignedMemoryRegion` AKA direct mapping.
=> flamenco: slow path store fix

src/disco/pack/fd_pack.c, src/disco/pack/test_pack.c
The extras section is not consensus-critical, but was used for either accounts that seemed like they should be on the list or as a DoS-mitigation measure. Now that we have penalty treaps and CU pacing, the impact of a transaction write-locking one of these accounts is pretty minimal.
=> pack: trim list of unwritable accounts

src/disco/pack/fd_pack.c, src/disco/pack/fd_pack.h, src/disco/pack/test_pack.c
Previously, the underlying pool size for the treaps and the priority queue was larger than the max passed to these data structures at initialization. This leads to out of bounds accesses (treap/prq contract violation).
The problem can be observed by checking if the treap is still valid after inserting a transaction and then running pack unit tests.
```diff
@@ -1288,6 +1288,7 @@ fd_pack_insert_txn_fini( fd_pack_t  * pack,
return replaces ? FD_PACK_INSERT_ACCEPT_VOTE_REPLACE : FD_PACK_INSERT_ACCEPT_VOTE_ADD;
} else {
treap_ele_insert( insert_into,         ord, pack->pool );
+    FD_TEST(treap_verify( insert_into, pack->pool )!= -1);
return replaces ? FD_PACK_INSERT_ACCEPT_NONVOTE_REPLACE : FD_PACK_INSERT_ACCEPT_NONVOTE_ADD;
}
}
```
Drive-by: typo fixes
=> pack: fix treap and prq sizes

src/disco/fd_disco_base.h, src/disco/shred/fd_shred_tile.c, src/discof/replay/Local.mk, src/discof/replay/fd_replay.c, src/discof/replay/fd_replay.h, src/discof/replay/fd_replay_tile.c, src/flamenco/runtime/fd_blockstore.c
- Removal of dependency on storei tile is a separate PR; so currently the storei tile still provides the `ctx->curr_slot` to drive execution. If the storei tile delivers a new slot fast enough, replay prepares for slot n, and then ends up executing for slot `n+1` and will err with `Unable to select a fork.` 
- Eviction from fec map is also a separate PR -- so the fec_insert may segf
- Changing shred_replay sig to more elegant is separate PR
- can mark leader/not leader
- have replay tile keep a separate ds of fecsets so that it can populate slice deque without polling the blockstore
=> replay: execute shreds recieved from shred tile

src/app/fdctl/config/default.toml
- Minor grammar improvements
- Adverb at beginning of sentence needs comma ("Instead, ...")
- Split up long compound sentences (", and ...")
- 'a' vs 'an' issues
- Typo fixes
- 'catchup' -> 'catch up'
- 'firedancer' -> 'Firedancer'
- Common hyphen words ("round-robin")
- Space between integer and unit ("1GiB" -> "1 GiB")
- 'filesystem' -> 'file system'
=> default.toml LanguageTool pass

src/waltz/quic/tls/fd_quic_tls.c
This PR fixes a bug during wrap-around in the quic_tls_hs circular buffer. Currently, if we ever wrap-around to the front of the buffer, we set head back to 0. However, this violates the invariant that head >= tail, causing a crash when popping that data. 
Additionally, if head actually wrapped around, we'd use bytes_used (head-tail) rather than bytes_avail to check if we had enough available space.
The server never hit this issue, because it always wrote less data than buffer size so never wrapped around. Fixing it nevertheless.
=> quic_tls: maintain invariant

contrib/test/test-vectors-fixtures/syscall-fixtures/sol_get_sysvar.list, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json
Thanks to @anarcheuz for root causing this!
=> flamenco: fix epoch rewards alignment to match agave

src/discof/replay/fd_replay.c, src/discof/replay/fd_replay.h
documentation inconsitencies, clip magic constant to fit into ulong, add magic check, remove unused field
=> replay: nits

src/discof/replay/fd_replay_tile.c
This PR fixes some some cases where `slots_per_epoch` was not being correctly initialized before accounts were loaded in the snapshot.
=> replay: correctly initialize rent collection in slot context

src/app/fdctl/Local.mk, src/app/fddev/Local.mk
Always build fdctl and fddev in 'make all'
=> Remove 'make rust' target for full Firedancer

src/disco/verify/fd_verify_tile.c, src/disco/verify/fd_verify_tile.h, src/disco/verify/test_verify.c
>   /* Users sometimes send transactions as part of a bundle (with a tip)
and via the normal path (without a tip).  Regardless of which
arrives first, we want to pack the one with the tip.  Thus, we
exempt bundles from the normal HA dedup checks.  The dedup tile
will still do a full-bundle dedup check to make sure to drop any
identical bundles. */
=> verify: don't dedup bundles

src/waltz/quic/fd_quic.c
Because a connection can be in at most one service queue, we take the earlier timer. However, this means we may have no timer to fire when pkt_meta expire in the future. This PR fixes that - it ensures that if we have any pkt_meta at all, the connection will be scheduled again. 
Note this is quite crude - because the service queues prevent dynamic timers at moment, we aren't rescheduling for the exact expiry of the pkt_meta. However, this at least guarantees we will eventually service this connection once the pkt_meta expires.
We do the rescheduling in pkt_meta_retry(), where we've just searched through the pkt_meta. This relies on conn_service always calling pkt_meta_retry. When that changes, we'll want to make sure this still works.
=> quic: reschedule service when any pkt_meta

contrib/test/test-vectors-fixtures/elf-loader-fixtures/elf-loader-fixtures.list, src/ballet/sbpf/fd_sbpf_loader.c, src/ballet/sbpf/fd_sbpf_loader.h, src/ballet/sbpf/fuzz_sbpf_loader.c, src/ballet/sbpf/test_sbpf_load_prog.c, src/ballet/sbpf/test_sbpf_loader.c, src/flamenco/runtime/tests/fd_vm_test.c, src/flamenco/vm/fd_vm.c, src/flamenco/vm/fd_vm_disasm.c, src/flamenco/vm/fd_vm_interp_core.c, src/flamenco/vm/syscall/fd_vm_syscall.c
Agave's syscall map implementation considers the full u32 range [0, UINT_MAX] as valid key entries, whereas firedancer's map reserves one value as the NULL key (i.e., 0). This means 0 is a valid entry in the Agave map and not ours. To fit the full range, we use a ulong key instead and define a value outside of the uint range to be the null key (i.e., ULONG_MAX)
=> ballet: use wider key type in fd_sbpf_syscalls

src/app/fdctl/topos/fd_firedancer.c, src/choreo/forks/fd_forks.c, src/choreo/forks/fd_forks.h, src/disco/fd_disco_base.h, src/discof/replay/fd_replay_tile.c, src/discof/store/fd_storei_tile.c, src/flamenco/runtime/fd_blockstore.h
- simulates intended repair tile behavior post-refactor using the store tile to deliver batches in order. Should be able to plug `STORE_IN_IDX` with `REPAIR_IN_IDX`
- patches the "Unable to select fork" err.
=> replay/store: replay in-order batches from storei with after_credit execution

src/flamenco/runtime/fd_acc_mgr.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_txn_account.c, src/flamenco/runtime/fd_txn_account.h
orig_meta was not being used, as it is the same as const_meta for read-only accounts. `fd_txn_account_restore` was also not being used at all.
=> flamenco: remove orig_meta from fd_txn_account_t

src/discof/replay/fd_replay_tile.c, src/flamenco/fd_flamenco_base.h, src/flamenco/runtime/context/fd_exec_slot_ctx.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/snapshot/fd_snapshot.c, src/flamenco/types/fd_type_names.c, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json, src/flamenco/types/test_types_fixtures.c
Previously `rent_fresh_accounts` was the size of the number of partitions, which meant a lot of memory was consumed and the `slot_bank` serialization/deserialization was too slow. This PR makes `rent_fresh_accounts` simply be a vector, and optimizes for the common case where we have no fresh accounts.
=> flamenco, runtime: change rent_fresh_accounts to be a list

src/flamenco/runtime/tests/fd_vm_test.c
When max_pc is a multiple of 64 we end doing an off-by-one bitmask AND. We actually don't need to apply a bitmask if the rodata size ends up being a multiple of 64 bytes.
=> flamenco: fix off-by-one bug in fd_vm_test

src/discof/store/fd_storei_tile.c
shred34 can contain up to 34 shreds, so a check was added to enforce this
=> add an additional check on the upper bound of the shred34 shred count

src/discof/eqvoc/fd_eqvoc_tile.c
add an additional check on the length of the duplicate shred we receive from the gossip tile
=> check the incoming duplicate shred chunk len in eqvoc

src/flamenco/runtime/context/fd_exec_instr_ctx.c, src/flamenco/runtime/context/fd_exec_instr_ctx.h, src/flamenco/runtime/context/fd_exec_txn_ctx.c, src/flamenco/runtime/context/fd_exec_txn_ctx.h, src/flamenco/runtime/fd_borrowed_account.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_system_ids.h, src/flamenco/runtime/fd_txn_account.h, src/flamenco/runtime/info/fd_instr_info.c, src/flamenco/runtime/program/fd_bpf_loader_program.c, src/flamenco/runtime/program/fd_bpf_loader_program.h, src/flamenco/runtime/program/fd_bpf_loader_serialization.c, src/flamenco/runtime/program/fd_config_program.c, src/flamenco/runtime/program/fd_loader_v4_program.c, src/flamenco/runtime/program/fd_stake_program.c, src/flamenco/runtime/program/fd_system_program_nonce.c, src/flamenco/runtime/sysvar/fd_sysvar_instructions.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi.c, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Notable changes:
- simplify txn_ctx account getter APIs to match Agave semantically and allow for users to pass in an account pre-condition checker function.
- Add `try_borrow_last_program_account` in the instr_ctx to match agave semantics and account borrowing checks.
=> flamenco: refactor txn_ctx/instr_ctx account getters API

config/extra/with-extra-brutality.mk, src/util/env/fd_env.h, src/util/fd_util_base.h, src/util/tmpl/fd_deque.c, src/util/tmpl/fd_deque_dynamic.c, src/util/tmpl/fd_dlist.c, src/util/tmpl/fd_heap.c, src/util/tmpl/fd_map.c, src/util/tmpl/fd_map_chain.c, src/util/tmpl/fd_map_dynamic.c, src/util/tmpl/fd_map_giant.c, src/util/tmpl/fd_map_para.c, src/util/tmpl/fd_map_slot_para.c, src/util/tmpl/fd_pool.c, src/util/tmpl/fd_prq.c, src/util/tmpl/fd_set.c, src/util/tmpl/fd_set_dynamic.c, src/util/tmpl/fd_smallset.c, src/util/tmpl/fd_treap.c, src/util/tmpl/test_heap.c, src/util/tmpl/test_pool.c, src/util/tmpl/test_set.c, src/util/tmpl/test_set_dynamic.c, src/util/tmpl/test_smallset.c, src/util/tmpl/test_treap.c
By popular demand.  Roughly 1-2 orders of magnitude faster for operations on large contiguous ranges of elements.
Drive by cleanups:
- util_base.h: FD_FN_PURE/FD_FN_CONST do not hint by default to help with various CI and fuzzing tools.  This also eliminates the need for maintaining the FD_HAS_HANDHOLDING.
- with-extra-brutality.mk: Hinting is still enabled manually with extra-brutality for various linting.
- src/env/env.h: a prototype outside FD_PROTOTYPE pair fixed
- test_pool.c: enabled some checks accidentally disabled due to a typo.
- Also did some minor linting around FD_FN_PURE / FD_FN_CONST in util/tmpl.
- And, also by popular demand, did a linting pass on handholding, eliminating a handful of checks that aren't actually handhold-y.  (This unfortunately touches a lot of files but …
=> Added range APIs to smallset, set and set_dynamic and other cleanups

src/disco/dedup/fd_dedup_tile.c
Reported via the bounty by @eternal_Zellic. This really is not a security bug because the oob read can only be triggered by a compromised tile, and this oob read does not provide any primitive useful towards achieving inter-tile RCE. Still it is could hygiene to move the check before the usage.
=> dedup: fix inter-tile oob read

contrib/offline-replay/offline_replay_network_parameters.sh
`testnet-ledger-asia-east1` seemed to be having some issues so changing back to `testnet-ledger-us-sv15`
=> offline-replay: change testnet ledger endpoint

contrib/test/test-vectors-fixtures/instr-fixtures/bpf-loader-v3.list, src/flamenco/runtime/program/fd_bpf_loader_program.c
Agave did not error out immediately when obtaining the new authority key while we were returning the error. See https://github.com/anza-xyz/agave/blob/v2.1.14/programs/bpf_loader/src/lib.rs#L901-L906
=> flamenco: fix bpf loader new authority key err mismatch

src/discof/repair/Local.mk, src/discof/repair/fd_fec_chainer.c, src/discof/repair/fd_fec_chainer.h, src/discof/repair/test_fec_chainer.c
This provides APIs for chaining FEC sets.  Every FEC set has a parent (the immediately preceding FEC set in the slot or parent slot) and children (immediately succeeding FEC set(s) for the same slot or child slots).
The purpose of the chainer is connect FEC set parents with their children as they are received asynchronously out-of-order from the network via Turbine and Repair, and to both validate and deliver these FEC sets in-order to the caling application.
Because of forks, FEC sets can have multiple children, but this will only be true across slots (ie. the parent and child must be different slots). There is a protocol violation called equivocation (also known as "duplicates") that can break this invariant.  Equivocation can also result in other anomalies such as keying collisions …
=> feat(repair): implement fec_set_chainer for repair tile

src/waltz/quic/fd_quic.c
There are currently 2 ping-related connection flags. One is CONN_FLAGS_PING and the other is CONN_FLAGS_PING_SENT. Ping_sent is intended to prevent sending new pings when there is already a ping in-flight. We should only ever unset it on reclaiming or retrying a pkt_meta. However, there is one extra unset right now during keep-alive (which, to be fair, is not in use rn). This PR fixes that.
=> quic: fix ping_sent flag

src/app/fdctl/config/default.toml, src/app/shared/fd_config.c
`{user}` and `{home}` variables are substituted in a lot of paths, but not `[ledger.accounts_path]` which can lead to some confusion. This PR adds the corresponding `replace` calls, and updates the documentation in default config.
=> fdctl: substitute {user} and {home} in ledger.accounts_path

contrib/test/test-vectors-fixtures/txn-fixtures/program-tests.list, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h
https://github.com/anza-xyz/agave/pull/5207 fixed a bug in the implementation of `remove_accounts_executable_flag_checks`
=> flamenco: add owner check in fd_executor_lookup_native_program

src/flamenco/rewards/fd_rewards.c, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/program/fd_address_lookup_table_program.c, src/flamenco/runtime/program/fd_loader_v4_program.c, src/flamenco/runtime/program/fd_stake_program.c, src/flamenco/runtime/program/fd_system_program_nonce.c, src/flamenco/runtime/program/fd_vote_program.c, src/flamenco/runtime/sysvar/fd_sysvar_cache.c, src/flamenco/runtime/sysvar/fd_sysvar_cache.h, src/flamenco/runtime/sysvar/fd_sysvar_clock.c, src/flamenco/runtime/sysvar/fd_sysvar_epoch_rewards.c, src/flamenco/runtime/sysvar/fd_sysvar_epoch_schedule.c, src/flamenco/runtime/sysvar/fd_sysvar_fees.c, src/flamenco/runtime/sysvar/fd_sysvar_last_restart_slot.c, src/flamenco/runtime/sysvar/fd_sysvar_rent.c, src/flamenco/runtime/tests/fd_exec_instr_test.c, src/flamenco/runtime/tests/fd_exec_sol_compat.c, src/flamenco/stakes/fd_stakes.c, src/flamenco/types/fd_bincode.h, src/flamenco/types/fd_types.c, src/flamenco/types/fd_types.h, src/flamenco/types/fd_types.json, src/flamenco/types/fd_types_custom.c, src/flamenco/types/fd_types_custom.h, src/flamenco/types/gen_stubs.py, src/flamenco/types/test_types_fixtures.c
1. make it so global types decode supports nested local pointers
2. remove global types that don't need to be global
3. add global encodes
=> runtime: fixing global types decode/encode

src/flamenco/runtime/program/fd_bpf_loader_program.c, src/flamenco/runtime/tests/run_ledger_tests_all.txt
If the upgrade authority address is None, we should update this correctly.
=> replay, bpf_loader_program: support un-setting upgrade authority address

src/util/tmpl/fd_pool_para.c
Compare against comment:
https://github.com/firedancer-io/firedancer/blob/a11b37fcc81cea10a3b601ddc33b77b96ff6415e/src/util/fd_util_base.h#L830-L836
Issue, is easy to see with a simple PoC:
```c
#include "../fd_util.h"
#include "../log/fd_log.h"
struct myele {
uint mynext;
uint val;
};
typedef struct myele myele_t;
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmacro-redefined"
#define FD_HAS_ATOMIC 1
static inline ulong
mypool_private_cas( ulong volatile * p,
ulong            c,
ulong            s ) {
ulong o;
FD_COMPILER_MFENCE();
o = FD_ATOMIC_CAS( p, c, s );
o = *p;
*p = fd_ulong_if( o==c, s, c );
FD_COMPILER_MFENCE();
return o;
}
#define FD_HAS_ATOMIC 0
static inline ulong
mypool2_private_cas( ulong volatile * p,
ulong            c,
ulong            s ) {
ulong o; …
```
=> fd_pool_para: fix atomic emulation logic in POOL_(private_cas)

src/flamenco/runtime/fd_executor.c
fix https://github.com/firedancer-io/firedancer/security/code-scanning/71
=> flamenco: move comparison inside FD_LIKELY

src/disco/pack/fd_pack_cost.h, src/disco/pack/test_pack.c, src/discoh/bank/fd_bank_tile.c
- We were double counting builtin costs (which is safe, but undesirable)
- print warning log when cu invariants are violated
=> pack, bank: cu improvements

src/ballet/toml/fd_toml.c, src/flamenco/runtime/fd_blockstore.h, src/flamenco/vm/test_vm_instr.c, src/funk/fd_funk.c, src/funk/fd_funk.h, src/funk/fd_funk_rec.c, src/funk/fd_funk_rec.h, src/funk/fd_funk_txn.c, src/funk/fd_funk_txn.h, src/util/cstr/fd_cstr.c, src/util/cstr/fd_cstr.h, src/util/cstr/test_cstr.c, src/util/log/fd_log.c, src/util/pod/fd_pod_ctl.c, src/util/shmem/fd_shmem_admin.c, src/util/shmem/test_shmem.c, src/util/tile/fd_tile_threads.cxx, src/util/tmpl/Local.mk, src/util/tmpl/fd_map_chain_para.c, src/util/tmpl/fd_map_slot_para.c, src/util/tmpl/test_map_chain_para.c
Hmmm ...
```
$ cat ctype_considered_harmful.c
#include <stdio.h>
#include <ctype.h>
int
main( int     argc,
char ** argv ) {
int bad_standards_make_babies_cry = isspace( '\n' );
printf( "isspace( '\\n' ) = %i\n", bad_standards_make_babies_cry );
return 0;
}
$ gcc ctype_considered_harmful.c
$ ./a.out
isspace( '\n' ) = 8192
```
... see code for more discussions.
Also, by popular demand, renamed fd_map_para to fd_map_chain_para.
=> ctype.h considered harmful and other cleanups

src/disco/shred/fd_shred_tile.c
The shred tile now sets (by default) send_fec_set_idx to max value for IN_KIND_POH inside during_frag.
=> disco: shred tile fec_set_idx to max by default

src/flamenco/gossip/fd_gossip.c
ping interval was accidentally bumped to 10s when it was (probably) meant to be every 100ms
=> flamenco, gossip: fix ping generation intervals

src/funk/fd_funk.c, src/funk/fd_funk.h, src/funk/fd_funk_rec.c, src/funk/fd_funk_rec.h
Addresses https://github.com/firedancer-io/firedancer/issues/4822
`fd_funk_delete` does not need to be thread-safe so we can remove the locking here, which removes the memory allocation.
=> funk: reduce memory allocation in fd_funk_delete

src/discof/batch/fd_batch_tile.c, src/flamenco/runtime/fd_hashes.c, src/flamenco/runtime/fd_hashes.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/snapshot/fd_snapshot.c, src/flamenco/snapshot/fd_snapshot.h
Adds a ledger test where:
- `LTHasHQX6661DaDD4S6A2TFi6QBuiwXKv66fB1obfHq` is enabled
- The lattice hash is _not_ present in the snapshot
=> flamenco: Fix lthash snapshot loaders

src/discoh/bank/fd_bank_abi.c, src/discoh/bank/fd_bank_abi.h
This was causing transactions to stomp on each other. Since we normally run with 1 transaction per microblock except in the bundle case, this was only triggering with bundles, which is why we didn't catch it immediately.
=> bank: fix agave 2.2 ABI

src/funk/fd_funk.h, src/funk/fd_funk_rec.c, src/funk/fd_funk_rec.h, src/funk/fd_funk_txn.c, src/funk/fd_funk_txn.h
Multi-threaded tpool perf
```
with global lock and 4 threads: Inserted 1000000 accounts in 0.57s (rate=1.8e+06 per_item=567ns)
with CAS on the txn object and 4 threads: Inserted 1000000 accounts in 0.34s (rate=2.9e+06 per_item=340ns)
```
single threaded perf:
```
With glocal rec pool lock: Inserted 1000000 accounts in 0.28s (rate=3.5e+06 per_item=284ns)
With CAS: Inserted 1000000 accounts in 0.29s (rate=3.5e+06 per_item=286ns)
```
Closes #4823
=> funk: remove rec pool global lock in rec_publish

src/flamenco/runtime/program/fd_system_program_nonce.c
We want to be log compatible with agave. This seems like a copy paste oversight from another function.
=> flamenco: fix log in fd_system_program_advance_nonce_account

src/app/fdctl/Local.mk, src/app/fdctl/version.c, src/app/firedancer/version.c, src/disco/gui/fd_gui_printf.c, src/util/fd_util_base.h, src/util/log/fd_log.c
- display correct version number when compiling agave cli tools like `solana`
- use correct version number for default log file directory
agave [diff](https://github.com/firedancer-io/agave/compare/876929e4775880f3f10bd71c1a823d01e3f5c2ab..jherrera/fix-cli-versions~3)
=> version: fix missing version numbers

src/disco/gui/fd_gui.c, src/disco/gui/fd_gui.h, src/disco/gui/fd_gui_printf.c, src/discof/replay/fd_replay_tile.c
In the gui, only leader slots were aware of max cus. This sends the value from the replay pipeline so that all slots reflect the limit accurately.
agave [diff](https://github.com/firedancer-io/agave/compare/3f7623b0fe..jherrera/gui-fix-cus-pct~9)
=> gui: fix CU pct for replayed slots

src/disco/topo/fd_topob.c
Fixes two bugs that result in workspace affinity to NUMA node 0
even if all user tiles are on a different NUMA node.
=> topo: fix workspace NUMA affinity

src/discof/forest/fd_forest.h
The header and the implementation do not agree on the order of the arguments, because the swaped arguments are of the same type the compiler does not catch this. Currently, everything is using it as the .c file expects it, so no usage fixes needed.
=> repair: fix fd_forest_new parameter mismatch

src/discof/forest/fd_forest.h
Right now this macro __always__ calls FD_LOG_ERR. Since there is no usage and no documentation, it is unclear what this macro should be used for in the future. Best we remove it until we actually need something like this.
=> repair: remove buggy FD_FOREST_TEST macro

src/discof/rpc/fd_rpcserv_tile.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/sysvar/fd_sysvar_slot_hashes.c, src/flamenco/runtime/sysvar/fd_sysvar_slot_hashes.h, src/flamenco/runtime/sysvar/fd_sysvar_slot_history.c, src/flamenco/runtime/tests/harness/fd_txn_harness.c
highly recommend hiding whitespace diffs
=> flamenco: initialize sysvar_slot_hashes in runtime + fix memory corruption in read genesis

src/flamenco/types/fuzz_types_decode.c
Types were already blacklisted during mutations, but now it prevents cases where fc corpus can get contaminated with blacklisted types.
=> flamenco: types fuzzer will reject blacklisted types

src/app/ledger/main.c, src/flamenco/runtime/fd_hashes.c, src/flamenco/runtime/fd_runtime.c
Fix solcap for slot 0,
Fix rent collection for slot 0,
Fix rent_epoch for accounts for slot 0
Fix leader and epoch length at slot 0
=> flamenco/genesis:  Address a bunch of genesis issues

src/app/shared/fd_config_parse.c, src/ballet/bigint/fd_uint256_mul.h, src/ballet/toml/fd_toml.c, src/disco/metrics/fd_metrics.h, src/disco/pack/fd_chkdup.h, src/disco/pack/fd_pack_rebate_sum.c, src/disco/pack/test_chkdup.c, src/discof/gossip/fd_gossip_tile.c, src/discof/poh/fd_poh.h, src/discoh/resolv/fd_resolv_tile.c, src/flamenco/fd_flamenco_base.h, src/flamenco/gossip/fd_gossip.c, src/flamenco/runtime/fd_acc_mgr.h, src/flamenco/runtime/fd_executor.c, src/funk/bench_funk_index.c, src/tango/tempo/fd_tempo.c, src/util/fd_util.h, src/util/math/test_stat.c, src/util/pod/fd_pod_ctl.c, src/util/pod/test_pod.c, src/util/rng/fd_rng.h, src/util/rng/test_rng.c, src/util/wksp/fd_wksp.h, src/util/wksp/fd_wksp_helper.c, src/waltz/quic/fd_quic.h, src/waltz/quic/fd_quic_private.h
Changes code so that including `fd_util.h` no longer includes `<x86intrin.h>` and friends.
The x86 intrinsics are about 70k lines of headers, which makes up the majority of compile-time for small compile units.
`make -j lib CC=gcc-14`:
Before: 0m28.815s
After: 0m26.495s
`make -j lib=CC=clang`:
Before: 0m21.672s
After: 0m19.811s
=> Remove x86intrin.h dependency from fd_util.h

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic.h, src/waltz/quic/tests/test_quic_hs.c
This PR makes keep_alive a quic config parameter rather than a compile time option. This is primarily to support the sender tile.
=> quic: keep alive config parameter

src/flamenco/runtime/tests/harness/fd_types_harness.c, src/flamenco/types/fd_types_custom.c, src/flamenco/types/fixtures/gossip_pull_req.yml, src/flamenco/types/fixtures/gossip_pull_resp_contact_info.yml, src/flamenco/types/fixtures/gossip_pull_resp_contact_info_v2.yml
1. Encode enum discriminants instead of names in in-memory representation (corresponding solfuzz-ag PR here https://github.com/firedancer-io/solfuzz-agave/pull/267)
2. Do not pretty print gossip ipaddrs (for now)
=> fuzz: types fuzzer compatibility changes

src/util/tmpl/fd_sort.c, src/util/tmpl/test_sort_para.c, src/util/tpool/fd_tpool.h, src/util/tpool/test_tpool.c
By popular demand and mentioned in parallel quick sort PR, this PR adds additional styles of parallel sorting.  This provides a thread parallel, NUMA friendly, cache friendly merge sort implementation.  (As a reminder, unlike quick sorts, merge sorts are stable but out-of-place.)
This implementation has an asymptotic wallclock of O(N) in the large thread count limit (as opposed to the N log N for a serial merge sort).
test_sort_para was updated to large arrays with more heavily randomized testing to explore more threading edge cases.
Tweaked FD_TPOOL_MAP_REDUCE to make this cleaner to implement and less restrictive to use and updated the test_tpool to reflect this. Specifically:
- FD_TPOOL_MAP_REDUCE no longer requires fd_scratch to be configured on the tpool threads used for the sorting. …
=> Parallel merge sorts

src/app/firedancer-dev/Local.mk, src/app/firedancer-dev/commands/backtest.c, src/app/firedancer-dev/main.c, src/app/shared/fd_config.h, src/app/shared/fd_config_parse.c, src/disco/archiver/Local.mk, src/disco/archiver/fd_archiver_backtest.c, src/disco/topo/fd_topo.h, src/disco/topo/fd_topob.c, src/discof/replay/fd_replay_tile.c
This PR adds the `backtest` command to firedancer-dev. This command spawns a smaller topology with only rocksdb, replay, exec and writer tiles, separate from the full topology. This smaller topology is used in CI which reads data shreds from rocksdb and replay the shreds.
=> firedancer-dev: add backtest (shred source: rocksdb) command

.github/workflows/codeql.yml
due to the recent split of build targets this change adds firedancer-dev to the CodeQL action
=> codeql: test frankendancer and firedancer in ci

src/ballet/sbpf/fd_sbpf_loader.c, src/flamenco/features/fd_features_generated.c, src/flamenco/features/fd_features_generated.h, src/flamenco/features/feature_map.json, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/sysvar/fd_sysvar_instructions.c, src/flamenco/runtime/sysvar/fd_sysvar_instructions.h, src/flamenco/runtime/tests/harness/fd_instr_harness.c, src/flamenco/runtime/tests/harness/fd_vm_harness.c
* Follows https://github.com/anza-xyz/sbpf/pull/39 and commit 9cba8b009a1a20955513d8270525b0b49a6d026c.
* Rekeys `enable_loader_v4` feature
* Move sysvar instructions updating to instruction level from txn level (follows https://github.com/anza-xyz/agave/pull/5698)
=> fuzz, flamenco: agave v2.2.13 support

src/app/firedancer-dev/config/private.toml, src/flamenco/runtime/tests/run_backtest_tests_all.sh, src/flamenco/runtime/tests/run_ledger_backtest.sh, src/flamenco/runtime/tests/run_ledger_tests_all.txt
example run:
```
(test_suite_env) [kbhargava@emch-ossdev-firedancer7 firedancer]$ src/flamenco/runtime/tests/run_ledger_backtest.sh -l slashing-ledger -s snapshot-1-3pPnJsADcbDoFaCJr8Fcvb6UHf2jDUdAtbJ3G2JtevDK.tar.zst -p 60 -y 16 -m 5000000 -e 44 -c 2.3.0
Starting on-demand ingest and replay
Running backtest for slashing-ledger
+ build/native/gcc/bin/firedancer-dev backtest --config ./dump/slashing-ledger_backtest.toml
Finished on-demand ingest and replay
Log for ledger slashing-ledger at /tmp/ledger_log3854442
```
=> backtest: script improvements

src/discof/repair/fd_repair_tile.c
There's a case where we use ctx->stem in fd_repair_tile's after_frag before setting it to the stem argument. ctx->stem is 0 when uninitialized, so segfaults. This PR fixes that.
=> repair: fix stem segfault

src/flamenco/runtime/fd_runtime_init.c, src/flamenco/runtime/fd_runtime_init.h
https://github.com/anza-xyz/solana-sdk/pull/168
=> flamenco, feature: fix feature deserialize for incorrect account size

src/discof/repair/fd_repair_tile.c
This PR is a temporary quick fix to ensure that replay's view of the poh_slot actually updates, and so it generates votes to send. That broke with a recent regression.
=> repair: init poh_slot to first turbine slot

src/app/fdctl/commands/run_agave.c, src/app/fdctl/config/default.toml, src/app/shared/fd_config.c, src/app/shared/fd_config.h, src/app/shared/fd_config_parse.c
- delay the throughput check to after 5 seconds
- add maximum_snapshot_download_abort config option with a default value of 5 retries
Once merged, I will also backport to v0.5 branch
agave [diff](https://github.com/firedancer-io/agave/compare/dbe432c3ce23df..jherrera/inc-speed-test_duration)
=> agave, snapshot: add download-abort param, delay download speed check

src/app/ledger/main.c, src/discof/consensus/test_consensus.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/tests/harness/fd_block_harness.c, src/util/alloc/fd_alloc.h, src/util/archive/fd_tar.h, src/util/bits/fd_bits.h, src/util/fd_util.h, src/util/scratch/fd_scratch.h, src/util/spad/fd_spad.h, src/util/tmpl/fd_sort.c, src/util/tmpl/test_sort_para.c, src/util/tpool/fd_map_reduce.h, src/util/tpool/fd_tpool.cxx, src/util/tpool/fd_tpool.h, src/util/tpool/test_tpool.c, src/util/wksp/fd_wksp.h, src/util/wksp/test_wksp_tpool.c
Polished up some thread parallelism rough edges noted in the recent parallel thread sorting API installation.  Significant performance improvement for thread parallelism strong scaling (not that it wasn't already very fast) and some low impact tpool API changes from user point of view for existing usages (that make it easier to use and more flexible to deploy):
- Improved cache traffic between dispatch and worker threads in tpool. Thread dispatch / sync is low tens of percent faster (from ~400 ns per level to ~300 ns per level by reducing cache contention).  A side effect of this is that the tpool state variable was split into two sequence number variables.  This eliminated the FD_TPOOL_WORKER_STATE_* defines and corresponding fd_tpool_state_cstr APIs.  It also replaced the …
=> Parallelization tune up and other cleanups

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic_conn.h, src/waltz/quic/templ/fd_quic_transport_params.h, src/waltz/quic/templ/test_quic_transport_params.c, src/waltz/quic/tests/fd_quic_sandbox.c, src/waltz/quic/tests/test_quic_concurrency.c
We currently don't convert the incoming peer_tp max_idle_timeout from ms to ticks when we take the min. So we probably timeout ticks_per_ns too fast. Opening this PR for now if folks want to take a look. Testing on val4 first.
=> Fix idle timeout units

src/waltz/quic/fd_quic.c, src/waltz/quic/tests/test_quic_conformance.c
Current behavior causes gaps in packet numbers, leading to inefficient ack ranges, and difficulty with diagnostics.
This patch avoids most such skips.
=> quic - only increment pkt_number when we have committed the current packet into the tx buffer

src/discof/repair/fd_repair_tile.c, src/flamenco/repair/Local.mk, src/flamenco/repair/fd_repair.c, src/flamenco/repair/fd_repair.h
Series of repair improvements, mostly simplifying what we have
- takes response rate by peer from ~50% -> 95% (could later track rndtrip latency)
- benchmarked catchup handful of times::
- pre-commit: takes > 400ms / slot to execute from snapshot to first turbine including repair stalls
- post: takes ~200ms/slot to execute from snapshot to first turbine inclusing repair stalls
Also overall way less shred->repair backpressure
=> repair: improvements

src/waltz/quic/fd_quic.c, src/waltz/quic/tests/test_quic_hs.c
This PR primarily addresses https://github.com/firedancer-io/firedancer/issues/5248 .  It refactors handle_v1_initial so that we don't allocate a connection too early, where it might need to be torn down anyway due to a decryption failure. It also closes a very low-sev attack vector that is currently open: If client A has an open connection that is still handshaking (server retains the initial enc keys), client B can tear down that connection by sending a malformed initial with the same destination connection ID. 
It also cleans up handle_initial. Should be soaked in mainnet for a while before merging.
=> quic: allocate conn after decrypt in handle_initial

src/app/rpcserver/main.c, src/disco/pack/fd_pack_tile.c, src/disco/shred/fd_shred_tile.c, src/disco/shred/fd_stake_ci.c, src/disco/shred/fd_stake_ci.h, src/disco/shred/test_stake_ci.c, src/discof/poh/fd_poh_tile.c, src/discof/repair/fd_repair_tile.c, src/discof/replay/fd_exec.h, src/discof/rpcserver/fd_rpc_service.c, src/discof/rpcserver/fd_rpc_service.h, src/discof/rpcserver/fd_rpcserv_tile.c, src/discof/send/fd_send_tile.c, src/discoh/poh/fd_poh_tile.c, src/flamenco/leaders/Local.mk, src/flamenco/leaders/fd_leaders.c, src/flamenco/leaders/fd_leaders.h, src/flamenco/leaders/fd_leaders_base.h, src/flamenco/leaders/fd_multi_epoch_leaders.c, src/flamenco/leaders/fd_multi_epoch_leaders.h, src/flamenco/leaders/test_multi_leaders.c, src/flamenco/repair/fd_repair.c, src/flamenco/repair/fd_repair.h, src/flamenco/runtime/context/fd_exec_epoch_ctx.c, src/flamenco/runtime/fd_runtime.c
- Clean up several 'uses' of stake_ci where it's not actually used.
- Implement fd_multi_epoch_leaders_t to handle stake updates and store/query leader schedules for multiple (currently assumed 2) epochs.
- Replace stake_ci with the new multi_epoch_leaders structure in the handful of cases we just care about leader schedule info, and not shred destinations
- minor refactors to use the new fd_stake_weight_msg_t struct to encode/decode stake update headers
To minimize blast radius, shred's fd_stake_ci is left unchanged at the cost of some code duplication, which ideally would be avoided by having stake_ci use the new multi_epoch_leader
Each consumer is modified in a separate commit, for easy reverts if needed. Review best done commit by commit, focusing on …
=> Cleanup stake_ci uses, factor out multi-epoch leader

contrib/offline-replay/offline_replay.toml, src/app/firedancer-dev/commands/backtest.c, src/discof/backtest/fd_backtest_tile.c, src/flamenco/runtime/tests/run_ledger_backtest.sh
Minimally, the replay tile needs to be notified of new roots, in order to advance its watermark and publish various structures.
Also reduce the max number of funk_txn available in backtest config TOMLs. This increases the likelihood of catching failures to publish in the replay tile.
=> backtest, offline-replay: mock tower tile

src/flamenco/leaders/fd_multi_epoch_leaders.c, src/flamenco/leaders/fd_multi_epoch_leaders.h, src/flamenco/leaders/test_multi_leaders.c
This PR modifies multi_epoch_leaders_get_next_slot to search for the next leader slot across epoch boundaries, to better mirror the original behavior of poh_tile.
=> multi_epoch_leaders: get_next_slot check across epochs

src/.clangd
Clangd incorrectly recognized .h files as Objective-C headers.
Fixes that.
=> Fix Clangd linting for C headers

src/app/shared_dev/commands/quic_trace/fd_quic_trace_main.c
This PR fixes quic_trace to access connections using fd_quic_conn_at_idx, rather than stepping directly by the size of the conn.
=> quic-trace - access conn via fd_quic_conn_at_idx

src/app/ledger/main.c, src/discof/exec/fd_exec_tile.c, src/discof/replay/fd_exec.h, src/discof/replay/fd_replay_tile.c, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_executor.h, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/fd_runtime.h, src/flamenco/runtime/fd_runtime_public.h, src/flamenco/runtime/program/Local.mk, src/flamenco/runtime/program/fd_bpf_loader_program.c, src/flamenco/runtime/program/fd_bpf_loader_program.h, src/flamenco/runtime/program/fd_bpf_program_util.c, src/flamenco/runtime/program/fd_bpf_program_util.h, src/flamenco/runtime/program/fd_loader_v4_program.c, src/flamenco/runtime/program/test_program_cache.c, src/flamenco/runtime/tests/fd_dump_pb.c, src/flamenco/runtime/tests/fd_dump_pb.h, src/flamenco/runtime/tests/harness/fd_instr_harness.c, src/flamenco/vm/fd_vm.c, src/flamenco/vm/fd_vm_private.h
This PR is the first of 3, in an effort to make the program cache correct, properly specified, and moved out of Funk:
1. (This PR)  Make the program cache ~~great again~~ by...
a. Getting rid of snapshot full account iteration by lazily populating the program cache as programs are referenced within transactions.
b. Adding support for reverifying programs across epoch boundaries where updated active feature sets may invalidate existing programs.
2. Move program cache updates to happen per transaction instead of at the end of a slot to remove any dependency on funk iteration APIs.
3. Moving the program cache to a new fork-aware data structure similar to but separate from Funk.
=> flamenco, replay: lazy program cache insertion / reverification

src/disco/bundle/fd_bundle_client.c, src/disco/bundle/test_bundle_client.c
If a backend ends the bundle gRPC stream, that's typically an
indication that this backend is done serving requests.  Need to
re-resolve DNS and reconnect in order to reach the new backend
server.
=> bundle: abandon conn if bundle stream ends

src/flamenco/runtime/program/fd_bpf_loader_serialization.c, src/flamenco/runtime/tests/run_backtest_ci.sh, src/flamenco/runtime/tests/run_backtest_tests_all.sh, src/flamenco/vm/fd_vm.h, src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
Also a minor drive-by fix for update_caller_account() in the CPI return edge. Use the correct source for prev_len.
=> flamenco, runtime: set original_data_len for non-DM CPI

src/disco/shred/fd_shred_tile.c
Upgrading unprivileged_init inside the shred tile (deprecated checks).
=> disco: shred tile unprivileged_init update

src/disco/gui/fd_gui.c, src/disco/gui/fd_gui.h, src/disco/gui/fd_gui_printf.c, src/disco/gui/fd_gui_tile.c
waiting for testnet to realive to test this
resolves https://github.com/firedancer-io/auditor-internal/issues/303
agave [diff](https://github.com/firedancer-io/agave/compare/04b8dfe993b358194cf77ccaee1c69aad7dc74fb..jherrera/gui-valinfo-bounds-check)
=> gui: add bounds check to peer messages

src/disco/net/fd_net_common.h, src/disco/net/sock/fd_sock_tile.c, src/disco/net/sock/fd_sock_tile_private.h, src/disco/net/xdp/fd_xdp_tile.c
Problem: full Firedancer currently doesn't work with sock tile.
While I don't love this solution, with this PR at least it works.
=> repair: add net hack also to sock tile

src/app/firedancer/config/default.toml, src/discof/forest/fd_forest.c, src/discof/forest/fd_forest.h, src/discof/forest/test_forest.c, src/discof/repair/fd_fec_chainer.c, src/discof/repair/fd_fec_chainer.h, src/discof/repair/fd_repair_tile.c, src/discof/repair/test_fec_chainer.c
fixest publish edge cases specifically for second incremental loading
=> repair: fix forest and fec chainer publish edge cases

.github/workflows/backtest.yml, contrib/offline-replay/offline_replay.toml, src/app/firedancer-dev/main.c, src/app/firedancer/topology.c, src/app/shared/commands/run/run.c, src/app/shared/fd_config.c, src/app/shared/fd_config.h, src/app/shared_dev/Local.mk, src/app/shared_dev/commands/configure/normalpage.c, src/disco/topo/fd_topo.c, src/disco/topo/fd_topo.h, src/disco/topo/fd_topo_run.c, src/disco/topo/fd_topob.c, src/discof/restore/fd_snapin_tile.c, src/flamenco/runtime/tests/run_backtest_ci.sh, src/flamenco/runtime/tests/run_ledger_backtest.sh, src/funk/test_funk_common.hpp, src/groove/test_groove_data.c, src/groove/test_groove_volume.c, src/util/shmem/fd_shmem.h, src/util/shmem/fd_shmem_admin.c, src/util/shmem/fd_shmem_user.c, src/util/shmem/test_shmem.c, src/util/wksp/fd_wksp.h, src/util/wksp/fd_wksp_helper.c
This PR changes the Funk workspace to use unlocked, unpinned pages that are not required to be resident in physical memory. This enables running large ledgers on machines with smaller memory.
=> topo, funk: change Funk workspace use unlocked pages

.github/actions/hugepages/action.yml, .github/workflows/backtest.yml
Ensures all other hugetlbfs mounts are cleaned up before running CI tests.
=> ci: clean up all hugetlbfs mounts before running CI tests

.github/actions/hugepages/action.yml
We were not reserving enough hugepages for the test vectors CI step.
=> ci: bump hugepages reservation

.github/workflows/backtest.yml, contrib/offline-replay/offline_replay.toml, src/app/firedancer-dev/commands/backtest.c, src/app/firedancer-dev/commands/snapshot_load.c, src/app/firedancer/config/default.toml, src/app/firedancer/topology.c, src/app/firedancer/topology.h, src/app/shared/fd_config.h, src/app/shared/fd_config_parse.c, src/flamenco/runtime/tests/run_backtest_ci.sh, src/flamenco/runtime/tests/run_ledger_backtest.sh, src/flamenco/runtime/tests/run_nightly_backtest.sh
We don't need to use unlocked pages for Funk in a lot of cases, so it makes sense to disable this by default.
=> funk, contrib: use locked pages for funk by default

src/discof/replay/fd_replay_tile.c
this pr probably doesn't solve all of the issues but mostly unblocks us as testnet is able to stay up and and replay through forks
=> replay: patch for replay state machine

src/discof/exec/fd_exec_tile.c, src/discof/replay/fd_replay_tile.c, src/discof/writer/fd_writer_tile.c, src/flamenco/runtime/fd_bank.c, src/flamenco/runtime/fd_bank.h
we need locks in the exec and writer tiles around uses of the bank. This is to avoid the replay tile releasing a bank that is currently being used in the exec and writer tiles. This is not needed in the replay tile because we have an invariant that the current slot that's being executed will not be rooted
=> replay: better locks around banks

src/app/fdctl/topology.c, src/app/firedancer/topology.c, src/disco/gui/fd_gui.c, src/disco/gui/fd_gui.h, src/disco/gui/fd_gui_printf.c, src/disco/gui/fd_gui_printf.h, src/disco/gui/fd_gui_tile.c, src/disco/topo/fd_topo.h
right now the gui gets the validator vote account using on-chain data. Though rare, there might be more than one on-chain vote account associated with a given identity pubkey. the right way to do this is to pass the vote pubkey from the config directly into the gui tile
=> gui: publish vote pubkey

src/app/firedancer/topology.c
currently works because repair uses another object from the slot_fseqs workspace with >= mode, but for consistency and maintainability we should declare this explicitly
=> topo: repair tile uses root_slot_obj

src/app/firedancer-dev/Local.mk, src/app/firedancer-dev/commands/repair.c, src/app/firedancer-dev/main.c, src/app/firedancer/topology.c, src/app/shared/fd_action.h, src/disco/topo/fd_topo.h, src/discof/repair/fd_repair_tile.c, src/discof/replay/fd_exec.h, src/discof/replay/fd_replay_tile.c, src/discof/shredcap/fd_shredcap_tile.c
Adding firedancer-dev command *repair*. This is a standalone application.
The fd_shredcap_tile has been modified to load a snapshot manifest from memory and *publish_stake_weights*.
It is a lighter version of https://github.com/firedancer-io/firedancer/pull/5687.
This PR also includes an upgrade to the replay tile's generate_stake_weight_msg.
=> firedancer-dev: repair profiler light

CODEOWNERS
So that we get a notification when agave submodule changes are made so we're less likely to accidentally not include them on our own changes.
=> add codeowners for agave

src/disco/stem/fd_stem.c
Reverts firedancer-io/firedancer#5904
Seems to be corrupting reliable links. Reverting until I figure it out
=> Revert "disco, stem: ignore halted consumers of reliable links"

src/disco/shred/fd_shred_tile.c, src/discof/poh/fd_poh_tile.c, src/discoh/poh/fd_poh_tile.c, src/flamenco/leaders/fd_leaders.h
Changes:
1. Removed `bank.set_block_id()` in Agave (I previously added it when first built chained merkle shreds)
2. Added block_ids table to shred tile to keep track of leader's block_ids
Tested in lab, running 2 validators both with stake. To simulate skips, we set-identity on one of the 2 validators so that it wouldn't produce slots. We see the correct behavior of the other validator skipping and fetching the parent block id from the new table.
=> shred: keep track of parent block_id when we are leader

src/disco/bundle/test_bundle_client.c
fixes unable to compile with `FD_DISABLE_OPTIMIZATION=1` on gcc 13
=> bundle: fix cast

src/disco/stem/fd_stem.c
This unreverts the revert from #5949
=> disco, stem: check if consumer of reliable tile has shutdown and ignore cr avail result in stem_run loop

src/waltz/quic/fd_quic.c, src/waltz/quic/fd_quic.h, src/waltz/quic/fd_quic_conn.c
+ drive-by fixes: wrong doc, wrong time unit in string, wrong branch hint
=> quic: use correct alignment for stream map

src/ballet/chacha/fd_chacha_rng_avx512.c
_mm_load_epi32 is an AVX-512 extension which GCC 10 doesn't have.
Use _mm_load_si128 instead.
=> chacha: _mm_load_epi32 not portable

src/app/shared_dev/commands/bench/fd_benchs.c, src/discof/send/fd_send_tile.c, src/waltz/quic/fd_quic_stream.c, src/waltz/quic/fd_quic_stream_pool.c, src/waltz/quic/tests/fd_quic_test_helpers.c, src/waltz/quic/tests/fd_quic_test_helpers.h, src/waltz/quic/tests/test_quic_bw.c, src/waltz/quic/tests/test_quic_streams.c
Requires tx_buf_sz for quic streams to be a pow2, so masking works correctly. 
And fixes circular buf OOB bug
found by @two-heart
=> quic: tx_buf_sz pow2

src/discof/rpcserver/fd_rpc_service.c
Fixes an inverse dependency from RPC server to version.h, which
can sometimes fail `make` runs in new checkouts.
=> Fix RPC server build failure

src/flamenco/gossip/fd_gossip_msg_parse.c
Ensures 16-bit addition cannot overflow by checking the sum in a wider type against USHORT_MAX, avoiding incorrect results due to integer promotions.
=> gossip: fix crds parsing overflow check

src/discof/replay/fd_replay_tile.c, src/flamenco/runtime/fd_bank.c, src/flamenco/runtime/fd_bank.h, src/flamenco/runtime/fd_executor.c, src/flamenco/runtime/fd_runtime.c, src/flamenco/runtime/test_bank.c
The replay tile unconditionally publishes upon receiving a new tower root.
This causes premature pruning of minority forks.  Specifically, a bank object
on a minority fork might get pruned before we've finished replaying the block
to which the bank is associated.  This causes a crash every once in a while.
We introduce reference counting to solve this issue.
This commit does not introduce logic for aborting execution of a dead block.
That will be added in a follow-up commit.
=> replay, flamenco: safer publishing

src/app/fdctl/commands/run_agave.c, src/app/fdctl/config/default.toml, src/app/shared/fd_config.h, src/app/shared/fd_config_parse.c
- Adds option to specify a `public_address` which can be useful for proxy/load balancer.
Note:
I believe this flag will be deprecated eventually in the underlying Agave client.
=> Add "--public-rpc-address" option

src/app/firedancer-dev/commands/send_test/send_test.c, src/app/firedancer-dev/commands/send_test/send_test_helpers.c, src/discof/send/fd_send_tile.c, src/discof/send/fd_send_tile.h, src/util/net/fd_ip4.c, src/waltz/quic/fd_quic.h, src/waltz/quic/fd_quic_conn_id.h
This PR fixes host/network order confusion in send, send_test, and corrects some comments in fd_quic. 
It also fixes send_test breaks due to gossip changes.
=> send: fix network ordering

src/flamenco/gossip/fd_gossip_msg_parse.c
otherwise we do oob accesses in handle_net due to uninitialized pointers
=> gossip: fix msg parsing error code propagation

src/flamenco/gossip/crds/fd_crds.c, src/flamenco/gossip/fd_gossip_msg_parse.c, src/flamenco/gossip/fd_gossip_private.h
otherwise we use uninitialized data as a pointer offset
https://github.com/firedancer-io/firedancer/blob/68c60dfb9486c25f5fa00e31956aa22f41e6ef56/src/flamenco/gossip/crds/fd_crds.c#L762-L762
=> gossip: parse token of node instance

src/app/firedancer/config/default.toml, src/app/firedancer/topology.c, src/disco/shred/fd_fec_resolver.c, src/disco/shred/fd_fec_resolver.h, src/disco/shred/fd_shred_tile.c, src/disco/shred/test_fec_resolver.c, src/discof/forest/fd_forest.c, src/discof/forest/fd_forest.h, src/discof/forest/test_forest.c, src/discof/repair/fd_repair_tile.c, src/flamenco/repair/fd_repair.c, src/util/tmpl/fd_map_giant.c, src/util/tmpl/fd_set.c, src/util/tmpl/test_set.c
so many bugs discovered 🐛 🐛  🐛  
🐛  `force_complete` didn't remove from curr_map , but it would release the memory back to freelist, so we could see things in the curr_map that were weird af
🐛  no pool_release in consumed_map in forest (in both publish and in advance_consumed 💀 )
🐛  repair.c inflight table insert doesn't return NULL on no space, and would eventually overwrite the map_private_t fields
🐛  store lock not released in replay
burst value: burst for the tile is already large enough due to the max burst publishing to store in frankendancer path; link burst remains <= 2 bc if an eviction happens that means there is no fec complete msg
=> shred: change fec resolver to not spill to done map

src/discof/send/fd_send_tile.c
In the send tile, handle_contact_info_removal calls conn_close on all open quic connections, and then immediately 0s out the entire entry. But when that connection close eventually triggers the conn_final callback, send screams and dies, unable to find the corresponding conn in the entry to clear. This PR fixes that.
=> send: fix double free

src/discof/restore/fd_snaprd_tile.c, src/flamenco/runtime/tests/run_ledger_backtest.sh
Need this so backtest fails if the snapshot doesn't exist.
=> snapshots: download check

src/app/shared/fd_action.h, src/app/shared_dev/commands/quic_trace/fd_quic_trace.h, src/app/shared_dev/commands/quic_trace/fd_quic_trace_log_tile.c, src/app/shared_dev/commands/quic_trace/fd_quic_trace_main.c, src/app/shared_dev/commands/quic_trace/fd_quic_trace_rx_tile.c, src/discof/send/fd_send_tile.c, src/waltz/quic/fd_quic_pretty_print.c
This PR extends quic_trace for the full client (particularly send_tile). It simplifies the rebasing logic and fixes various quic_trace bugs.
=> quic_trace: full client support

src/flamenco/gossip/crds/fd_crds.c
We otherwise have a dangling entry in our evict treap, which could lead to bad/attackable eviction choices
=> gossip: remove element from eviction treap in fd_crds_acquire

src/app/firedancer/topology.c
Fixes a bug where the `[gossip.host]` config option is ignored
=> gossip: fix NAT support

src/discof/restore/utils/fd_snapshot_parser.h, src/discof/restore/utils/fd_ssmanifest_parser.c
fixes fuzzer asan crash:
```
==2125607==ERROR: AddressSanitizer: invalid alignment requested in aligned_alloc: 128, alignment must be a power of two and the requested size 0xe198 must be a multiple of alignment (thread T0)
```
=> snapshots: fix alignment

src/disco/stem/fd_stem.c
=> metrics, stem: right-size metric_regime_ticks array

book/api/websocket.md, src/app/firedancer/topology.c, src/ballet/shred/test_shred.c, src/disco/gui/Local.mk, src/disco/gui/fd_gui.c, src/disco/gui/fd_gui.h, src/disco/gui/fd_gui_live_table_tmpl.c, src/disco/gui/fd_gui_peers.c, src/disco/gui/fd_gui_peers.h, src/disco/gui/fd_gui_printf.c, src/disco/gui/fd_gui_printf.h, src/disco/gui/fd_gui_tile.c, src/discof/restore/Local.mk, src/discof/restore/fd_snapin_tile.c, src/discof/restore/fd_snaprd_tile.c, src/discof/restore/fd_snaprd_tile.h, src/discof/restore/utils/fd_sshttp.c, src/discoh/poh/fd_poh_tile.c, src/flamenco/gossip/fd_gossip_private.h, src/flamenco/gossip/test_gossip.c, src/util/net/fd_net_headers.h
Adds the following ws messages
- `summary.boot_progress`
- `gossip.network_stats`
- `gossip.query_scroll`
- `gossip.query_sort_col`
- `gossip.peers_size_update`
- `gossip.view_update`
Some fields are still missing support, but they'll be fixed in a future PR
- `gossip.network_stats.health.pull_already_known_pct`  (requires gossvf tile support)
- `gossipo.network_stats.health.total_stake` (requires RPC call at startup)
- `gossipo.network_stats.health.total_staked_peers` (requires RPC call at startup)
- `gossipo.network_stats.health.total_unstaked_peers` (requires RPC call at startup)
driveby nit fix: replaces some uses of compiler intrinsic `__builtin_offsetof` with slightly more cross-compiler compatible `offsetof`
=> gui: new boot screen
