firedancer-io/firedancer

src/util/fd_util_base.h
src/util/test_util_base.c

- Minor polishing of fd_asan.h API
- Polished up FD_INCBIN

Polish incbin API

---

src/util/tmpl/fd_deque_dynamic.c
src/util/tmpl/fd_prq.c
src/util/tmpl/fd_queue_dynamic.c
src/util/tmpl/test_prq.c

Imported from https://git.firedancer.io/c/firedancer/+/407

util: small fixes, make prq work without explicit timeout

---

src/net/quic/crypto/fd_quic_crypto_suites.c
src/net/quic/crypto/fd_quic_crypto_suites.h
src/net/quic/tests/test_checksum.c
src/net/quic/tests/test_tls.c
src/net/quic/tests/test_tls_decrypt.c
src/net/quic/tests/test_tls_pcap2.c
src/net/quic/tests/test_tls_quic_both.c

quic: cleanup

---

src/ballet/ed25519/fd_ed25519.h
src/ballet/txn/BUILD
src/ballet/txn/fd_txn.h
src/ballet/txn/test_txn_parse.c

- ed25519: add fd_ed25519_sig_t
- txn: add fd_txn_get_signatures

txn: add fd_txn_get_signatures

---

src/util/bits/fd_bits.h
src/util/bits/test_bits.c

Adds a simple branchless conditional write

Add store_if to bits

---

.gitignore

git: add vim, vimdiff items to gitignore

---

.github/workflows/make_build.yml
.github/workflows/make_coverage.yml
.github/workflows/make_test.yml

ci: switch to Firecracker runners

---

src/util/alloc/fd_alloc.h
src/util/alloc/test_alloc.c
src/util/rng/fd_rng.h

... and workaround a minor compiler inlining nit found in funky polishing.

Helper function for optimizing dynamic resizing

---

src/funk/Local.mk
src/funk/fd_funk.c
src/funk/fd_funk.h
src/funk/fd_funk_base.h
src/funk/test_funk.c

Extracted as part of the review of Alex's funk store.
This is all the high level funk construction destruction, interfacing with persistent shared memory workspaces and what not.  More layers to come ...

Installed funk object layer

---

deps.sh

add libseccomp to deps.sh

---

deps.sh

This reverts commit #261.
Temporary revert to un-break deps.sh on main

Revert "bring in libseccomp for ci"

---

src/util/shmem/fd_shmem.h
src/util/shmem/fd_shmem_admin.c
src/util/wksp/fd_wksp_helper.c

Support for multi-NUMA node anonymous memory regions

---

config/everything.mk
lint.cfg

Adds a minimal lint config (ie it conforms to the majority of code in the repo already).

lint: add initial lint config

---

src/ballet/sbpf/fd_sbpf_loader.c

Fixes some of the mismatches found by the differential fuzzer
1. `EI_ABIVERSION` check too strict
2. Dynamic symbol table should be discovered via `DT_SYMTAB` instead of `.dynsym` section name

sbpf: fix loader mismatches

---

src/util/fd_util.h
src/util/log/fd_log.c
src/util/log/fd_log.h
src/util/scratch/fd_scratch.c
src/util/scratch/fd_scratch.h
src/util/scratch/test_scratch.c
src/util/tile/fd_tile.h
src/util/tile/fd_tile_nothreads.cxx
src/util/tile/fd_tile_threads.cxx
src/util/tile/test_tile.c

... by popular demand (Josh has his dream of an alloca that can detect if it would overflow the stack).
This also eliminates FD_HAS_X86 requirements for advanced tile stack features.

APIs for run-time stack diagnostics

---

src/vm/Local.mk
src/vm/fd_vm_stack.c
src/vm/fd_vm_stack.h

Adds a minimal stack to support the VM runtime.

vm: add stack for vm

---

src/ballet/sbpf/fd_sbpf_instr.h
src/vm/Local.mk
src/vm/fd_vm_context.c
src/vm/fd_vm_context.h

Add the vm execution context object and several helper functions for said data structure. 
Depends on #361

vm: add vm excecution context object

---

src/vm/Local.mk
src/vm/fd_vm_context.c
src/vm/fd_vm_context.h
src/vm/fd_vm_syscalls.c
src/vm/fd_vm_syscalls.h

adds VM address translation and the prototypes for all the current syscalls. Some syscalls are implemented, many are not.

vm: initial syscalls and address translation

---

src/vm/fd_jump_tab.c
src/vm/fd_jump_tab_teardown.c

Adds the templates which will be used in the jump table used in the VM interpreter

vm: add jump table templates

---

doc/rant/omit-frame-pointer.md

rant: add omit-frame-pointer.md

---

deps.sh

Also speed up checkout_repo function

deps.sh: add bzip2, RocksDB

---

deps.sh

and fix an issue where zstd was being pulled from the wrong place

jsiegel/deps: Make everybody use the same version of gcc

---

src/app/fdctl/src/commands/configure/frank.rs
src/app/frank/Local.mk
src/app/frank/fd_frank.c
src/app/frank/fd_frank.h
src/app/frank/fd_frank_main.c
src/app/frank/fd_frank_mon.bin.c
src/app/frank/fd_frank_pack.c
src/app/frank/fd_frank_verify.c
src/app/frank/load/fd_frank_verify_synth_load.c

pod: correctly pin prefix as 'firedancer'

---

src/ballet/pack/Local.mk
src/ballet/pack/fd_est_tbl.h
src/ballet/pack/test_est_tbl.c

Re-created from #60 to fix authorship

pack: add CU estimation table

---

src/disco/quic/Local.mk
src/disco/quic/fd_quic.h
src/disco/quic/fd_quic_tile.c
src/disco/quic/test_quic_tile.c
src/tango/fd_tango_base.h

- disco: add quic tile
- quic: prevent quic tile from overwriting chunks owned by the verify tile

disco: add quic tile

---

.github/workflows/cargo.yml
Cargo.toml
config/everything.mk
config/linux_clang_x86_64.mk
config/with-ffi.mk
ffi/rust/firedancer-diff/src/lib.rs
ffi/rust/firedancer-sys/build.rs
ffi/rust/firedancer-sys/tests/links_correctly.rs
src/ballet/Local.mk
src/disco/Local.mk
src/tango/Local.mk
src/util/Local.mk

Kind of annoying to get this working end to end at the moment so just disabling it for now, we can revisit if it becomes a problem.

ffi: fix link problems due to thinlto

---

src/tango/quic/crypto/fd_quic_crypto_suites.c
src/tango/quic/crypto/fd_quic_crypto_suites.h
src/tango/quic/fd_quic.c
src/tango/quic/fd_quic.h
src/tango/quic/fd_quic_conn.c
src/tango/quic/fd_quic_conn.h
src/tango/quic/templ/fd_quic_templ.h
src/tango/quic/tests/Local.mk
src/tango/quic/tests/test_quic_retry_integration.c
src/tango/quic/tests/test_quic_retry_unit.c
src/tango/quic/tests/test_quic_server.c

Follow-up to #346: this PR wires the retry packet control flow through both our client and server
Closes https://github.com/firedancer-io/firedancer/issues/257

feat(quic): retry control flow

---

src/app/fdctl/src/commands/configure/ethtool.rs

Consumer grade NICs often don't support setting the number of channels but this is a requirement if we are running with more than one QUIC tile. We add a helpful diagnostic message in this case as it might be quite common when running on development boxes, and also suggest a potential fix for development (running with one QUIC tile).

fdctl: diagnose if nic does not support channels

---

src/app/fdctl/configure/configure.h
src/app/fdctl/configure/workspace.c
src/app/fdctl/configure/xdp.c
src/app/fdctl/run.c
src/app/fdctl/utility.c
src/app/frank/fd_frank_quic.c
src/tango/xdp/fd_xsk.c

fix solana labs being created in the wrong namespace

fix fd_frank_quic (bad syscall and FDs being closed)

---

src/app/fdctl/utility.c
src/app/frank/fd_frank_quic.c
src/app/frank/fd_frank_verify.c

fd_frank_quic requires madvise syscall because of OpenSSL

integrate verify tile from milestone-1.1-demo

---

src/app/fdctl/config.c

We saw on a machine that calling libc `getpwnam` would eventually open `/var/lib/sss/mc/passwd` and then not close it, leaking the file descriptor to later in the process which would flag an error in the sandboxing code that there was an unexpected file open. To prevent such nonsense we just parse `/etc/passwd` ourselves.

fdctl: remove use of getpwnam

---

src/ballet/pack/fd_pack.c
src/ballet/pack/fd_pack.h
src/ballet/pack/test_pack.c

Switches from red-black trees to treaps to use the new merge functionality.
Also plumbs through the `is_simple_vote` flag for use in runtime

ballet/pack: Minor updates

---

.github/workflows/fuzz_artifacts.yml

fix fuzz artifact publication

---

.github/codecov.yml

Change validated by
`curl -X POST --data-binary @codecov.yml https://codecov.io/validate`

coverage: introduce codecov flags

---

config/test.sh

- Fix ShellCheck warnings
- Fix bug that scheduled too many tests on CPU 0
- Support for LLVM coverage

test.sh fixes

---

src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/configure/large_pages.c
src/app/fdctl/configure/workspace.c
src/app/fdctl/monitor/monitor.c
src/app/fdctl/run.c
src/app/fddev/dev1.c
src/app/frank/Local.mk
src/app/frank/fd_frank.h
src/app/frank/fd_frank_forward.c

Adds a new tile which runs and loops without error.

forward tile skeleton

---

.github/workflows/coverage.yml
.github/workflows/make_daily.yml

Result viewable at https://vigilant-carnival-vrqv8pw.pages.github.io/

CI: Merge coverage tasks

---

src/ballet/chacha20/Local.mk
src/ballet/chacha20/fd_chacha20rng.h
src/ballet/chacha20/test_chacha20rng_roll.c

While I'm at it, eliminate provide a non-UINT128 codepath

chacha20: Make roll match Rust rand crate

---

doc/rant/omit-frame-pointer.md

fix typo in omit-frame-pointer.md

---

.github/workflows/publish_fuzz_targets.yml

ci: configure pages on fuzz workflow

---

src/app/fdctl/configure/workspace.c
src/app/frank/fd_frank_pack.c
src/ballet/pack/fd_pack.c
src/ballet/pack/fd_pack.h
src/ballet/pack/test_pack.c

ballet/pack: schedule microblocks specifically for a bank tile

---

src/tango/quic/fd_quic.c

Addresses https://github.com/firedancer-io/auditor-internal/issues/13

added check for null in fd_quic_conn_close

---

src/ballet/bmtree/fd_bmtree.c
src/ballet/bmtree/fd_bmtree.h
src/ballet/bmtree/test_bmtree.c

Take updated version of ballet/bmtree from 1.3 demo branch

Add inclusion proof calculation and verification to bmtree

---

src/tango/quic/fd_quic.c

https://github.com/firedancer-io/auditor-internal/issues/15

DoS in fd_quic_process_quic_packet_v1 #15

---

src/tango/quic/fd_quic.c

https://github.com/firedancer-io/auditor-tj/issues/8

quic - fd_quic_handle_v1_frame return value can be greater than frame_sz

---

src/tango/quic/fd_quic.c

https://github.com/firedancer-io/auditor-internal/issues/3

Integer underflow in fd_quic_conn_tx #3

---

src/tango/quic/fd_quic.c

https://github.com/firedancer-io/auditor-internal/issues/2

Insecure test code in fd_quic_handle_v1_* functions #2

---

src/tango/quic/fd_quic.c

https://github.com/firedancer-io/auditor-internal/issues/1
https://github.com/firedancer-io/auditor-tj/issues/5

fd_quic_frame_handle_stream_frame missing length validation #1

---

src/tango/quic/fd_quic.c

https://github.com/firedancer-io/auditor-internal/issues/10

Underflow in frame_sz calculation

---

src/tango/quic/crypto/fd_quic_crypto_suites.c
src/tango/quic/fd_quic.c
src/tango/quic/fd_quic_proto.h
src/tango/quic/tests/fuzz_quic.c
src/util/tmpl/fd_map_dynamic.c
src/util/tmpl/fd_prq.c

https://github.com/firedancer-io/auditor-internal/issues/12
https://github.com/firedancer-io/auditor-internal/issues/9

addresses fd_quic_crypto_decrypt payload_sz underflow

---

src/app/fdctl/config/default.toml
src/tango/quic/fd_quic.c
src/tango/quic/templ/fd_quic_parsers_decl.h
src/util/fd_util_base.h

https://github.com/firedancer-io/auditor-tj/issues/7

fd_quic_handle_v1_retry does not check return value for fd_quic_decode_retry

---

.github/workflows/scripts/cov_all.sh
config/everything.mk
scripts/script-tests.sh
src/disco/mux/Local.mk
src/tango/test_ipc_init
src/tango/test_ipc_meta

Current coverage is incomplete due to script tests not being exercised. This PR makes CI compute the coverage of script tests.

test: run script tests

---

src/app/fdctl/run/tiles/net.c
src/tango/xdp/fd_xsk.c

xdp: correctly notify driver when needed

---

src/util/simd/fd_avx512_wwi.h
src/util/simd/test_avx512_16x32.c

(Should have been included in PR #778)

Fix wwi_abs specification / implementation

---

.github/actions/deps/action.yml
.github/workflows/codeql.yml
.github/workflows/functional_tests.yml
.github/workflows/test.yml
deps.sh

Created a Solana branch v1.17-fd, on top of Solana v1.17. No major merge issues.

solana: switch to solana labs v1.17

---

config/base.mk
config/native.mk
src/test/single-transaction.sh

We've talked about this change earlier this year. Here it is!

clang as golden compiler

---

src/tango/quic/fd_quic.c

Added more checks, and adjusted the invariant of `cur_pkt_number`
Plus a lot of extra comments.
Hopefully this is now correct.
https://github.com/firedancer-io/auditor-runtimeverification/issues/52

quic - ack range fix - rtv-52

---

src/disco/shred/fd_stake_ci.c
src/util/tmpl/fd_sort.c

Also turns off by default the destination dumps

disco/shred: fix two bugs in fd_stake_ci

---

src/tango/quic/fd_quic.c

We shouldn't run out of acks or streams. If we do we should not crash the app, but terminate the connection.

quic - terminate connections instead of hard crashing

---

book/guide/getting-started.md

book: add hardware requirements

---

config/native.mk

I'm not sure if this was explicitly undesired... in that case please disregard & close.
Tested working on Icelake, and correctly NOT working on Skylake and below.

config: add avx512 to native

---

doc/getting-started.md

restrictiv ➔ restrictive
availabiity ➔ availability

fix some typos in getting-started.md

---

src/app/fdctl/config.c
src/util/net/fd_ip4.h
src/util/net/test_ip4.c

fixes #906 
lmk if anything is in the wrong place (pretty new to this repo) or if any formatting issues 
note that there's some technically non-public ranges that aren't covered here, but this should catch the common cases...

config: error if iface address is not public

---

src/ballet/siphash13/Local.mk
src/ballet/siphash13/fuzz_siphash13.c

In favor of https://github.com/firedancer-io/firedancer/pull/885

fuzz: siphash13

---

src/app/fdctl/run/run.c
src/app/fddev/dev.c

Thanks to Richie for the suggestion.

can't get child exit code without sandbox (2)

---

src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/run/tiles/fd_quic.c
src/app/fdctl/run/tiles/tiles.h
src/app/fdctl/topology.c
src/app/fdctl/topology.h
src/disco/mux/fd_mux.c
src/disco/mux/fd_mux.h
src/disco/quic/Local.mk
src/disco/quic/fd_tpu.h
src/disco/quic/fd_tpu_reasm.c
src/disco/quic/fd_tpu_reasm_private.h
src/disco/quic/test_tpu_reasm.c

- quic: add tpu_reasm class
- quic: integrate tpu_reasm into tile

Add tpu_reasm class

---

src/disco/mux/fd_mux.c

mux: fix bug with not reloading time

---

doc/getting-started.md
doc/rant/integer-types.md
doc/rant/omit-frame-pointer.md

fix: typos

---

src/app/fdctl/run/tiles/fd_pack.c

Increase the number of microblocks per block that we allow the pack tile to produce. Contains a long justification for why this is acceptable.
This requires #974, so for clarity this is set to merge into that branch to show the difference. Once #974 is merged, I'll retarget this to main.

fd_pack: relax microblock per block constraint

---

src/flamenco/leaders/Local.mk
src/util/hist/fd_histf.h

- hist: fix non-x86 support
- leaders: fix non-x86 support
- 
Fixes https://github.com/firedancer-io/firedancer/issues/1004

int128 fixes

---

src/app/fdctl/configure/workspace_leftover.c
src/app/fdctl/fdctl.h
src/app/fdctl/main.c
src/app/fddev/Local.mk
src/app/fddev/configure/kill.c
src/app/fddev/main.c

fddev: kill existing instances for convenience

---

src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/run/run_solana.c

config: add configuration for solana labs poh core

---

src/app/fdctl/run/tiles/fd_shred.c

If we switch forks while we're leader, we may abandon a block and restart the next block on a different fork. Previously, this was causing frankendancer to crash. Now, we just abandon those microblocks. It is kinder to the other validators to signal the block is dead, but the current architecture of the shred tile makes that a bit tricky.
The problem was aggravated by other bugs/issues, but this can happen in rare cases even when the rest of the system is working properly.

fd_shred: Abandon microblocks from abandoned block instead of crashing

---

src/app/fdctl/run/tiles/fd_verify.c

This PR fixes a shortcoming of the pre-dedup cache in the verify tile, by:
1) query if a tx is in the pre-dedup cache; if so, discard
2) verify ed25519 signature; if not verified, discard
3) insert in the pre-dedup cache; if already in, discard
The following describes an attack that was possible before this patch.
An attacker could front run any user and DoS them:
- User wants to send tx_a
- Attacker sees tx_a, sends an invalid tx_b with the same signature of tx_a (the signature doesn't have to validate, the - attacker can simply take tx_a and truncate it)
- Assumption: attacker can send tx_b before user's tx_a
Expected behavior:
- tx_b is invalid so it should be dropped
- tx_a is valid so it should be processed
Current behavior (before PR):
- tx_b sig is added to the dedup tcache
- …

fd_verify: insert verified txs only in pre-dedup tcache

---

src/ballet/pack/Local.mk
src/ballet/pack/fuzz_compute_budget_program_parse.c

Fixes https://github.com/firedancer-io/firedancer/issues/150

Fuzz fd_compute_budget_program_parse

---

src/app/fddev/txn.c

Calls to the new signing API were added to `fd_quic_new_anonymous` in  `fd_quic_test_helpers.c`
`fddev/txn.c`, however, doesn't use `fd_quic_new_anonymous`, so `sign_fn` was not being set, resulting in a segfault

Fix fddev/txn.c (broken during signer changes)

---

src/app/fdctl/fdctl.h
src/app/fdctl/main1.c
src/app/fddev/main.c

config_t config can be too large for the stack
zero initialize args_t args in fddev/main.c

A couple bug fixes

---

src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/run/run.h
src/app/fdctl/run/run1.c
src/app/fdctl/run/run_solana.c
src/app/fdctl/topology.c
src/app/fdctl/topology.h
src/app/fddev/dev.c
src/app/fddev/main.c

fddev: add single process debug mode

---

src/app/fdctl/config.c
src/app/fdctl/run/tiles/fd_net.c
src/app/fdctl/run/tiles/fd_quic.c
src/app/fdctl/run/tiles/fd_shred.c
src/app/fdctl/run/tiles/generated/net_seccomp.h
src/app/fdctl/run/tiles/generated/quic_seccomp.h
src/app/fdctl/run/tiles/generated/shred_seccomp.h
src/app/fdctl/run/tiles/net.seccomppolicy
src/app/fdctl/run/tiles/quic.seccomppolicy
src/app/fdctl/run/tiles/shred.seccomppolicy
src/app/fdctl/topology.h
src/app/fddev/txn.c
src/tango/ip/fd_ip.c
src/tango/ip/fd_ip.h
src/tango/ip/fd_netlink.c
src/tango/ip/fd_netlink.h
src/tango/ip/test_arp.c
src/tango/quic/fd_quic.c
src/tango/quic/fd_quic.h
src/tango/quic/fd_quic_ctl.c
src/tango/quic/tests/fd_quic_test_helpers.c
src/tango/quic/tests/test_quic_client_flood.c
src/tango/quic/tests/test_quic_txn.c
src/tango/quic/tests/test_quic_txns.c

Moves routing and ARP from quic and shred into fd_net
Closes #1125

move routing/arp to fd_net

---

src/waltz/quic/fd_quic.c

Addresses:
https://github.com/firedancer-io/auditor-internal/issues/41

QUIC - added safety check for zero bytes consumed

---

src/util/tmpl/fd_treap.c
src/util/tmpl/test_treap.c

Pack was spending a substantial amount of time iterating through a treap in sorted order.  The complexity of this can be reduced from O(log(n)) to O(1) by threading a linked list through the nodes.  Iterating with this linked list also eliminates hard-to-predict branches and cache misses.  Maintaining this linked list doesn't affect the complexity of the other treap operations, but it does increase the constant factor slightly and the space requirements somewhat significantly (an extra two indices), so I made this optional.

Add option to optimize treap iteration

---

src/app/fdctl/config.c
src/app/fdctl/run/tiles/fd_pack.c
src/app/fdctl/run/tiles/fd_poh.c

Also fixes a deadlock between the poh tile and labs

remove stake_ci from pack

---

src/app/fdctl/run/tiles/fd_poh.c

Rust can call the `fd_ext` functions from random threads with no `FD_TL` variables. In particular, in rare cases, they might try to update metrics, which needs the thread local `fd_metrics_tl`.
There's no good way to intercept the creation of these threads by the Rust code, so the two choices become to defer the metrics until later or to have the Rust thread assume the identity of the PoH tile when they call into any `fd_ext` functions.  Deferring the metrics until the end of the housekeeping loop seemed cleanest.
Although the deferred metrics are written from one thread and read from another, there's the intervening lock release, with the necessary fences, so it won't race (not that it really matters).

fdctl/fd_poh: fix segfault when trying to update metrics from Rust thread

---

src/app/fdctl/run/tiles/fd_poh.c

The current parameters for mainnet lead to a hashcnt duration of 500ns, but this is not the case for certain development networks, or for future mainnet with the update_hashes_per_tick features enabled.

poh: allow fractional hashcnt_duration_ns

---

src/app/fdctl/run/tiles/fd_poh.c

When FD becomes leader after the previous leader skipped a slot, we start forking infinitely.
[2024-02-06T19:19:29.534327843Z INFO  solana_core::replay_stage] new fork:104 parent:99 (leader) root:68 [2024-02-06T19:19:29.928265347Z INFO  solana_core::replay_stage] new fork:105 parent:99 (leader) root:68 [2024-02-06T19:19:30.147370965Z INFO  solana_core::window_service] num addresses: 0, top packets by source: [] [2024-02-06T19:19:30.263528659Z INFO  solana_core::repair::repair_service] repair_stats: [] [2024-02-06T19:19:30.328228537Z INFO  solana_core::replay_stage] new fork:106 parent:99 (leader) root:68 [2024-02-06T19:19:30.728228859Z INFO  solana_core::replay_stage] new fork:107 parent:99 (leader) root:68 [2024-02-06T19:19:31.128223809Z INFO  solana_core::replay_stage] new fork:108 …

poh: fix infinite forking bug

---

src/app/fddev/configure/genesis.c

genesis: ensure RLIMIT_NOFILE is set properly

---

src/app/fdctl/run/tiles/fd_sign.c

sign: check keypair is canonical

---

src/app/fdctl/run/tiles/fd_pack.c

Sorry, I forgot to move this debugging line before I pushed the change that added this code.

fd_pack: remove stray debug logging line

---

src/app/fdctl/configure/hugetlbfs.c

hugetlbfs: clarify ENOMEM error message

---

src/app/fdctl/run/run.c
src/app/fdctl/run/run_solana.c
src/disco/topo/fd_topo_run.c

fdctl: clarify sched_setaffinity error messages

---

src/app/fdctl/run/tiles/fd_sign.c
src/disco/keyguard/fd_keyload.c

sign: prevent stack being dumped

---

src/app/fdctl/Local.mk

build: report firedancer client id and version over gossip

---

src/app/fdctl/run/tiles/fd_verify.c

This reverts commit 015f531dab5d0e64e46e7c5d0d6586684fcb22e2.

Revert "verify: remove dedup from verify"

---

src/app/fdctl/configure/hugetlbfs.c
src/app/fdctl/configure/workspace.c
src/app/fdctl/main1.c
src/disco/topo/fd_topo.c
src/disco/topo/fd_topo.h
src/disco/topo/fd_topob.c

fdctl: use numa aware workspace assignments

---

src/app/fdctl/run/tiles/fd_pack.c

Gaps between leader slots cause pack to fill up and drop verified transactions, so we need to increase our transaction buffer. The heap that pack uses becomes too slow as it gets too large (cache effects plus the Log(n) factor in the heap).
Long term, it would be better if pack had only one form of transaction storage, but that probably requires a fancy probabilistic data structure.
Fixes #1396

fd_pack: add space for handling overflow transactions

---

src/app/fdctl/run/tiles/fd_pack.c

Two small performance tuning changes. First, only use the extra transaction storage when we don't have a leader slot. This will reduce cache thrashing, but means that pack can drop transactions again. Second, switch to using ticks pretty much wherever is possible. Pack was spending 11% of its time in `clock_gettime`, which is not as bad as it sounds, but should still be improved.

fd_pack: performance tuning

---

src/app/fdctl/configure/configure.c
src/app/fdctl/configure/configure.h
src/app/fdctl/configure/hugetlbfs.c
src/app/fdctl/configure/workspace.c
src/app/fdctl/configure/xdp.c
src/app/fddev/configure/genesis.c
src/app/fddev/configure/keys.c
src/app/fddev/configure/netns.c
src/disco/topo/fd_topo.c
src/disco/topo/fd_topo.h
src/util/shmem/fd_shmem.h
src/util/shmem/fd_shmem_admin.c

fdctl: don't zero workspaces in development

---

src/app/fdctl/fdctl.h
src/app/fddev/Local.mk
src/app/fddev/bench.c
src/app/fddev/fddev.h
src/app/fddev/main1.c
src/app/fddev/spammer.c
src/app/fddev/tiles/fd_benchs.c
src/disco/topo/fd_topo.h

spammer: support for standalone benchmarking

---

src/app/fdctl/config.c
src/app/fdctl/config/bench-zen3-32core.toml
src/app/fdctl/config/default.toml
src/app/fdctl/run/tiles/fd_net.c
src/app/fdctl/run/tiles/fd_quic.c
src/app/fdctl/run/tiles/fd_shred.c

topo: remove netmux for cache efficiency

---

src/app/fdctl/Local.mk
src/app/fdctl/fdctl.h
src/app/fdctl/main.c
src/app/fddev/Local.mk
src/app/fddev/configure/blockstore.c
src/app/fddev/configure/genesis.c
src/app/fddev/dev.c
src/app/fddev/genesis_hash.h
src/app/fddev/main1.c
src/disco/keyguard/fd_keyload.c
src/disco/keyguard/fd_keyload.h

fddev: use flamenco to create genesis

---

book/guide/getting-started.md

labs: improve blockstore performance

---

src/app/fddev/configure/blockstore.c

The rocksdb abstraction layers in the Rust code don't make it easy to join all the threads when we're done, so this is an easier fix.

fddev: move blockstore creation to a separate file so rocksdb threads don't affect sandboxing

---

src/disco/mux/fd_mux.c

The flag `FD_MUG_FLAG_COPY` is documented as
>   FD_MUX_FLAG_COPY
The mux tile is not zero copy, meaning it copies frag payloads and
does not simply republishes a pointer to the incoming frag payload
on to downstream consumers.  Because of this, flow control is less
complicated since we no longer need to track the number of
filtered frags in addition to published ones.  If this flag is
set, it means the user promises that all published frags have been
copied and the mux does not need to track filtered ones.
So the logic we should use for computing `cr_max` and returning credits should be slightly adjusted in these cases.

fd_mux: modify flow control for tiles that copy frags

---

src/waltz/ip/Local.mk
src/waltz/ip/fd_ip.c
src/waltz/ip/fd_ip.h
src/waltz/ip/fd_netlink.c
src/waltz/ip/fd_netlink.h
src/waltz/ip/test_routing_load.c

Removed unnecessary logging. Some bugs fixed

ARP - workaround for apparent bug in netlink causing repeated EBUSY.

---

src/app/ledger/main.c
src/disco/tvu/test_runtime.c
src/flamenco/runtime/fd_acc_mgr.c
src/flamenco/runtime/tests/run_ledger_tests.sh

This is uglier than the first fix but whatever...

Second attempt at tpool fix

---

src/app/ledger/main.c
src/disco/tvu/test_runtime.c
src/flamenco/runtime/fd_acc_mgr.c
src/flamenco/runtime/fd_rocksdb.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
src/flamenco/runtime/tests/Local.mk
src/flamenco/runtime/tests/run_ledger_tests.sh
src/flamenco/vm/fd_vm_context.c

1. Program upgrade offset fix
2. Fix for sbpf program validation
3. Ledger test
4. Small validation fix for rocksdb minify
5. Performance fix for runtime checkpointing

bank hash fixes: program upgrade logic

---

src/disco/tvu/fd_tvu.c
src/flamenco/runtime/context/fd_capture_ctx.h
src/flamenco/runtime/context/fd_exec_txn_ctx.h
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_runtime.h
src/flamenco/runtime/program/fd_address_lookup_table_program.c
src/flamenco/runtime/tests/Local.mk

1. adding path option for instruction pb dumper
2. fix for lut freeze 
3. corresponding ledger test

Flamenco: bhm fix for address lut

---

src/app/fdctl/run/tiles/fd_poh.c

Fix the following case:
1. After credit leaves ctx->hashcnt 2 before a tick boundary.
2. We get two microblocks from bank in very quick succession.
3. In the first after_frag, we advance hashcnt by 1 to publish the microblock
4. In the second after_credit, `now` basically hasn't advanced, which means target_hash_cnt gets adjusted to tick-2 again. However, while( ctx->hashcnt<target_hash_cnt ) { is false, so we don't do any hashing in after_credit.
5. In the second after_frag, we publish a microblock on a tick boundary
After hitting several of this type of issue, I also took a deep dive into proving that the current implementation is correct. It's a non-trivial proof, though I feel like I probably overcomplicated it. I also extracted the logic into a test and essentially ran a fuzzer over …

fd_poh: fix corner case that caused bad ticks

---

src/funk/fd_funk_val.c

Kevin found an issue with unaligned fd_alloc calls

Change value alignment to 8 in funky

---

src/flamenco/vm/fd_vm_interp_core.c

Small thing I noticed while proof reading

Fix typo in OP identifier

---

src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
src/flamenco/runtime/tests/Local.mk
src/flamenco/runtime/tests/run_ledger_tests.sh
src/flamenco/vm/fd_vm_syscalls.c

1. CPI check_authorized fix
2. bpf_loader check missing signature fix
3. ledger test

flamenco: bpf loader fixing missing required signature check + cpi check_authorized check fix

---

src/app/fdctl/run/tiles/fd_sign.c
src/disco/keyguard/fd_keyguard.h
src/disco/keyguard/fd_keyguard_match.c

Reverts firedancer-io/firedancer#1675

Revert "tiles: adds remote signing to sign tile for repair and gossip"

---

src/util/wksp/fd_wksp.h

fixed fd_wksp_mprotect comment

---

src/app/fddev/tiles/fd_benchs.c
src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_pkt_meta.h

QUIC - Changes to pack multiple streams into each UDP datagram

---

src/disco/tvu/fd_tvu.c
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/tests/fd_exec_instr_test.c

* Refactor spitting out Protobuf messages
* Fix bugs causing mismatches when creating instruction context

runtime: fix bugs in Protobuf instruction context input / output

---

src/flamenco/runtime/tests/Local.mk
src/flamenco/vm/fd_vm_context.c
src/flamenco/vm/syscall/fd_vm_hashes.c

1. Shouldn't be erroring out on vm_translate on zero length cases
2. Adding FIXME in function to handle within fd_vm_translate_vm_to_host_private

flamenco: handling vm hash zero length case

---

src/flamenco/capture/fd_solcap_diff.c

1. Updating solcap_diff to just tkae in one file to print transaction diffs

flamenco: solcap improvements

---

src/app/fdctl/run/tiles/fd_store_int.c

Adds the store int tile. This was reviewed in lheeger/tile-integ.

tiles: add store_int tile

---

src/flamenco/runtime/tests/run_ledger_tests.sh

This means we can pass `--capture` to `run_ledger_tests.sh`

Propagate solcap argument to fd_ledger

---

src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/program/fd_system_program.h
src/flamenco/runtime/program/fd_system_program_nonce.c
src/flamenco/runtime/tests/Local.mk
src/flamenco/runtime/tests/run_ledger_tests.sh

1. Reimplementing has_nonce check
2. Uncommenting ledger test

flamenco: fixing nonce account check

---

contrib/test/test_firedancer.sh
src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/run/topos/fd_firedancer.c

topo: parse snapshot slot out of snapshot file name

---

src/app/ledger/main.c
src/disco/tvu/fd_tvu.c
src/flamenco/runtime/fd_runtime.h
src/flamenco/runtime/tests/Local.mk
src/flamenco/runtime/tests/run_ledger_tests.sh

adding option that adds separate funk wksp for replay execution

flamenco: add separate funk wksp to runtime replay 

---

src/waltz/xdp/fd_xsk.c

fdctl: error out with helpful message if NIC driver is bad

---

contrib/test/test_firedancer.sh
src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/run/tiles/fd_gossip.c
src/app/fdctl/run/topos/fd_firedancer.c
src/disco/topo/fd_topo.h
src/flamenco/gossip/fd_gossip.c
src/flamenco/gossip/fd_gossip.h

gossip: shred version discovery

---

src/app/fdctl/run/tiles/fd_repair.c
src/disco/consensus/test_consensus.c
src/disco/tvu/fd_tvu.c
src/flamenco/repair/fd_repair.c
src/flamenco/repair/fd_repair.h
src/flamenco/repair/fd_repair_tool.c

repair: make fd_repair bump allocated

---

src/flamenco/runtime/tests/fd_exec_instr_test.c

Solfuzz-agave sets default values for these clock, epoch schedule, and rent sysvars if they are not present in the accounts list. We introduce the same for Firedancer within the fuzz harness context creation.

fuzz, flamenco: Add clock, epoch schedule, and rent default sysvars to fuzz harness

---

src/flamenco/gossip/fd_gossip.c

Tweaked gossip prune message handling to match solana

Fix gossip prune message signature validation

---

src/app/fdctl/config/default.toml
src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_conn.h
src/waltz/quic/fd_quic_private.h

Fixes to RETRY handling
Also, robustness validity checks added

quic - fixed RETRY

---

src/app/fdctl/run/tiles/fd_gossip.c
src/app/fdctl/spy.c
src/disco/consensus/test_consensus.c
src/disco/tvu/fd_tvu.c
src/flamenco/gossip/fd_gossip.c
src/flamenco/gossip/fd_gossip.h
src/flamenco/gossip/fd_gossip_spy.c

gossip: make fd_gossip bump allocated

---

src/app/fdctl/config.c

fdctl: retrieve uid/gid correctly

---

src/flamenco/runtime/program/fd_stake_program.c
src/flamenco/runtime/tests/run_ledger_tests_all.txt

1. Overflow for indexing into deque fixed
2. Adding corresponding ledger test

flamenco: handling overflow case in stake program deqlinquent instruction

---

src/flamenco/runtime/program/fd_vote_program.c
src/flamenco/runtime/tests/run_ledger_tests_all.txt

Incorrect logic in calculation that led to flaky behavior. Rewrite to better match up with agave logic

flamenco: rewrite of vote credit calc

---

src/flamenco/runtime/fd_snapshot_loader.c

Let fd_snapshot_load load full snapshots directly into the current slot transaction (ideally NULL) instead of buffering into a child txn.

snapshot: don't use a funk txn for full snapshots

---

src/flamenco/runtime/tests/fd_exec_instr_test.c

Fix a bunch of memory leaks that occur when running on less RAM. We were never freeing workspace allocations.

fuzz, flamenco: fix workspace memory leaks from failed context creation

---

src/app/fdctl/run/tiles/fd_sign.c

Closes firedancer-io/auditor-internal#78

fix(sign): sz checks for gossip/repair firedancer-io/auditor-internal#78

---

src/flamenco/gossip/fd_gossip.c

Closes firedancer-io/auditor-internal#79

fix(gossip): use the correct buffer size firedancer-io/auditor-internal#79

---

src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_replay_notif.h
src/app/fdctl/run/topos/fd_firedancer.c

flamenco, tiles: added notification pipe to replay to support websockets in rpcserver

---

src/app/fdctl/run/topos/fd_firedancer.c

gossip: use the same gossip listen port value everywhere

---

src/app/fdctl/run/tiles/fd_bank.c
src/app/fdctl/run/tiles/fd_pack.c
src/app/fdctl/run/tiles/fd_poh.c
src/app/fdctl/run/tiles/tiles.h
src/app/fdctl/run/topos/fd_frankendancer.c
src/ballet/pack/fd_pack.h

Fixes #1850
Fixes #1541
Fixes #1386

poh: implement ticks_per_hash feature, fork skip fix

---

src/flamenco/runtime/fd_account.c
src/flamenco/runtime/fd_account_old.h
src/flamenco/runtime/program/fd_bpf_loader_serialization.c
src/flamenco/runtime/program/fd_bpf_loader_v2_program.c
src/flamenco/runtime/tests/run_ledger_tests_all.txt

bpf deserialize fixes + more error checks

flamenco: bpf deserialize fix

---

src/flamenco/runtime/program/fd_stake_program.c

Addresses https://github.com/firedancer-io/auditor-internal/issues/81
The crash needs to be added to https://github.com/firedancer-io/test-vectors/tree/main/instr/fixtures/stake once https://github.com/firedancer-io/solfuzz/pull/31 is done.

flamenco: check all overflows and underflows in stake_weighted_credits_observed

---

src/flamenco/capture/fd_solcap_diff.c
src/flamenco/runtime/context/fd_exec_txn_ctx.c
src/flamenco/runtime/context/fd_exec_txn_ctx.h
src/flamenco/runtime/fd_account.c
src/flamenco/runtime/fd_account.h
src/flamenco/runtime/fd_account_old.h
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_executor.h
src/flamenco/runtime/fd_runtime.h
src/flamenco/runtime/program/fd_bpf_loader_serialization.c
src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
src/flamenco/vm/fd_vm_syscalls.c

We were missing the resize delta check which is a transaction level limit on how much data can be changed.

flamenco: adding resize delta check

---

src/flamenco/runtime/tests/run_ledger_tests_all.txt

```
Deploy: Slot 493
Invoke: Slot 551
Close: Slot 563
```

flamenco: add deploy+close ledger to CI

---

src/app/fdctl/Local.mk

fdctl: fix for not rebuilding solana

---

src/flamenco/runtime/program/fd_bpf_program_util.c

https://github.com/firedancer-io/auditor-internal/issues/90

flamenco: underflow check in bpf program cache update

---

src/choreo/bft/fd_bft.c
src/choreo/bft/fd_bft.h
src/choreo/fd_choreo_base.h
src/choreo/ghost/fd_ghost.c
src/choreo/ghost/fd_ghost.h
src/choreo/ghost/test_ghost.c
src/disco/consensus/test_consensus.c
src/disco/tvu/fd_tvu.c
src/flamenco/runtime/context/fd_exec_slot_ctx.h

This PR refactors the choreo library's bft and ghost modules. It reworks some of the public APIs and simplifies a lot of the implementation.

refactor(choreo): rework bft and ghost apis and impls

---

src/app/ledger/main.c
src/flamenco/runtime/fd_runtime.h

Can now pass in multiple rocksdb as an argument to --rocksdb

ledger: adding multiple rocksdb support

---

src/app/fdctl/Local.mk

fdctl: check solana submodule version

---

book/guide/initializing.md
src/app/fdctl/configure/sysctl.c
src/app/fdctl/main.c
src/app/fdctl/run/run.c

fdctl: fix sysctl configuration

---

src/flamenco/runtime/program/fd_bpf_loader_v3_program.c

https://github.com/firedancer-io/auditor-internal/issues/101

flamenco: fd_bpf_loader_v3_program process_loader_upgradeable_instruction NULL checks

---

book/guide/getting-started.md
src/app/fdctl/config/default.toml
src/app/fdctl/configure/ethtool.c
src/app/fdctl/configure/hugetlbfs.c

fdctl: log steps taken by configure

---

src/flamenco/runtime/program/fd_stake_program.c

https://github.com/firedancer-io/auditor-internal/issues/102

flamenco: fix acceptable_reference_epoch_credits head out of bounds

---

src/flamenco/runtime/fd_executor.c
src/flamenco/vm/fd_vm_syscalls.c

These don't need to be warnings.

flamenco: reduce spurious warning logs

---

src/flamenco/runtime/tests/run_ledger_tests_all.txt
src/flamenco/vm/fd_vm_cpi.h
src/flamenco/vm/fd_vm_syscalls.c

Implementation of the get_last_processed_sibling_instruction syscall.

flamenco, vm: implement get_last_processed_sibling_instruction syscall

---

src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
src/flamenco/runtime/tests/fd_exec_instr_test.c

https://github.com/firedancer-io/auditor-internal/issues/83
https://github.com/firedancer-io/auditor-internal/issues/96

flamenco: fixing loader state read leaks

---

src/app/ledger/main.c

sometimes agave snapshots happen on a slot such that slot + 1 is not rooted. Previously we considered slot + 1 the first start slot. We update to search for up to 32 slots to find the first valid one

ledger: better start slot lookup

---

src/app/ledger/main.c

Reverts firedancer-io/firedancer#2061

Revert "ledger: better start slot lookup"

---

src/app/fdctl/monitor/monitor.c
src/app/fdctl/run/run.c
src/app/fdctl/run/run_solana.c
src/disco/keyguard/Local.mk
src/disco/keyguard/fd_keyload.c
src/disco/keyguard/fd_keyload.h
src/disco/keyguard/test_keyload.c
src/disco/topo/fd_topo_run.c
src/util/sandbox/Local.mk
src/util/sandbox/fd_sandbox.c
src/util/sandbox/fd_sandbox.h
src/util/sandbox/fd_sandbox_private.h
src/util/sandbox/test_sandbox.c

sandbox: harden sandbox further

---

src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/run/run.c
src/app/fdctl/run/run_solana.c

fdctl: get rpc bigtable storage working

---

src/flamenco/runtime/program/fd_native_cpi.c

https://github.com/firedancer-io/auditor-internal/issues/92

flamenco: add parent signer check to native cpi invocations

---

src/flamenco/runtime/program/fd_stake_program.c

https://github.com/firedancer-io/auditor-internal/issues/103
https://github.com/firedancer-io/auditor-internal/issues/104
fixtures https://github.com/firedancer-io/test-vectors/pull/22
https://github.com/firedancer-io/test-vectors/blob/e053a3f2e54fad1efa0aaaa88ad3f68764df8407/instr/fixtures/stake/cd308a27e93b46140f6ee2ade4ef6006257949d4.ctx
https://github.com/firedancer-io/test-vectors/blob/e053a3f2e54fad1efa0aaaa88ad3f68764df8407/instr/fixtures/stake/43dd5f76a94f797f1fd30d309192f41891d0d0ca.ctx

flamenco: correctly cast double to ulong in stake program

---

src/flamenco/runtime/program/fd_bpf_loader_v3_program.c

https://github.com/firedancer-io/auditor-internal/issues/115

fix possible null pointer

---

.github/workflows/on_main_push.yml

When a new commit lands on main, we want to kick solfuzz CI.

`CI`: on_main_push.yml: kick off solfuzz CI

---

src/flamenco/runtime/program/fd_bpf_loader_v3_program.c

https://github.com/firedancer-io/auditor-internal/issues/109
We don't do `fd_ulong_sat_add( SIZE_OF_PROGRAM, programdata_len )` because that value is wrong and [only used for the program cache](https://github.com/anza-xyz/agave/blob/da6f7f2d317ed978701b08c3cc3e8d62756e565a/programs/bpf_loader/src/lib.rs#L146) (which we don't have).
https://github.com/firedancer-io/test-vectors/pull/24

flamenco: fix asan issue with bpf_loader_v3 deploy_program

---

src/app/fdctl/run/tiles/fd_replay.c
src/flamenco/snapshot/fd_snapshot.c
src/flamenco/snapshot/fd_snapshot.h
src/flamenco/snapshot/fd_snapshot_http.c
src/flamenco/snapshot/fd_snapshot_http.h
src/flamenco/snapshot/fd_snapshot_loader.c
src/flamenco/snapshot/fd_snapshot_loader.h
src/flamenco/snapshot/fd_snapshot_main.c
src/flamenco/snapshot/fuzz_snapshot_http.c
src/flamenco/snapshot/test_snapshot_http.c

Fix direct download of snapshots over http

---

src/util/bits/fd_float.h
src/util/bits/test_float.c

- **util: fix whitespace in fd_float**
- **util: add float classify functions**

Float classify 

---

deps.sh

- Fetch submodules
- Add rustup installer
- Install libclang-dev (required by bindgen)
Thank you to SerGo for reporting.

deps.sh: add Frankendancer dependencies

---

src/flamenco/runtime/fd_bank_hash_cmp.c

https://github.com/firedancer-io/auditor-internal/issues/116

flamenco: keep track of bank_hash_cmp->cnt

---

contrib/gdb/README.md
contrib/gdb/fd_gdb.py
contrib/tool/fd_gdb

Closes #2140
Before
```
Breakpoint 1, memset (__len=<optimized out>, __ch=<optimized out>, __dest=<optimized out>) at src/flamenco/snapshot/test_snapshot_restore.c:234
234         ulong sz = fd_bank_slot_deltas_size( cache );
#2  main (argc=<optimized out>, argv=<optimized out>) at src/flamenco/snapshot/test_snapshot_restore.c:232
232         fd_memset(status->key_slice, 2, 20);
$1 = {hash = {hash = '\001' <repeats 32 times>, key = '\001' <repeats 32 times>, ul = {72340172838076673, 72340172838076673, 72340172838076673, 72340172838076673}, ui = {16843009, 16843009, 16843009, 16843009, 16843009, 16843009, 16843009, 16843009}, uc = '\001' <repeats 32 times>}, value = {txn_idx = 2, statuses_len = 1, statuses = 0x7fff80105058}}
```
After
```
Breakpoint 1, memset (__len=<optimized out>, …
```

contrib: add GDB pretty printers for fd_hash_t and fd_signature_t

---

src/flamenco/runtime/program/fd_vote_program.c

getting this in before @ibhatt-jumptrading steps on me

vote_audit: vote audit

---

src/app/fddev/tiles/fd_benchs.c

Moved service ratio code and changed the ratio. This allows multiple transactions to be included in each QUIC packet.
Added in calls to service in additional places, including whenever we have no quic connection. This avoids losing many transactions in the event a connection is closed.
Also removed the DONTWAIT flag from sendmmsg, which seems to have no effect.
This branches off nbridge/quic-ms14-fixes, although there should be no overlap

quic - updates to benchs-quic for stability

---

src/flamenco/capture/fd_solcap_import.c
src/flamenco/capture/fd_solcap_writer_stub.c
src/flamenco/gossip/fd_gossip.c
src/flamenco/gossip/fd_gossip_spy.c
src/flamenco/repair/fd_repair.c
src/flamenco/repair/fd_repair_tool.c
src/flamenco/snapshot/fd_snapshot_http.c
src/flamenco/snapshot/fd_snapshot_loader.c
src/flamenco/vm/fd_vm_tool.c
src/flamenco/vm/test_vm_interp.c

Adds missing headers that are only implicitly imported on Linux

Allow runtime to build on non-Linux

---

src/flamenco/runtime/program/fd_vote_program.c
src/flamenco/runtime/sysvar/fd_sysvar_clock.c
src/flamenco/runtime/sysvar/fd_sysvar_stake_history.c

the pool idx_acquire and ele_acquire don't check to see if there are any free elements and can return random garbage

pool_hardening: harden calls to idx_acquire and ele_acquire 

---

src/waltz/quic/crypto/fd_quic_crypto_suites.c
src/waltz/quic/tests/fd_quic_test_helpers.c
src/waltz/quic/tests/fd_quic_test_helpers.h
src/waltz/quic/tests/test_quic_client_flood.c
src/waltz/quic/tests/test_quic_server.c
src/waltz/quic/tls/fd_quic_tls.c
src/waltz/udpsock/fd_udpsock.c

Allow fd_quic to compile on macOS and FreeBSD

Make fd_quic portable

---

src/ballet/base58/fd_base58_tmpl.c

Closes https://github.com/firedancer-io/auditor-internal/issues/111

base58: fix unaligned access

---

src/app/fdctl/run/tiles/fd_verify.h

Closes https://github.com/firedancer-io/auditor-internal/issues/114

Fix unaligned read in fd_txn_verify

---

src/ballet/pack/fd_compute_budget_program.h

Closes https://github.com/firedancer-io/auditor-internal/issues/110

Fix unaligned read in fd_compute_budget_program_parse

---

src/app/ledger/main.c
src/flamenco/runtime/fd_rocksdb.c

Agave updated how they structure some of their rocksdb keys. Misc fixes to prune

ledger, flamenco: fixing prune and copy txn status

---

.github/workflows/builds.yml
contrib/build.sh
deps.sh

To begin with, I'll run this manually during EOD (each compiler seems to take about ~30 minutes). Eventually, will put this on schedule. Nothing is tied to any PR.
Sample run: https://github.com/firedancer-io/firedancer/actions/runs/9699409537/job/26768295689

build: update workflow file and build matrix script

---

CONTRIBUTING.md

CONTRIBUTING.md: Write out some commonly violated code style rules.

Add some more code style rules

---

src/app/ledger/main.c
src/flamenco/runtime/fd_account.c
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/program/fd_bpf_loader_serialization.c
src/flamenco/runtime/program/fd_bpf_loader_serialization.h
src/flamenco/runtime/tests/run_ledger_tests.sh
src/flamenco/runtime/tests/run_ledger_tests_all.txt

1. Fixing several bpf loader serialization bugs
2. Adding ledger test support for funk archives
3. Adding corresponding ledger test

flamenco: bpf loader serialization fixes

---

contrib/test/instr-fixtures.list

fuzz, runtime: add failing vote fixture

---

src/flamenco/runtime/tests/run_ledger_tests_all.txt

adds test for https://github.com/firedancer-io/firedancer/pull/2286

flamenco: add ledger test for sbpf load error

---

src/flamenco/runtime/program/fd_bpf_loader_v3_program.c

flamenco: correct log message during sbpf_program_load fail

---

src/util/wksp/fd_wksp.h
src/waltz/xdp/Local.mk
src/waltz/xdp/fd_xdp_redirect_user.c
src/waltz/xdp/fd_xsk.c
src/waltz/xdp/test_xsk_rxdrop.c

- **xdp: improve logging**
- **wksp: fix typo**
- **xdp: add test_xsk_rxdrop**

Add test_xsk_rxdrop

---

src/app/ledger/main.c

In practice mainnet ledgers have overlapping slot ranges. This lets you specify when you switch to the next rocksdb

ledger: better multi rocksdb replay

---

src/flamenco/vm/fd_vm_interp_core.c
src/flamenco/vm/instr_test/int_math.instr

vm: fix handling of LE instruction

---

src/waltz/quic/fd_quic.c

If a short packet immediately follows one or more long packets in a single datagram, the short packet is omitted.
This fixes that issue

quic - fixed incorrect handling of short packets immediately following long packets

---

config/extra/with-vlog.mk
src/app/ledger/main.c
src/flamenco/runtime/context/fd_exec_epoch_ctx.c
src/flamenco/runtime/context/fd_exec_epoch_ctx.h
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/program/fd_builtin_programs.c
src/flamenco/runtime/tests/run_ledger_test.sh
src/flamenco/runtime/tests/run_ledger_tests_all.txt
src/flamenco/types/fd_type_names.c
src/flamenco/types/fd_types.c
src/flamenco/types/fd_types.h
src/flamenco/types/fd_types.json
src/flamenco/types/fd_types_custom.c

@yhzhangjump and I added basic v2.0 support for both snapshots and genesis

Various fixes for basic v20 support

---

src/ballet/sbpf/fd_sbpf_loader.c

This change keeps our use of `sh_addr` and `sh_offset` consistent between parsing sections and loading them, rather than relying on the assumption `sh_addr == sh_offset`.
It's worth noting that this is largely a design change, as `sh_addr == sh_offset` holds true for all mainnet programs, and is enforced when deploying programs. So technically the two values can be used interchangeably. This is mostly for consistency.
If implemented, would fix this downstream issue of comparing an `rodata_sz` that was computed using `sh_addr` and asserted against `sh_offset`: https://github.com/firedancer-io/auditor-internal/issues/130

flamenco, ballet: sbpf loader use sh_offset when computing rodata region size

---

src/flamenco/types/Local.mk
src/flamenco/types/fixtures/gossip_pull_req.yml
src/flamenco/types/fixtures/gossip_pull_resp_contact_info.yml
src/flamenco/types/fixtures/gossip_pull_resp_version.yml
src/flamenco/types/fixtures/vote_account.yml

Closes https://github.com/firedancer-io/firedancer/issues/2372

types: fix and re-enable tests

---

src/flamenco/runtime/sysvar/fd_sysvar.c
src/flamenco/runtime/sysvar/fd_sysvar.h

This is unlikely but worth fixing and documenting.

flamenco, sysvar: properly handle the case where sysvar data size changes

---

src/ballet/ed25519/test_ed25519.c

Developed by Atredis during their audit.

expand ed25519 tests

---

src/flamenco/runtime/sysvar/fd_sysvar.c
src/flamenco/runtime/sysvar/fd_sysvar.h
src/flamenco/runtime/sysvar/fd_sysvar_last_restart_slot.c
src/flamenco/runtime/sysvar/fd_sysvar_last_restart_slot.h

Fixes https://github.com/firedancer-io/auditor-internal/issues/139

sysvar: fix updates of 'last restart slot'

---

src/app/fdctl/configure/ethtool.c

Some network drivers advertise a 'max_combined' channel count of 0.
On those, channels are configured by setting the RX and TX channel
count separately.
Observed on tg3 (Broadcom) and gve (Google Cloud).
Closes https://github.com/firedancer-io/firedancer/issues/1427

fdctl: support NICs with split channel count

---

.github/actions/deps/action.yml
.github/actions/submodule/action.yml
.github/workflows/tests.yml

ci: add local cache

---

src/waltz/quic/fd_quic.c

Closes https://github.com/firedancer-io/firedancer/issues/2419

quic: debug mode compile fix

---

src/flamenco/runtime/tests/fd_exec_instr_test.c
src/flamenco/runtime/tests/generated/txn.pb.h
src/flamenco/runtime/tests/generated/vm.pb.h

Fix protobuf following protosol change.
Fix various bugs in the syscall fuzzer harness.

fuzz: various fix for the syscall fuzzer harness

---

src/flamenco/runtime/program/fd_vote_program.c

Work on a line-for-line audit of vote program

flamenco/vote_program audit: switch to agave repo and update a bunch of comments

---

src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_shred.c
src/app/fdctl/run/topos/fd_firedancer.c
src/app/fdctl/run/topos/fd_frankendancer.c
src/ballet/wsample/fd_wsample.c
src/ballet/wsample/fd_wsample.h
src/ballet/wsample/test_wsample.c
src/disco/shred/fd_shred_dest.c
src/disco/shred/fd_shred_dest.h
src/disco/shred/fd_stake_ci.c
src/disco/shred/fd_stake_ci.h
src/disco/shred/test_shred_dest.c
src/disco/shred/test_stake_ci.c
src/flamenco/leaders/fd_leaders.c
src/flamenco/leaders/fd_leaders.h
src/flamenco/leaders/test_leaders.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/stakes/fd_stakes_from_snapshot.c

This is a pretty subtle change, and we need to test it more thoroughly before merging.
The Rust side is also only pushed to a branch at the moment.

fd_stake_ci: degrade gracefully if cluster has >40k staked nodes

---

src/flamenco/runtime/context/fd_exec_slot_ctx.c
src/flamenco/runtime/context/fd_exec_slot_ctx.h
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/program/fd_system_program_nonce.c
src/flamenco/runtime/sysvar/fd_sysvar_fees.c
src/flamenco/runtime/tests/fd_exec_instr_test.c

agave uses the previous lamports per signature for advance nonce fee collection

flamenco: update advance nonce fee collector

---

src/waltz/quic/fd_quic.c

Assumptions in the ack handling code were broken. This fixes that

quic: fix for occasional ack packet not being acked

---

src/app/fdctl/run/tiles/fd_dedup.c

Fixes bug introduced in a0646fbd817fb14064ed5e2716291f85cad51b43

dedup: update mcache size if parsing happened

---

src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/config_parse.c
src/app/fdctl/run/run_solana.c

config: add support for SOLANA_METRICS_CONFIG env var

---

src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/config_parse.c
src/app/fdctl/run/run_solana.c

Closes https://github.com/firedancer-io/firedancer/issues/2475

fdctl: remove disable_wal option

---

src/flamenco/runtime/program/fd_bpf_loader_v3_program.c

ordering of the checks were triggering the fuzzers

bpf_loader_mutable_check: change ordering of checks

---

src/flamenco/vm/syscall/fd_vm_syscall_crypto.c
src/flamenco/vm/syscall/fd_vm_syscall_curve.c
src/flamenco/vm/syscall/fd_vm_syscall_hash.c
src/flamenco/vm/syscall/fd_vm_syscall_pda.c
src/flamenco/vm/syscall/fd_vm_syscall_util.c

fixes https://github.com/firedancer-io/auditor-internal/issues/153

fix register naming: follow syscall calling convention

---

src/flamenco/features/fd_features_generated.c
src/flamenco/features/feature_map.json
src/flamenco/vm/syscall/fd_vm_syscall_curve.c

Same as https://github.com/anza-xyz/agave/commit/3e3b16c0c6c9a2b349ac37c7cf83bc04afca3ffa

syscalls: clean up curve25519 msm length feature gate check

---

src/app/fdctl/run/tiles/fd_dedup.c
src/app/fdctl/run/tiles/fd_verify.c
src/app/fdctl/run/tiles/fd_verify.h
src/app/fdctl/run/tiles/test_verify.c

Fixes https://github.com/firedancer-io/firedancer/issues/990

dedup: use randomized hash

---

src/app/fdctl/configure/hugetlbfs.c
src/app/fddev/main1.c

fddev: better error when uid 0 doesn't have caps

---

src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_enum.h

Reported by ImmuneFi user gln.

quic: drop short UDP packets

---

README.md
book/.vitepress/config.mts
book/api/cli.md
book/api/metrics-generated.md
book/api/metrics-link-preamble.md
book/api/metrics-tile-preamble.md
book/api/metrics.md
book/guide/configuring.md
book/guide/getting-started.md
book/guide/initializing.md
book/snippets/commands/configure-check.ansi
book/snippets/commands/configure-init.ansi
book/snippets/configure.ansi
src/app/fdctl/config/default.toml
src/disco/metrics/gen_metrics.py

docs: tidy up and add metrics page

---

src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_conn_id.h

Closes https://github.com/firedancer-io/firedancer/issues/2492

quic: use fd_rng for conn IDs

---

src/waltz/quic/tests/fuzz_quic_wire.c

Closes https://github.com/firedancer-io/firedancer/issues/2534

Fix net header lengths in fuzz_quic_wire

---

src/waltz/quic/fd_quic.c

fd_rng wasn't being seeded, so each different instance of fd_quic would generate exactly the same sequence of connection ids.
This fixes that by using a secure random source to seed fd_rng.

quic - added code to seed fd_rng for generating unique conn_ids

---

src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/tests/run_ledger_tests_all.txt

set rent epoch to 0 for new sysvars and adding ledger test.
From testnet automation
iredancer-ci-resources/testnet-283927487.tar.gz

flamenco: rent exemption for sysvars

---

src/app/ledger/main.c
src/flamenco/features/fd_features.c
src/flamenco/features/fd_features.h
src/flamenco/runtime/fd_acc_mgr.c
src/flamenco/runtime/fd_account.c
src/flamenco/runtime/fd_account.h
src/flamenco/runtime/program/fd_bpf_loader_serialization.c
src/flamenco/runtime/program/fd_bpf_loader_serialization.h
src/flamenco/runtime/program/fd_bpf_loader_v2_program.c
src/flamenco/runtime/program/fd_bpf_loader_v3_program.c
src/flamenco/runtime/tests/fd_exec_instr_test.c
src/flamenco/runtime/tests/fd_vm_validate_test.c
src/flamenco/runtime/tests/run_ledger_tests_all.txt
src/flamenco/vm/fd_vm.c
src/flamenco/vm/fd_vm.h
src/flamenco/vm/fd_vm_interp_core.c
src/flamenco/vm/fd_vm_private.h
src/flamenco/vm/fd_vm_tool.c
src/flamenco/vm/instr_test/load.instr
src/flamenco/vm/syscall/fd_vm_syscall_cpi.c
src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c
src/flamenco/vm/syscall/fd_vm_syscall_util.c
src/flamenco/vm/syscall/test_vm_syscall_curve.c
src/flamenco/vm/syscall/test_vm_syscalls.c
src/flamenco/vm/test_vm_instr.c
src/flamenco/vm/test_vm_interp.c

flamenco, vm: direct mapping

---

doc/build-system.md

Basic build system documentation I wrote a while ago but forgot to check in.

doc: add build-system.md

---

src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/config_parse.c
src/app/fdctl/run/run_agave.c

support authorized voter keypairs

---

src/flamenco/vm/syscall/fd_vm_syscall_util.c

fixes https://github.com/firedancer-io/auditor-internal/issues/172

fix postinc off-by-one in memcmp syscall

---

src/flamenco/vm/syscall/fd_vm_syscall_util.c

variants the bug described in https://github.com/firedancer-io/auditor-internal/issues/172

fix postinc off-by-one variants in memory syscalls

---

src/flamenco/runtime/fd_runtime.c

The Agave transaction execution API used for transaction fuzzing does not verify signatures, so we should move it out to not be grouped within phase2 so that it can be bypassed easily by the fuzzer.

flamenco: move signature verification out of phase2

---

src/app/fdctl/Local.mk

agave: build agave-ledger-tool

---

contrib/test/instr-fixtures.list
src/flamenco/runtime/program/fd_address_lookup_table_program.c

Fixtures added here: https://github.com/firedancer-io/test-vectors/commit/27e1eaf71de0634458018763567dcafd73dca32b

flamenco: use proper function for deriving PDA

---

src/ballet/http/Local.mk
src/ballet/http/fd_hcache.c
src/ballet/http/fd_hcache.h
src/ballet/http/fd_hcache_private.h
src/ballet/http/fd_http_server.c
src/ballet/http/fd_http_server.h
src/ballet/http/fd_sha1.c
src/ballet/http/fd_sha1.h
src/ballet/http/test_http_server.c
src/ballet/http/test_http_server.py
src/ballet/http/test_sha1.c

http: add http server

---

src/flamenco/runtime/context/fd_exec_txn_ctx.c
src/flamenco/runtime/context/fd_exec_txn_ctx.h
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_executor.h
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/program/fd_native_cpi.c
src/flamenco/runtime/sysvar/fd_sysvar_instructions.c
src/flamenco/runtime/sysvar/fd_sysvar_instructions.h
src/flamenco/runtime/tests/fd_exec_instr_test.c

remove wksp alloc in the txn_setup context and remove pool allocations for fd_instr_info_t

flamenco: tearout instr pool

---

src/app/fdctl/run/run_agave.c
src/app/fdctl/run/tiles/fd_store.c

- re-enable log spam
- fix agave affinity setting
- fix disable blockstore setting

several bug fixes

---

src/flamenco/runtime/program/fd_bpf_loader_serialization.c
src/flamenco/runtime/tests/run_ledger_tests_all.txt
src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c

Missing error check in CPI setup when updating callee account

flamenco: CPI error handling

---

src/flamenco/runtime/tests/fd_exec_instr_test.c

Loads input regions correctly, reflecting write permissions

flamenco, fuzz: (syscall fuzzing) load input data regions correctly

---

contrib/test/instr-fixtures.list
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/program/fd_stake_program.c
src/flamenco/runtime/program/fd_system_program.c
src/flamenco/runtime/program/fd_vote_program.c
src/flamenco/types/fd_types.c
src/flamenco/types/fd_types.h
src/flamenco/types/fd_types.json
src/flamenco/types/gen_stubs.py

Rust bincode deserialize verifies that string types are valid UTF-8 strings.

flameco: add UTF-8 verify for string types

---

src/flamenco/runtime/fd_txncache.c
src/flamenco/runtime/fd_txncache.h

Tested against localnet and testnet

flamenco: add correct ref counted tombstone deletion to txncache

---

src/app/fdctl/run/tiles/fd_replay.c
src/choreo/fd_choreo_base.h
src/choreo/tower/fd_tower.c
src/choreo/tower/fd_tower.h
src/flamenco/runtime/fd_blockstore.c
src/flamenco/runtime/fd_blockstore.h

ignore shreds <= smr
also add and update hcs

fix(replay): change fork-aware structures to publish smr not tower root

---

src/flamenco/vm/syscall/fd_vm_syscall_util.c

fixes https://github.com/firedancer-io/auditor-internal/issues/174

flamenco, vm: better guards for direct mapping

---

src/flamenco/runtime/tests/fd_exec_instr_test.c

In Agave, the Bank's `store_account` function used in the transaction fuzzing harness does not store accounts containing 0 lamports, and when used, returns default accounts with its fields 0-set instead.
Closes [#199](https://github.com/firedancer-io/auditor-internal/issues/199)

fuzz, flamenco: zero-set accounts with 0 lamports when loading them in

---

src/waltz/quic/crypto/fd_quic_crypto_suites.c
src/waltz/quic/crypto/fd_quic_crypto_suites.h
src/waltz/quic/fd_quic.c
src/waltz/quic/tests/fuzz_quic_wire.c
src/waltz/quic/tests/test_quic_crypto.c

- **quic: remove unused suite argument from crypto functions**
- **quic: add crypto benchmark**

Add QUIC crypto benchmark

---

src/app/fdctl/run/tiles/fd_replay.c
src/choreo/forks/fd_forks.c
src/choreo/forks/fd_forks.h
src/choreo/tower/fd_tower.c
src/choreo/tower/fd_tower.h

add documentation for the above
clean up tower apis, forks logic

fix(tower): bug when our latest vote is on different fork than smr

---

contrib/test/run_test_vectors.sh
src/flamenco/runtime/tests/fd_exec_instr_test.c
src/flamenco/runtime/tests/fd_exec_sol_compat.c

* Add support for executing transaction fixtures
* Re-enable precompiles in CI

fuzz, flamenco: support transaction fixture execution

---

src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/tests/fd_exec_instr_test.c

* Added permalinks
* Fixed incorrect return codes
* Added proper error code setting in Protobuf output

fuzz, flamenco: fix fd_executor_txn_check

---

src/flamenco/runtime/tests/fd_exec_instr_test.c

Default sysvar clock account was not being initialized properly in the transaction fuzzing harness

fuzz: sysvar clock account needs to be set in fuzzing harness

---

src/flamenco/runtime/fd_runtime.c

The transaction fuzzing harness in Agave does precompile verification before executing transactions. For convenience of keeping error codes conformant in the transaction fuzzer, I've moved precompile verification to the top of phase2 so if it contains an error, it will fail in the same place as the Agave txn harness. However, we should probably move this logic to be higher up, similar to how Agave does it.

fuzz, flamenco: move precompile verification to top of phase2 tpool

---

src/ballet/sbpf/fd_sbpf_loader.c
src/ballet/sbpf/fd_sbpf_loader.h
src/ballet/sbpf/fuzz_sbpf_loader.c
src/ballet/sbpf/test_sbpf_load_prog.c
src/ballet/sbpf/test_sbpf_loader.c
src/flamenco/runtime/program/fd_bpf_loader_program.c
src/flamenco/runtime/program/fd_bpf_program_util.c
src/flamenco/vm/fd_vm_tool.c
src/flamenco/vm/syscall/fd_vm_syscall_cpi.c
src/flamenco/vm/test_vm_instr.c
src/flamenco/vm/test_vm_util.c
src/flamenco/vm/test_vm_util.h

C _Bool is broken. Context: https://jumptrading.slack.com/archives/C04QN9GNMLL/p1679673294210479

Remove usage of bool from VM

---

src/waltz/quic/tests/Local.mk
src/waltz/quic/tests/test_quic_key_phase.c

Security report made for QUIC key phase changes highlighted a hole in our testing.
This adds `test_quic_key_phase` to test key phase changes.

quic - added key phase test test_quic_key_phase

---

src/flamenco/runtime/tests/fd_exec_instr_test.c
src/flamenco/runtime/tests/fd_exec_instr_test.h
src/flamenco/runtime/tests/fd_exec_sol_compat.c
src/flamenco/runtime/tests/fd_vm_test.c

- Exports the test instruction context create as a function
- Use said function in VM interpreter fuzzer

flamenco, fuzz: feature flag support in vm interpreter fuzzer

---

src/app/rpcserver/fd_methods.c
src/app/rpcserver/main.c
src/ballet/aes/fd_aes_base.h
src/ballet/bn254/fd_bn254_pairing.c
src/ballet/http/test_http_server.c
src/flamenco/runtime/fd_rocksdb.c
src/flamenco/snapshot/fd_snapshot_http.c
src/flamenco/types/fd_types_yaml.c
src/flamenco/types/test_types_archive.c

- Fix incorrect inclusion of malloc.h instead of stdlib.h
- Don't blindly declare inet_aton
- Fix incorrect printf usage in fd_rocksdb.c

Fix minor code quality issues

---

src/waltz/quic/crypto/fd_quic_crypto_suites.c
src/waltz/quic/crypto/fd_quic_crypto_suites.h
src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_conn.h
src/waltz/quic/fd_quic_enum.h
src/waltz/quic/fd_quic_private.h
src/waltz/quic/tests/fuzz_quic_wire.c
src/waltz/quic/tests/test_quic_crypto.c
src/waltz/quic/tests/test_quic_key_phase.c
src/waltz/quic/tests/test_quic_tls_hs.c
src/waltz/quic/tls/fd_quic_tls.c
src/waltz/quic/tls/fd_quic_tls.h
src/waltz/tls/fd_tls.c
src/waltz/tls/fd_tls.h
verification/stubs/fd_quic_crypto.c

- **aes: fix typos**
- **quic: simplify secret handling**
Closes #2570

quic: simplify secret handling

---

src/flamenco/runtime/fd_executor.c

Loaded addresses field is being deprecated as we're now resolving ALUT accounts in the Agave harness

fuzz, flamenco: remove loaded addresses from txn dumping

---

src/flamenco/runtime/tests/generated/txn.pb.c
src/flamenco/runtime/tests/generated/txn.pb.h

Removed `loaded_addresses` field

fuzz: update txn context protobuf generated files

---

src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_executor.h
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/fd_runtime_err.h

not ready for review. opening to check tests

flamenco: add ProgramCacheHitMaxLimit check

---

src/flamenco/vm/syscall/fd_vm_syscall_pda.c

Addresses https://github.com/firedancer-io/auditor-internal/issues/160

flamenco, vm: fix sol_create_program_address correctness issues

---

contrib/test/instr-fixtures/vote.list
src/flamenco/runtime/program/fd_vote_program.c

Start from a freshly initialized vote_state object

vote_init_fix: Vote state fix

---

src/ballet/sbpf/fd_sbpf_loader.c

This reverts commit 3986ea04530309bba98ae168c39a54b0d0af7041.

Revert "ballet: move sh_type check"

---

book/index.md

changed from "borrowed" to draws from experience

update book description reword feature

---

README.md

changed from "borrowed" to draws from experience

Update README description feature

---

src/waltz/quic/fd_quic.c

Implements RFC 9001 'Discarding Unused Keys'

quic: abandon lower encryption levels

---

src/waltz/quic/fd_quic.c

- Fixes gaps in packet numbers when generating packets.
This allows the peer to send more optimized ACK frames.
- Fixes an edge case where a pkt_meta object could get leaked.

quic: fix pkt number gaps and pkt_meta leaks

---

src/flamenco/runtime/fd_account.c

just a duplicated statement, that caused no bug

runtime: remove duplicate self.touch() (nit)

---

src/flamenco/runtime/program/fd_address_lookup_table_program.c
src/flamenco/runtime/program/fd_bpf_loader_program.c
src/flamenco/runtime/program/fd_config_program.c
src/flamenco/runtime/program/fd_stake_program.c
src/flamenco/runtime/program/zksdk/fd_zksdk.c

native programs: add logs

---

src/flamenco/runtime/tests/fd_exec_instr_test.c

Closes https://github.com/firedancer-io/auditor-internal/issues/221

fuzz: set queue ages root in txn fuzz harness

---

src/app/fdctl/run/tiles/fd_shred.c
src/app/fdctl/run/topos/fd_firedancer.c
src/app/fdctl/run/topos/fd_frankendancer.c
src/ballet/shred/fd_shred.c
src/ballet/shred/fd_shred.h
src/ballet/shred/test_shred.c
src/disco/shred/fd_fec_resolver.c
src/disco/shred/fd_fec_resolver.h
src/disco/shred/test_fec_resolver.c
src/disco/topo/fd_topo.h

Partially addresses #2746, but more fuzzing needed.

shred: add extra shred validation

---

config/everything.mk
src/app/rpcserver/Local.mk
src/app/rpcserver/fuzz_json_lex.c
src/ballet/secp256k1/Local.mk

Reported-by: two-heart <seven-master@hotmail.de>

Add back fuzz_json_lex and fuzz_secp256k1_recover

---

src/disco/shred/test_fec_resolver.c

Fix OOB read in test_fec_resolver

---

.gitignore
GNUmakefile
config/base.mk
config/extra/with-libcxx.mk
config/extra/with-lz4.mk
config/extra/with-msan-pre.mk
config/extra/with-msan.mk
config/extra/with-openssl.mk
config/extra/with-rocksdb.mk
config/extra/with-secp256k1.mk
config/extra/with-zstd.mk
deps.sh
doc/testing.md

- **config: make opt directory configurable**
- **deps.sh: add support for MSan**
- **deps.sh: add MSan C++ support (via libc++)**
- **config: add C++ MSan support**
-------
Adds MSan support for C++ and dependencies.
Adds a new `./deps.sh +msan` build mode and improve the `msan` compile extra.

Add full MSan support

---

src/waltz/quic/fd_quic.c

Fixes https://github.com/firedancer-io/auditor-internal/issues/204

Fix incorrect doc comment in fd_quic_process_quic_packet_v1

---

src/ballet/shred/fd_shred.c

fd_shred: harden parsing for new variants

---

contrib/test/instr-fixtures/bpf-loader-v3-programs.list
src/flamenco/runtime/context/fd_exec_txn_ctx.h
src/flamenco/runtime/fd_executor.c

Closes https://github.com/firedancer-io/auditor-internal/issues/223

flamenco: add CPI and instruction stack/trace prechecks

---

contrib/test/setup_fd_only_follower.sh
contrib/test/setup_fd_only_genesis.sh
contrib/test/setup_fd_only_leader.sh
contrib/test/test_firedancer_leader2.sh
contrib/test/tps.py
contrib/tool/txn-gen.py
src/app/fdctl/run/tiles/fd_gossip.c
src/app/fdctl/run/tiles/fd_repair.c
src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_store_int.c
src/app/fdctl/run/topos/fd_firedancer.c
src/ballet/http/fd_http_server.c
src/disco/poh/fd_poh_tile.c
src/disco/store/fd_store.c
src/disco/topo/fd_topo.h
src/flamenco/gossip/fd_gossip.c
src/flamenco/repair/fd_repair.c
src/flamenco/runtime/Local.mk
src/flamenco/runtime/context/fd_exec_slot_ctx.h
src/flamenco/runtime/fd_acc_mgr.c
src/flamenco/runtime/fd_blockstore.c
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/fd_readwrite_lock.h
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/fd_runtime.h
src/flamenco/runtime/program/fd_bpf_loader_program.c
src/flamenco/runtime/tests/fd_exec_instr_test.c
src/funk/fd_funk.c
src/util/tile/fd_tile_threads.cxx

Improves performance across the entirety of Firedancer's runtime and replay sections. Adds some new scripts used for the demos.

firedancer: performance demo improvements

---

contrib/test/test_firedancer_leader.sh
src/app/fdctl/config.c
src/app/fdctl/run/run.c
src/app/fdctl/run/tiles/fd_repair.c
src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_store_int.c
src/app/fdctl/run/topos/fd_firedancer.c
src/app/ledger/main.c
src/app/shredcap/main.c
src/disco/topo/fd_topob.c
src/disco/topo/fd_topob.h
src/flamenco/runtime/fd_blockstore.c
src/flamenco/runtime/fd_blockstore.h

- **fdctl: remove concrete objects**
- **contrib: fix configuration of firedancer localnet script**

fdctl: remove concrete objects

---

src/choreo/tower/Local.mk

added missing conditional flag discussed in #3065

secp256k1 conditional compilation flag for test_tower

---

src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c

adds bottom part of https://github.com/firedancer-io/firedancer/pull/3062

flamenco: remove lamport checks in CPI

---

src/app/fdctl/run/tiles/fd_gossip.c

Since we don't need nanosecond precision for gossip pushes, we can reduce frequency of calls to `fd_log_wallclock()` in gossip tile by moving it to the `during_housekeeping()` callback.

gossip: wallclock update in during_housekeeping

---

src/flamenco/runtime/program/fd_bpf_loader_program.c
src/flamenco/vm/fd_vm.h

Addresses https://github.com/firedancer-io/auditor-internal/issues/225

flamenco, runtime: handle failure to setup vm in bpf loader

---

src/waltz/quic/fd_quic.c

These are technically unreachable bugs on current main, but should
be fixed regardless.
- Fixes an issue where streams can exist in both the connection
stream list and the free pool, if the stream hashmap is full
- Fixes two bugs relating to 'fire and forget' frames (those are
frames that don't set flags in pkt_meta).  If an outgoing packet
consists exclusively of such frames, the correct behavior is to
not allocate a pkt_meta record.  The bugs are:
- 'Fire and forget' packets are dropped instead of sent
- 'Fire and forget' packets leak pkt_meta, eventually bricking
the fd_quic instance

quic: logic improvements

---

src/app/fdctl/run/tiles/fd_pack.c
src/ballet/pack/fd_pack.c
src/ballet/pack/fd_pack.h

I confirmed this still can handle 1M TPS

pack: pace CUs through block

---

src/app/fdctl/run/tiles/fd_pack.c
src/ballet/pack/fd_pack.c
src/ballet/pack/fd_pack.h

This reverts commit c7744e337c87437beb32177c5fcbd740b415eed2.

Revert "pack: pace CUs through block"

---

src/util/net/fd_pcapng.c
src/util/net/fd_pcapng.h
src/util/net/test_pcapng.c

Simplifies error handling in the fd_pcapng public API

Switch fd_pcapng to fd_io-compatible error codes

---

src/waltz/quic/tests/fd_quic_test_helpers.c
src/waltz/quic/tests/fd_quic_test_helpers.h
src/waltz/quic/tests/test_quic_bw.c
src/waltz/quic/tests/test_quic_drops.c

- **quic: move loss/reorder simulator to fd_quic_netem_t**
- **quic: add netem support to test_quic_bw**

Add netem support to test_quic_bw

---

src/flamenco/runtime/fd_runtime.c

Fixes a mismatch on ledger devnet-335622435 where we hashed a rent recipient account that shouldn't have been due to the account being owned by a non-system program.

flamenco: mark rent recipient accts dirty only if all checks pass

---

contrib/quic/agave_compat/Cargo.toml
src/waltz/quic/fd_quic.c

- Improve MAX_DATA frame handler
- Update agave_compat test dependencies

quic: minor improvements

---

src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_private.h

Remove unused fd_quic_pkt->ping flag

quic: fix nits in ping handler

---

src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_private.h

Closes https://github.com/firedancer-io/firedancer/issues/256

quic: fix FD_QUIC_DISABLE_CRYPTO

---

src/waltz/quic/tests/test_quic_bw.c
src/waltz/quic/tests/test_quic_concurrency.c

Improve logging of QUIC single-conn and multi-conn benchmarks

quic: improve test_quic_{bw,concurrency}

---

src/waltz/quic/fd_quic_conn_map.h

quic: reduce conn_map size

---

src/app/fdctl/config.c
src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/config_parse.c
src/app/fdctl/run/tiles/fd_net.c
src/app/fdctl/run/topos/fd_firedancer.c
src/app/fdctl/run/topos/fd_frankendancer.c
src/disco/topo/fd_topo.h

Required for some specific configurations

net - add support for additional ip addresses

---

src/app/fdctl/config.h
src/app/fdctl/config/default.toml
src/app/fdctl/config_parse.c
src/app/fdctl/run/tiles/fd_quic.c
src/app/fdctl/run/topos/fd_firedancer.c
src/app/fdctl/run/topos/fd_frankendancer.c
src/app/fddev/tiles/fd_benchs.c
src/disco/topo/fd_topo.h
src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic.h
src/waltz/quic/fd_quic_conn.c
src/waltz/quic/fd_quic_conn.h
src/waltz/quic/fd_quic_private.h
src/waltz/quic/tests/Local.mk
src/waltz/quic/tests/fd_quic_sandbox.c
src/waltz/quic/tests/fd_quic_test_helpers.c
src/waltz/quic/tests/test_quic_concurrency.c
src/waltz/quic/tests/test_quic_conformance.c
src/waltz/quic/tests/test_quic_conn.c
src/waltz/quic/tests/test_quic_drops.c
src/waltz/quic/tests/test_quic_hs.c
src/waltz/quic/tests/test_quic_key_phase.c
src/waltz/quic/tests/test_quic_retry_integration.c
src/waltz/quic/tests/test_quic_streams.c

Greatly improves performance at high conn counts.

quic: rewrite service queue

---

src/app/fdctl/run/run.c
src/app/fdctl/run/tiles/fd_net.c
src/app/fdctl/run/tiles/fd_quic.c
src/app/fdctl/run/tiles/fd_shred.c
src/app/fdctl/run/topos/fd_firedancer.c
src/app/fdctl/run/topos/fd_frankendancer.c
src/app/fddev/bench.c
src/app/fddev/dev.c
src/app/fddev/load.c
src/disco/topo/fd_topo.h
src/disco/topo/fd_topo_run.c
src/waltz/xdp/Local.mk
src/waltz/xdp/fd_xdp1.c
src/waltz/xdp/fd_xdp1.h

Closes https://github.com/firedancer-io/firedancer/issues/2205

net: allow multiple net tiles

---

src/flamenco/vm/fd_vm_private.h
src/flamenco/vm/syscall/fd_vm_syscall_cpi.c
src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c

Out-of-order preflight checks in CPI is proving to be a constant source of false positive error code mismatches during fuzzing.  With this change, we will be doing these checks in-flight, similar to how agave does things.  There's also two minor issues with the preflight checks that this commit fixes.  One being that we returned MAX_INSTRUCTION_ACCOUNT_INFOS_EXCEEDED in a place where it should have been TOO_MANY_ACCOUNTS.  The other being that a comparison against INT_MAX was more restrictive than Agave's LONG_MAX.
This PR intentionally does not include a new fixture that exposed preflight induced error code mismatches, because this PR does not make that fixture completely pass.  We will include the fixture in a separate PR that fixes another issue unrelated to preflight that has been …

flamenco: refactor CPI out-of-order preflight checks to in-order

---

src/app/fdctl/run/tiles/fd_pack.c

Extra storage has been a pain for us since the start. We're leaning towards just bigger treaps now. Is keeping it behind a `#define` the right choice, or should we delete it entirely?

pack: disable extra transaction storage by default

---

src/flamenco/vm/fd_vm_interp_core.c

Drive-by fixes of wide shift semantics in the interpreter.

flamenco, vm: correct wide shift semantics in interpreter

---

src/app/fdctl/run/tiles/fd_net.c

Closes https://github.com/firedancer-io/firedancer/issues/3288

Fix net_tile_tx_dropped metric

---

src/flamenco/vm/syscall/fd_vm_syscall_runtime.c

syscall, vm: handle UB when memcpying 0 bytes

---

contrib/test/test-vectors-fixtures/instr-fixtures/system.list
src/flamenco/runtime/program/fd_system_program.c

The signature check should happen before the lamport check

system_transfer_seed: transfer_with_seed consensus failure

---

src/flamenco/runtime/program/fd_system_program.c

No reason to add a test since I added a test in a previous PR that covers this case as well.

system_cleaned_feature: this feature was cleaned up and incorrectly feature gated initially

---

src/disco/topo/fd_pod_format.h

add more format attributes

---

src/util/tmpl/fd_pool.c
src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_private.h
src/waltz/quic/tests/test_quic_conformance.c
src/waltz/quic/tests/test_quic_conn.c
src/waltz/quic/tests/test_quic_tls_hs.c
src/waltz/quic/tls/fd_quic_tls.c
src/waltz/quic/tls/fd_quic_tls.h

- **Fix error messages in fd_pool.c**
- **quic: rewrite handshake pool using fd_pool**
Closes https://github.com/firedancer-io/firedancer/issues/3347

quic: rewrite handshake pool using fd_pool

---

src/app/fdctl/config.h
src/app/fdctl/config_parse.c
src/app/fdctl/run/tiles/fd_gossip.c
src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_store_int.c
src/app/fdctl/run/topos/fd_firedancer.c
src/disco/restart/Local.mk
src/disco/restart/fd_restart.c
src/disco/restart/fd_restart.h
src/disco/topo/fd_topo.h
src/flamenco/gossip/fd_gossip.c
src/flamenco/types/fd_type_names.c
src/flamenco/types/fd_types.c
src/flamenco/types/fd_types.h
src/flamenco/types/fd_types.json

This PR contains the initial version of the wen-restart control flow.

Start to implement wen-restart

---

src/waltz/quic/fd_quic.c

QUIC was sending max_data frames unnecessarily. This fixes that, and also fixes a case whereby rx_max_data could go beyond the max allowed.

quic - do not automatically increase max_data. Limit max_data to max varint

---

src/tango/fd_tango_base.h
src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic_private.h
src/waltz/quic/fd_quic_retry.h
src/waltz/quic/fd_quic_stream.h
src/waltz/quic/templ/fd_quic_templ.h
src/waltz/tls/fd_tls_estate.h
src/waltz/tls/test_tls.c

Some stylistic improvements I found while auditing QUIC.

quic: nits

---

src/flamenco/features/fd_features_generated.c
src/flamenco/features/fd_features_generated.h
src/flamenco/features/feature_map.json
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/vm/syscall/fd_vm_syscall_cpi.c

feature was added in https://github.com/anza-xyz/agave/pull/3152

add enable_secp256r1_precompile feature

---

src/app/fdctl/caps.h
src/app/fdctl/config.c
src/app/fdctl/configure/configure.c
src/app/fdctl/configure/ethtool-channels.c
src/app/fdctl/configure/ethtool-gro.c
src/app/fdctl/fuzz_fdctl_config.c
src/app/fdctl/main1.c
src/app/fdctl/monitor/helper.c
src/app/fdctl/monitor/monitor.c
src/app/fdctl/run/run.c
src/app/fdctl/spy.c
src/app/fdctl/utility.c
src/app/fdctl/utility.h
src/app/fddev/bench.c
src/app/fddev/configure/genesis.c
src/app/fddev/dev.c
src/app/fddev/flame.c
src/app/fddev/load.c
src/app/fddev/tiles/fd_benchg.c
src/app/fddev/tiles/fd_bencho.c
src/app/fddev/tiles/fd_benchs.c
src/disco/topo/fd_topo.c
src/disco/topo/fd_topo_run.c

Also remove circular dependencies

fdctl: optimize imports

---

contrib/codegen/gen_map_perfect.py
src/ballet/pack/fd_pack.c
src/ballet/pack/fd_pack_tip_prog_blacklist.h
src/ballet/pack/test_pack.c

The other tables were updated here: https://github.com/firedancer-io/firedancer/pull/3398

secp256r1: add to fd_pack_unwritable

---

.github/workflows/on_nightly.yml

nightly: remove ledger-replay

---

src/app/fddev/flame.c

perf record has an issue where if too many processes or threads are being collected, it works if you output to a file, but doesn't work if you stream the output to a pipe.  This is due to it using a different format internally when going to a pipe which has smaller limits.
To fix this, we switch it to use a file ... ideally you would use a tempfile here, but this also doesn't work, as
`perf script -i <file> report` doesn't seem to work with the flamegraph command.  We just leave it to use the default perf.data file.

fddev: fix flame command

---

contrib/tango.lua

The file was previously using tabs, so I also adjusted that, which is why the diff is so big.

contrib: update tango lua parser

---

src/disco/stem/fd_stem.c
src/disco/stem/fd_stem.h

- Add feature guards
- Allow multiple stems in one compile unit
- Clean up defines

stem: belt sanding

---

src/waltz/aio/Local.mk
src/waltz/aio/fd_aio_pcapng.c
src/waltz/aio/fd_aio_tango.c
src/waltz/aio/fd_aio_tango.h

- **Add fd_aio_tango_tx API**
- **Add fd_aio_tango_rx**

aio<>tango translation library

---

src/app/fdctl/run/tiles/fd_quic_tile.c

clock_gettime consumes significant CPU time.
This patch hacks together an RDTSC based replacement.

quic: crude clock_gettime replacement

---

contrib/tango.lua
src/app/fddev/dump.c

Useful to detect bugs in fd_quic_tile

fddev: support quic->verify link dumps

---

contrib/test/test-vectors-fixtures/txn-fixtures/program-tests.list
src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c

prepare instruction wasnt propogating insn error code, now it is

flamenco: cpi error code propogation

---

src/flamenco/gossip/fd_gossip.c

We incorrectly only pushed the CRDS data, not the full value. This causes (among other things) push to break since it forwards values without signature encoded.

flamenco, gossip: insert full crds value into value table on recv_crds

---

src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_rpcserv.c
src/app/fdctl/run/topos/fd_firedancer.c
src/app/ledger/main.c
src/disco/topo/fd_topo.h
src/funk/fd_funk.c
src/funk/fd_funk.h
src/funk/fd_funk_base.h
src/funk/fd_funk_filemap.c
src/funk/fd_funk_part.c
src/funk/fd_funk_rec.h
src/funk/fd_funk_txn.c
src/funk/fd_funk_txn.h
src/funk/fd_funk_val.h

Some minor nits and fixes noticed during reading replay and funk code.

replay: nits

---

src/ballet/sbpf/fd_sbpf_loader.c
src/ballet/sbpf/fd_sbpf_loader.h
src/ballet/sbpf/fuzz_sbpf_loader.c
src/ballet/sbpf/test_sbpf_elf_peek.c
src/ballet/sbpf/test_sbpf_load_prog.c
src/ballet/sbpf/test_sbpf_loader.c
src/flamenco/features/fd_features_generated.c
src/flamenco/features/fd_features_generated.h
src/flamenco/features/feature_map.json
src/flamenco/runtime/program/fd_bpf_loader_program.c
src/flamenco/runtime/program/fd_bpf_program_util.c
src/flamenco/runtime/program/fd_bpf_program_util.h
src/flamenco/runtime/tests/fd_exec_instr_test.c
src/flamenco/vm/fd_vm_tool.c

https://github.com/anza-xyz/agave/pull/3830

vm v2: add feature gates

---

src/flamenco/runtime/fd_borrowed_account.c
src/flamenco/runtime/fd_borrowed_account.h
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/tests/Local.mk

Fixes mismatch on ledger devnet-340941576

flamenco: make a read-only account copy for executable bit flips

---

config/base.mk
contrib/test/test-vectors-fixtures/vm-interp-fixtures/vm_interp-fixtures.list
src/flamenco/runtime/tests/fd_exec_instr_test.c
src/flamenco/runtime/tests/fd_vm_test.c
src/flamenco/runtime/tests/generated/pack.pb.h
src/flamenco/runtime/tests/generated/vm.pb.c
src/flamenco/runtime/tests/generated/vm.pb.h
src/flamenco/vm/fd_vm_interp_core.c
src/flamenco/vm/fd_vm_private.h

This includes https://github.com/firedancer-io/firedancer/pull/3528

vm: interp test + bugfix segfault

---

config/extra/with-fuzz.mk

We want as many checks as we can during fuzzing.

fuzz: enable all handholding

---

src/flamenco/repair/fd_repair.c

#2769 tweaked time durations, but didn't update comments

repair: fix duration comments

---

src/ballet/reedsol/fd_reedsol_pi.c
src/util/simd/Local.mk
src/util/simd/fd_avx.h
src/util/simd/fd_avx_wh.h
src/util/simd/fd_avx_ws.h
src/util/simd/test_avx_16x16.c
src/util/simd/test_avx_common.c

Add AVX ushort wrappers for ops load, store, extract, insert, neg,
abs, min, max, add, sub, mul, eq, and ne.

Add fd_avx_wh.h (16x ushort)

---

src/app/ledger/main.c

When replaying large ledgers, we need to evict old blocks from the blockstore.

app, ledger: remove previous block from blockstore

---

src/flamenco/runtime/tests/fd_pack_test.c

Upstream PRs:
- https://github.com/firedancer-io/protosol/pull/30

flamenco, fuzz: add heap_sz and loaded_acct_data_sz to pack cbp

---

contrib/codeql/BincodeCrdsValue.ql

catch bugs like the one fixed in #3568
Credits the query idea: @ravyu-jump

codeql: add fd_value_elem data encoding check

---

src/app/ledger/Local.mk
src/app/rpcserver/Local.mk
src/choreo/eqvoc/fd_eqvoc.c
src/choreo/tower/fd_tower.c
src/disco/geyser/Local.mk
src/disco/gui/fd_gui.c
src/flamenco/capture/Local.mk
src/flamenco/rewards/fd_rewards.c
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_executor.h
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/program/fd_bpf_loader_program.c
src/flamenco/runtime/program/fd_bpf_loader_serialization.c
src/flamenco/runtime/program/fd_builtin_programs.c
src/flamenco/runtime/program/fd_vote_program.c
src/flamenco/runtime/sysvar/fd_sysvar_slot_hashes.c
src/flamenco/runtime/sysvar/fd_sysvar_slot_history.c
src/flamenco/runtime/sysvar/fd_sysvar_stake_history.c
src/flamenco/runtime/tests/fd_exec_instr_test.c
src/flamenco/runtime/tests/fd_vm_test.c
src/flamenco/runtime/tests/fd_vm_test.h
src/flamenco/shredcap/fd_shredcap.c
src/waltz/quic/tests/fd_quic_test_helpers.c
src/waltz/xdp/fd_xdp_redirect_user.c

Fixes instances of publicly exported symbols without the 'fd_' prefix.

Fix symbol pollution

---

src/app/fdctl/run/tiles/fd_pack.c
src/ballet/pack/fd_pack_pacing.h

> We want to use as few banks as possible to fill the block in 400
milliseconds.  That way we pass up the best transaction because it
conflicts with something actively running as infrequently as
possible.  To do that, we draw lines through in the time-CU plane
that pass through (400 milliseconds, 48M CUs) with slope k*(single
bank speed), where k varies between 1 and the number of bank tiles
configured.  This splits the plane into several regions, and the
region we are in tells us how many bank tiles to use.

pack: change model for pacing CUs

---

contrib/offline-replay/offline_replay_network_parameters.sh

```
[agave]$ target/release/solana cluster-version -um
2.0.18
[agave]$ target/release/solana cluster-version -ut
2.1.1
[agave]$ target/release/solana cluster-version -ud
2.0.15
```

offline-replay: update cluster-versions

---

src/app/fddev/dev.c

fix: fddev monitor tries to join shmem without init

---

src/app/fdctl/run/tiles/fd_gossip.c

Addresses: https://github.com/firedancer-io/auditor-internal/issues/255

tile, gossip: check that incoming vote txns are single instruction

---

deps.sh

MOREFLAGS was removed in favour of CFLAGS

deps: update lz4 flags

---

src/app/fdctl/run/tiles/fd_shred.c

Ensure the last batch generates >= 32 data shreds by padding with 0s.
This is important for https://github.com/anza-xyz/feature-gate-tracker/issues/19 otherwise our blocks won't get voted on

feat(shredder): always pad last FEC set to 32 data shreds

---

src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/program/fd_bpf_program_util.c

checking for tombstones when iterating through funk

---

.github/workflows/builds.yml
.github/workflows/on_nightly.yml
contrib/build.sh

build: features for adding exceptions

---

src/util/sanitize/fd_msan.h
src/util/scratch/fd_scratch.h

new scratch memory should be treated as uninitalized memory, and reads into popped or otherwise "freed" memory is not allowed

scratch msan poisoning

---

src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_store_int.c
src/choreo/forks/fd_forks.c
src/disco/store/fd_store.c
src/flamenco/runtime/fd_blockstore.c
src/flamenco/runtime/fd_blockstore.h
src/flamenco/runtime/fd_rocksdb.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/shredcap/fd_shredcap.c

Reverts firedancer-io/firedancer#3734

Revert "blockstore: fix and document locking"

---

contrib/test/run_test_vectors.sh

vm: temp disable interp tests

---

contrib/test/test-vectors-fixtures/vm-interp-fixtures/vm_interp-fixtures.list
src/flamenco/vm/syscall/fd_vm_syscall.c

2 tests, one was actually a bug in solfuzz-agave: https://github.com/firedancer-io/solfuzz-agave/pull/204

vm: fix double negative for feature disable_fees_sysvar

---

src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/fd_runtime.h

#3829 depends on this to pass ledger per-stake-history-new-rate-activation-epoch

flamenco: fix hashes_per_tick feature activation

---

src/ballet/bn254/fd_bn254.c
src/ballet/bn254/fd_bn254.h
src/ballet/bn254/test_bn254.c
src/flamenco/features/fd_features_generated.c
src/flamenco/features/fd_features_generated.h
src/flamenco/features/feature_map.json
src/flamenco/vm/syscall/fd_vm_syscall_crypto.c

https://github.com/anza-xyz/agave/pull/3686

bn254: fix check input sz for mul

---

src/app/fdctl/run/tiles/fd_replay.c
src/app/ledger/main.c
src/disco/consensus/test_consensus.c
src/flamenco/snapshot/fd_snapshot.c
src/flamenco/snapshot/fd_snapshot.h
src/flamenco/snapshot/fd_snapshot_http.h
src/flamenco/snapshot/fd_snapshot_istream.c
src/flamenco/snapshot/fd_snapshot_loader.c
src/flamenco/snapshot/fd_snapshot_loader.h
src/flamenco/snapshot/fd_snapshot_restore.c
src/flamenco/snapshot/fd_snapshot_restore.h
src/flamenco/snapshot/fd_snapshot_restore_private.h
src/flamenco/snapshot/test_snapshot_restore.c
src/util/archive/fd_tar.h
src/util/archive/fd_tar_reader.c
src/util/archive/fuzz_tar.c

Reverts firedancer-io/firedancer#3910

Revert "snapshot: break out snapshot load"

---

src/app/fdctl/run/tiles/fd_replay.c

Assumes:
`ctx->blockstore_batch_idx_start` and `ctx->blockstore_batch_idx_end` are populated, and the end_idx is inclusive 
`parse_batch_txns` also commented out since buffered shreds are likely to not be populated, since in `deshred` we remove the buffered shreds. keeping shreds in buf_shred_map allows for `parse_batch_txns` to be called.

replay: directly retrieve transactions in entry batch from the blockstore shred map

---

src/flamenco/features/fd_features_generated.c
src/flamenco/features/fd_features_generated.h
src/flamenco/features/feature_map.json
src/flamenco/runtime/tests/run_ledger_tests_all.txt

https://github.com/anza-xyz/agave/pull/3699

flamenco: rekey enable_get_epoch_stake_syscall

---

src/flamenco/snapshot/fd_snapshot.c
src/util/sanitize/Local.mk
src/util/sanitize/fd_asan.c
src/util/sanitize/fd_asan.h
src/util/sanitize/fd_backtrace.c
src/util/sanitize/fd_backtrace.h

also fixed a bug in snapshot code

added address watch support to deepasan

---

src/app/fdctl/run/tiles/fd_batch.c
src/flamenco/runtime/context/fd_exec_slot_ctx.c
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/snapshot/fd_snapshot.c

tracking and updating of lt_hash

Implement accounts_lt_hash feature.  

---

src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_store_int.c
src/app/ledger/main.c
src/choreo/forks/fd_forks.c
src/disco/store/fd_store.c
src/disco/store/fd_store.h
src/flamenco/runtime/context/fd_exec_slot_ctx.h
src/flamenco/runtime/fd_blockstore.c
src/flamenco/runtime/fd_blockstore.h
src/flamenco/runtime/fd_rocksdb.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/fd_runtime.h
src/flamenco/shredcap/fd_shredcap.c

tested by running locally + doing getBlock RPC

blockstore: replace block_query references with shred assembly

---

README.md

Developers should run ./deps.sh with the +dev option

README: +dev for developing

---

src/app/fdctl/run/tiles/fd_replay.c
src/flamenco/snapshot/fd_snapshot.c
src/flamenco/snapshot/fd_snapshot.h

Reverts firedancer-io/firedancer#3983

Revert "snapshot: fix incremental snapshot loading"

---

src/app/fdctl/config/development.toml

Config option development.sudo was removed

Clean up old config option in development.toml

---

src/app/fdctl/run/tiles/fd_batch.c

This PR fixes a memory leak issue that eventually leads to segfault in a long run (~17 hours) of firedancer. The fix is simply adding `FD_SCRATCH_SCOPE_BEGIN/END` and updating some indentation accordingly. Let me know if I misunderstand anything. The details of the segfault are given below.
```
Thread 25 "batch:0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x77e1fe1ff640 (LWP 637556)]
fd_clock_timestamp_vote_t_map_pool_new (max=15001,
shmem=0x64e6c2b88e00)
at src/flamenco/types/../../util/tmpl/fd_pool.c:252
252       meta->free = max;
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-100.el9_4.4.x86_64 libgcc-11.5.0-2.el9.x86_64 libstdc++-11.5.0-2.el9.x86_64
(gdb) bt
#0  fd_clock_timestamp_vote_t_map_pool_new (max=15001,
shmem=0x64e6c2b88e00)
at …
```

batch: fix a mem leak issue

---

src/app/fdctl/run/run.c

Addresses https://github.com/firedancer-io/firedancer/issues/3925

fix(supervisor): gracefully handle SIGUSR1/2 

---

book/api/websocket.md
src/app/fdctl/config.c
src/app/fdctl/run/tiles/fd_plugin.c
src/app/fdctl/run/tiles/fd_poh.c
src/disco/gui/fd_gui.c
src/disco/plugin/fd_plugin.h
src/flamenco/genesis/Local.mk
src/flamenco/genesis/fd_genesis_cluster.c
src/flamenco/genesis/fd_genesis_cluster.h

Addresses https://github.com/firedancer-io/firedancer/issues/3926

gui: fetch cluster from snapshot

---

src/util/tmpl/fd_map_slot_para.c
src/util/tmpl/test_map_slot_para.c

- Added missing function prototype when doing library build.
- Added stricter testing of parallel memo iteration and fixed rising edge / falling edge mixup bug uncovered in the process.

fd_map_slot_para fixes

---

contrib/test/test-vectors-fixtures/precompile-fixtures/ed25519.list
src/flamenco/features/fd_features_generated.c
src/flamenco/features/fd_features_generated.h
src/flamenco/features/feature_map.json
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/program/fd_precompiles.c
src/flamenco/runtime/program/fd_precompiles.h

Implement `move_precompile_verification_to_svm` feature gate.

flamenco: Implement move_precompile_verification_to_svm

---

src/waltz/quic/fd_quic.c

This small PR removes the switch on version inside the packet processing loop. Instead, we just check once for UDP datagram that the version is valid, and check for each packet that it hasn't changed. Primarily cleaning/refactoring, with some small expected performance change.

Quic: Check version outside pkt processing loop

---

src/waltz/quic/crypto/fd_quic_crypto_suites.c
src/waltz/quic/crypto/fd_quic_crypto_suites.h
src/waltz/quic/fd_quic.c
src/waltz/quic/fd_quic.h
src/waltz/quic/fd_quic_conn.c
src/waltz/quic/fd_quic_conn.h
src/waltz/quic/fd_quic_private.h
src/waltz/quic/fd_quic_stream.h
src/waltz/quic/tests/fd_quic_sandbox.c
src/waltz/quic/tests/test_quic_conformance.c
src/waltz/quic/tests/test_quic_crypto.c

This PR contains several miscellaneous cleanup changes.

Misc Cleanup of the Quic Implementation

---

src/app/fdctl/run/tiles/fd_batch.c
src/app/fdctl/run/tiles/fd_replay.c
src/app/ledger/main.c
src/flamenco/rewards/fd_rewards.c
src/flamenco/rewards/fd_rewards.h
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/fd_runtime.h
src/flamenco/snapshot/fd_snapshot.c
src/flamenco/snapshot/fd_snapshot.h
src/flamenco/stakes/fd_stakes.c
src/flamenco/stakes/fd_stakes.h
src/flamenco/types/fd_types.c
src/flamenco/types/fd_types.h
src/flamenco/types/fd_types.json
src/flamenco/types/fd_types_custom.h

Co-authored-by: Manik Jain <mjain@jumptrading.com>
#4030

flamenco: tpool and optimize epoch boundary

---

src/flamenco/gossip/fd_gossip.c

gossip: refactor metrics + additional gossip documentation

---

src/flamenco/gossip/fd_gossip.c

Agave sends a sample of bloom filters (instead of the full set) in its pull requests. Preliminary analysis shows a substantial drop (several orders of magnitude) in duplicate CRDS value received rates without affecting unique received rates (across a minute long time interval), so this is a good win for us traffic wise. The tile itself is still saturated with sigverifies since the unique value rate is unchanged.

gossip: send sample of bloom filters in pull requests

---

src/app/fdctl/Local.mk
src/app/fdctl/fdctl.h
src/app/fdctl/main1.c
src/app/fddev/Local.mk
src/app/fddev/fddev.h
src/app/fddev/main1.c
src/app/fddev/spy.c

Fixes https://github.com/firedancer-io/firedancer/issues/4201

fdctl: move spy to fddev

---

src/app/fdctl/config/default.toml

Document https://github.com/firedancer-io/firedancer/pull/4018

fdctl: add sigusr doc

---

src/app/fdctl/run/tiles/cswtch.seccomppolicy
src/app/fdctl/run/tiles/fd_cswtch.c
src/app/fdctl/run/tiles/generated/cswtch_seccomp.h
src/disco/netlink/fd_netlink_tile.c

Also fix netlnk tile heartbeat flickering

Reduce cswtch tile CPU usage

---

src/app/fdctl/run/tiles/fd_pack.c

Consider this situation:
1. Schedule a bundle or transaction to bank 0
2. Pacing says it's okay to use bank 1, so the next transaction we try to schedule goes to bank 1.  We do find a non-bundle transaction to schedule there.
3. Bank 0 completes, so we attempt to schedule something else to bank 0, but the next transaction is a bundle that conflicts with what is running on bank 1.  schedule_next_microblock returns empty, and bank 0 remains idle.
4. Bank 1 completes, but the pack tile continues trying to schedule to bank 0 (it always tries the first available), so we never call fd_pack_microblock_complete on bank 1. pack continues to thinks the transaction on bank is still going.
The only thing that gets us out of this state is ending the block.

pack: complete microblock as soon as bank is ready

---

src/flamenco/runtime/tests/fd_exec_sol_compat.c

Adds back in this fuzzing target which was accidentally removed.

add sol_compat_elf_loader_v1

---

src/app/fdctl/Local.mk
src/app/fdctl/config.h
src/app/fdctl/config/default-firedancer.toml
src/app/fdctl/config_parse.c
src/app/fdctl/main.c
src/app/fdctl/run/tiles/fd_gossip.c
src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_restart.c
src/app/fdctl/run/tiles/fd_store_int.c
src/app/fdctl/run/topos/fd_firedancer.c
src/app/fddev/main1.c
src/disco/restart/test/restart_agave.sh
src/disco/restart/test/restart_fd.sh
src/disco/topo/fd_topo.h
src/flamenco/runtime/fd_runtime_init.c

Move most of the wen-restart logic from replay tile to a separate tile, so replay tile can purely do replay.

Move wen-restart into a new tile

---

src/disco/pack/fd_pack.c

A test fails unless #4346 is also included.

pack: fix delete_worst

---

.github/actions/deps/action.yml
.github/workflows/clusterfuzz.yml
.github/workflows/codeql.yml
.github/workflows/coverage_report.yml
.github/workflows/coverage_report_clusterfuzz.yml
.github/workflows/ledgers.yml
.github/workflows/test_firedancer_localnet.yml
.github/workflows/test_firedancer_testnet.yml
.github/workflows/test_firedancer_testnet_shredcap.yml
.github/workflows/tests.yml

ci: run tests without dev dependencies

---

src/flamenco/runtime/tests/run_ledger_tests_all.txt

fixed by https://github.com/firedancer-io/firedancer/pull/4419

flamenco: add vote bhm fix

---

src/app/fdctl/run/tiles/fd_poh_int.c
src/app/fdctl/run/tiles/fd_replay.c
src/app/fdctl/run/tiles/fd_shred.c
src/app/fdctl/run/tiles/fd_store_int.c
src/app/fdctl/run/topos/fd_firedancer.c
src/disco/fd_disco_base.h
src/disco/topo/fd_topo.h

First pass at merging in #4401 piecemeal

feat(replay): add shred replay link

---

src/disco/shred/fd_fec_resolver.c
src/disco/shred/fd_fec_resolver.h
src/disco/shred/fd_shred_tile.c
src/disco/shred/test_fec_resolver.c

feat(shred): return merkle root in fec set resolver

---

src/app/fdctl/topos/fd_firedancer.c
src/app/shared_dev/commands/spy.c
src/disco/topo/fd_topo.h
src/discof/gossip/fd_gossip_tile.c
src/flamenco/gossip/fd_gossip.c
src/flamenco/gossip/fd_gossip.h
src/flamenco/gossip/fd_gossip_spy.c

Send out contact info v2 in pull requests, which is a requirement in agave v2.2

flamenco, gossip: migrate gossip library contact info to v2

---

src/wiredancer/rtl/sha512_pre.sv
src/wiredancer/sim/sha512_pre/test.py

Adding wiredancer sha512_pre.sv + unit-test update

---

src/discof/batch/fd_batch_tile.c
src/flamenco/features/fd_features_generated.c
src/flamenco/features/fd_features_generated.h
src/flamenco/features/feature_map.json
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/fd_hashes.h
src/flamenco/runtime/fd_runtime.c

simd change: https://github.com/solana-foundation/solana-improvement-documents/pull/265
agave change: https://github.com/anza-xyz/agave/pull/5336
feature change: https://github.com/anza-xyz/solana-sdk/pull/79

lthash_update: SIMD-215 changes

---

contrib/test/test-vectors-fixtures/cpi-fixtures/cpi.list
src/flamenco/vm/syscall/fd_vm_syscall_cpi_common.c

- **flamenco: (cpi) delay account meta presence checks to fd_vm_prepare**

flamenco: cpi delay acc meta presence checks

---

src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_txn_account.h
src/flamenco/runtime/tests/fd_exec_instr_test.c

This field is not used anywhere

fuzz, flamenco: remove `starting_owner_dlen` from txn account

---

src/util/tmpl/fd_map_para.c

Documentation says FD_MAP_AGAIN, code defines FD_MAP_ERR_AGAIN

fix fd_map_para error docs

---

.github/workflows/tests.yml

Reverts firedancer-io/firedancer#4689

Revert "workflows: run CPI in test-vectors"

---

src/discof/replay/fd_replay_tile.c

We do not support snapshot creation in Firedancer V1, so we do not need this logic anymore.

replay: remove double constipation concept

---

src/util/tmpl/fd_map_para.c

The check for ele_max is to align it with the general check stucture and the checks in txn_init. Other than that, just drive typos, fixed during auditing

fd_map_para nits

---

src/flamenco/runtime/fd_executor.c

flamenco: fix for loop checking validated_loaders when loading accounts

---

src/flamenco/runtime/fd_runtime.c

Note: ledger test will be added later once cost tracker works

flamenco: fix mismatch where nonce account is fee payer

---

src/flamenco/runtime/context/fd_capture_ctx.c
src/flamenco/runtime/context/fd_capture_ctx.h
src/flamenco/runtime/fd_blockstore.h
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/fd_hashes.h
src/flamenco/runtime/fd_runtime.c

Fixes several race conditions in ledger replay solcap.

runtime, capture: fix solcap race conditions

---

src/flamenco/runtime/fd_runtime.c

This fixes an issue where calculating the EHA in offline replay would deadlock, because of a lock re-entrancy bug.

replay, hashes: fix EAH deadlock

---

contrib/codegen/generate_filters.py

Nan from Zellic reported that the unused bit-and operator does not
work.  The offending code is removed.
As a general rule, we only keep functionality in the seccomp
policy compiler that is actually used.

Remove bit-and from seccomp compiler

---

src/util/bits/Local.mk
src/util/bits/fd_bits.h
src/util/bits/fd_bits_tg.h
src/util/bits/test_bits_tg.c
src/util/simd/fd_avx512_wwi.h
src/util/simd/fd_avx512_wwu.h
src/util/tpool/fd_tpool.h

And a drive by cleanup to simd (missing "do") and tpool (used more optimal splitting for thread dispatch).

Type generic version of fd_bits

---

src/discof/exec/fd_exec_tile.c
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/fd_runtime.c

chore: remove wrong FD_PARAM_UNUSED

---

src/discoh/bank/fd_bank_tile.c

waiting on https://github.com/firedancer-io/firedancer/pull/4710

bank: strictly enforce cu invariant

---

src/disco/gui/fd_gui_printf.c

Commit hash in the gui is broken on main, this fixes it.

gui: missing include version

---

src/flamenco/capture/fd_solcap_dump.c
src/flamenco/runtime/tests/Local.mk
src/flamenco/runtime/tests/fetch_and_generate.sh
src/flamenco/runtime/tests/harness/fd_exec_sol_compat.c
src/flamenco/runtime/tests/harness/fd_exec_sol_compat.h
src/flamenco/runtime/tests/harness/fd_types_harness.c
src/flamenco/runtime/tests/harness/fd_types_harness.h
src/flamenco/runtime/tests/harness/generated/type.pb.c
src/flamenco/runtime/tests/harness/generated/type.pb.h

Re-working differential types fuzzer to work with our conformance tooling.

fuzz: re-work differential types fuzzer

---

src/discof/replay/fd_replay_tile.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/sysvar/fd_sysvar_slot_hashes.c

and bring back some code from the dead...

fd_runtime_read_genesis: use new types decode conventions to decode genesis_block

---

src/discof/replay/fd_replay_tile.c
src/flamenco/runtime/fd_hashes.c
src/flamenco/runtime/fd_hashes.h
src/flamenco/runtime/fd_runtime.c

addresses comments in https://github.com/firedancer-io/firedancer/pull/4864

flamenco: dedup update_hash_bank code

---

book/guide/getting-started.md
book/guide/initializing.md
src/app/fdctl/commands/run_agave.c
src/app/fdctl/config/default.toml
src/app/fdctl/config/development.toml
src/app/fdctl/topology.c
src/app/firedancer-dev/commands/gossip.c
src/app/firedancer-dev/commands/sim.c
src/app/firedancer/topology.c
src/app/shared/commands/configure/ethtool-channels.c
src/app/shared/commands/configure/ethtool-gro.c
src/app/shared/commands/configure/ethtool-loopback.c
src/app/shared/commands/configure/sysctl.c
src/app/shared/commands/run/run.c
src/app/shared/fd_config.c
src/app/shared/fd_config.h
src/app/shared/fd_config_parse.c
src/app/shared_dev/commands/bench/bench.c
src/app/shared_dev/commands/dev.c
src/app/shared_dev/commands/load.c
src/app/shared_dev/commands/pktgen/pktgen.c
src/app/shared_dev/commands/txn.c
src/disco/net/fd_net_tile.h
src/disco/net/fd_net_tile_topo.c
src/waltz/xdp/fd_xsk.c

Backport to v0.5
Co-authored-by: Michael McGee <mmcgee@jumptrading.com>

net 2.0: refactor net config

---

src/app/firedancer-dev/commands/gossip.c
src/app/firedancer-dev/commands/sim.c
src/app/shared/commands/configure/hyperthreads.c
src/app/shared/commands/keys.c
src/app/shared/commands/monitor/monitor.c
src/app/shared/commands/set_identity.c
src/app/shared_dev/commands/bench/fd_benchs.c
src/disco/gui/fd_gui_tile.c
src/disco/pack/fd_pack.c
src/disco/shred/fd_shred_dest.c
src/discof/gossip/fd_gossip_tile.c
src/discof/repair/fd_repair_tile.c
src/discof/replay/fd_replay_tile.c
src/discof/rpcserver/fd_block_to_json.c
src/discof/rpcserver/fd_rpc_service.c
src/discoh/poh/fd_poh_tile.c
src/flamenco/repair/fd_repair.c
src/flamenco/runtime/program/fd_builtin_programs.c
src/flamenco/runtime/program/fd_loader_v4_program.c
src/flamenco/runtime/tests/harness/fd_types_harness.c

Removes some global symbols that are not properly namespaced

Fix symbol visibility

---

src/app/shared/commands/configure/sysctl.c

fdctl: allow missing numa_balancing sysctl

---

src/app/shared/boot/fd_boot.c
src/app/shared/commands/help.c
src/app/shared_dev/boot/fd_dev_boot.c

agave [diff](https://github.com/firedancer-io/agave/compare/afc9e91..jherrera/0.5-fixes)

v0.5: fix deprecation warning, --version flag

---

src/flamenco/gossip/fd_gossip.c
src/flamenco/gossip/fd_gossip.h

Untested since fd_gossip doesn't have tests

gossip: support tpu vote quic

---

src/app/shared/boot/fd_boot.c
src/app/shared/commands/help.c
src/app/shared_dev/boot/fd_dev_boot.c

#4974 was merged to v0.5 but not to main.

fdctl: allow --version flag

---

src/funk/fd_funk_rec.c
src/funk/fd_funk_rec.h

the contract promises FD_FUNK_ERR_KEY in this case

funk: fix return code in fd_funk_rec_remove

---

src/discof/repair/fd_repair_tile.c
src/flamenco/types/fd_fuzz_types.h
src/flamenco/types/fd_types.c
src/flamenco/types/fd_types.h
src/flamenco/types/fd_types.json

from @ibhatt-jumptrading 's https://github.com/firedancer-io/firedancer/compare/types_local?expand=1

flamenco: fix repair request hdr

---

src/flamenco/runtime/fd_blockstore.c

@lidatong please carefully review that the fix is now correct

blockstore: fix eqvoc check + check expected shred type

---

src/waltz/quic/fd_quic_pretty_print.c
src/waltz/quic/templ/fd_quic_pretty_print.h

Some bugs and cleanups. More compatible with python syntax, particularly in the event of a QUIC parse error

quic - some pretty print fixes

---

src/choreo/tower/fd_tower.h

This small PR fixes a few examples in fd_tower.h docs.

towerdocs: minor fixes

---

.github/workflows/codeql.yml

Fixes #5029 
Also made some updates/corrections to the workflow file. This works on a manual run ([link to successful run](https://github.com/firedancer-io/firedancer/actions/runs/14856403723/job/41710682989)), will monitor after merging to see if there are any issues from the scheduled run.

codeql: allow uploading SARIF file to GH Code Scanning

---

src/app/shared_dev/commands/bench/fd_bencho.c
src/discof/poh/fd_pohi_tile.c
src/discof/replay/fd_replay_tile.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/fd_runtime.h

initialize POH correctly
enable the features we want on by default
cleanup unused memory
rename some functions for easier breakpoints or tracing

flamenco/bench:  progress on firedancer-dev bench

---

src/discof/replay/fd_replay_tile.c

Fix for calculating hashes in live client when number of hashes is small. `firedancer-dev backtest` caught this! 🎉

replay: fix lthash when number of account is small

---

src/flamenco/runtime/program/fd_loader_v4_program.c

https://github.com/anza-xyz/agave/pull/5997

flamenco: update loader v4 `deploy` to v2.2.13 implementation

---

src/waltz/quic/fd_quic.c

Cherry-picks 33ae9c9b085fa1425cedb343112e1d63f198713e onto v0.5.

Quic: Fix tls_hs eviction segfault

---

src/flamenco/runtime/sysvar/fd_sysvar_epoch_rewards.c

agave does the same https://github.com/anza-xyz/agave/blob/b9c9ecccbb05d9da774d600bdbef2cf210c57fa8/runtime/src/bank/partitioned_epoch_rewards/sysvar.rs#L36-L43

sysvar: move assert after potential assignment

---

src/disco/shred/fd_shred_tile.c

`ctx->store_out_idx` is used on line 1024.

shred: initialize store_out_idx earlier

---

src/flamenco/runtime/tests/harness/fd_block_harness.c

Hopefully this logic should go away soon if we look into removing the vote timestamps cache

fuzz: populate vote timestamps cache from epoch stakes

---

book/.vitepress/theme/custom.css
book/.vitepress/theme/index.js
book/api/metrics-generated.md
src/disco/metrics/generate/write_docs.py

book: make metrics-generated.md more readable

---

src/flamenco/features/fd_features_generated.c
src/flamenco/features/fd_features_generated.h
src/flamenco/features/feature_map.json
src/flamenco/runtime/program/fd_zk_elgamal_proof_program.c

https://github.com/anza-xyz/agave/pull/6545

zk-sdk: feature gates to disable and reenable zk elgamal proof program

---

src/discof/forest/fd_forest.c
src/discof/forest/fd_forest.h
src/discof/forest/test_forest.c
src/discof/repair/fd_repair_tile.c
src/flamenco/repair/fd_repair.h

not benchmarked, looks reasonably on the order of / if not faster than first iteration changes

forest: iterator API for repair requesting one shred at a time

---

src/flamenco/runtime/program/fd_bpf_loader_program.c

fd_ulong_sat_add with one operand >0 guranttes heap_size!=0

flamenco: remove unreachable check in calculate_heap_cost

---

src/waltz/quic/fd_quic_ack_tx.c

This PR adds a probe in gen_ack frames that reports how many ack ranges were sent, whether the buffer was fully flushed, and the enc level.

quic: probe gen_ack_frames

---

src/discof/replay/fd_replay_tile.c
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/sysvar/fd_sysvar_slot_history.c
src/flamenco/types/fd_types.c
src/flamenco/types/gen_stubs.py

Small fixes to enable booting from genesis.

replay, runtime: fix genesis booting

---

src/util/log/fd_log.c

increasing to match topo print buf

log: increase buf size

---

src/app/shared/boot/fd_boot.c
src/app/shared/commands/mem.c
src/app/shared/commands/monitor/monitor.c
src/app/shared/commands/netconf.c
src/app/shared/commands/ready.c
src/app/shared/commands/run/run.c
src/app/shared/commands/set_identity.c
src/app/shared/commands/version.c
src/app/shared/fd_action.h

Note that `fddev` does not include this check, so e.g. `fddev mem` still works

app: only certain subcommands require config

---

src/flamenco/runtime/program/zksdk/instructions/fd_zksdk_percentage_with_cap.c

See https://github.com/anza-xyz/agave/pull/6523/files#diff-2d6b8b55bf791cc2df6dc74b3ec5d258889993107436265228aeebd8d75ca229

zk-sdk: add c_max_proof to the sigma proof transcript

---

src/app/firedancer-dev/config/default.toml

Minor changes needed for testnet

tweaks for default.toml

---

src/flamenco/types/fd_bincode.h
src/flamenco/types/fd_types.c
src/flamenco/types/fd_types.h
src/flamenco/types/fd_types.json
src/flamenco/types/fd_types_custom.c
src/flamenco/types/fd_types_custom.h
src/flamenco/types/gen_stubs.py
src/flamenco/types/test_types_fixtures.c

flameco,types: implement fd_sanitize_entries

flameco,types: Add late stage deserialization error checking

---

src/flamenco/types/fd_bincode.h
src/flamenco/types/fd_types.c
src/flamenco/types/fd_types.h
src/flamenco/types/fd_types.json
src/flamenco/types/fd_types_custom.c
src/flamenco/types/fd_types_custom.h
src/flamenco/types/gen_stubs.py
src/flamenco/types/test_types_fixtures.c

This reverts commit 5224cf73e838141e9c5a0c787176ea26c3b81a9f.

Revert "flameco,types: Add late stage deserialization error checking"

---

src/flamenco/rewards/Local.mk
src/flamenco/rewards/fd_epoch_rewards.c
src/flamenco/rewards/fd_epoch_rewards.h
src/flamenco/rewards/test_epoch_rewards.c

adding unit tests and some additional sanity checks

epoch_rewards: adding unit tests

---

src/disco/gui/fd_gui.c

Fixes a segfault in previous commit

bundle, gui: add tile card + primary metric pt2

---

src/disco/gui/fd_gui.c
src/disco/gui/sankey_debug.py

removes success_insert_*_replace metrics since these are included in transaction_deleted

gui: fix sankey accounting

---

src/app/shared_dev/commands/quic_trace/fd_quic_trace_main.c

quic_trace used the quic_conn_at_idx helper, which relied on state->conn_base. But that address was in the quic_tile's address space, not translated to the local address space. This PR fixes the resulting segfault.

quic_trace: fix conn_at_idx

---

src/discof/exec/fd_exec_tile.c
src/discof/writer/fd_writer_tile.c
src/flamenco/runtime/fd_executor.c
src/flamenco/runtime/fd_executor.h
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/fd_runtime.h
src/flamenco/runtime/tests/harness/fd_block_harness.c
src/flamenco/runtime/tests/harness/fd_block_harness.h
src/flamenco/runtime/tests/harness/fd_txn_harness.c
src/flamenco/runtime/tests/harness/fd_txn_harness.h
src/flamenco/runtime/tests/test_exec_sol_compat.c

Removes dead fuzz-specific code that was previously used in ledger replay

flamenco, fuzz: consolidate fuzzing harnesses with production code

---

src/disco/shred/fd_stake_ci.c
src/disco/shred/fd_stake_ci.h
src/disco/shred/test_stake_ci.c

stake_ci: add APIs for updating or removing individual contact info entries

---

src/choreo/eqvoc/fd_eqvoc.h
src/flamenco/gossip/Local.mk
src/flamenco/gossip/fd_gossip_types.h

For use in gossipv2 and out link consumers

gossip2: public type definitions

---

src/waltz/quic/fd_quic.c
src/waltz/quic/tests/test_quic_keep_alive.c

This PR fixes a quic regression where quic config->keep_timed_out == 0 means we neither call conn_final nor free the timed out connection. 1.5 quic_tile is unaffected, running with keep_timed_out==1.

quic: free timed out conn when not keep_timed_out

---

src/discof/replay/fd_replay_tile.c

Saves about 7 cache lines.  Also prepares for an upcoming commit where we need to easily check whether the execution pipeline is fully drained for safe publishing of some shared data structures.

replay: use bitset for exec tile state tracking

---

src/app/firedancer-dev/commands/backtest.c
src/app/firedancer-dev/commands/repair.c
src/discof/restore/fd_snapin_tile.c
src/discof/restore/utils/fd_snapshot_parser.c
src/discof/restore/utils/fd_snapshot_parser.h
src/discof/restore/utils/fd_ssmsg.h
src/discof/restore/utils/fuzz_snapshot_parser.c
src/discof/shredcap/fd_shredcap_tile.c

fixing bug in d5e37f247004a37394cf7515ee281cf4cf7267bd

snapshot: sizing out links on all topologies for manifest

---

src/discof/gossip/fd_gossvf_tile.c

gossfv: bounds check stakes link input

---

src/waltz/quic/tests/test_quic_pkt_meta.c

parameterizes and fixes quic_pkt_meta's wksp allocation

quic: fix test_quic_pkt_meta

---

src/disco/shred/fd_shred_tile.c
src/disco/store/fd_store.h
src/discof/repair/fd_repair_tile.c
src/discof/replay/fd_replay_tile.c

store: auto cleanup store lock

---

src/discof/gossip/fd_gossvf_tile.c
src/flamenco/gossip/fd_gossip_msg_parse.c

Originally I suspected there to be a DoS vector, however this is not the case, since the older validator is stopped.
Changed this to keep the other smaller fixes.

gossip: parser readability + push msg recency window to match agave

---

src/discof/gossip/fd_gossvf_tile.c

by definition of FD_STAKE_CI_STAKE_MSG_SZ we can express this equivalently

gossip: simplify stake link bounds check

---

src/discof/replay/Local.mk
src/discof/replay/fd_rdisp.c
src/discof/replay/fd_rdisp.h
src/discof/replay/fd_rdisp_simple.c
src/discof/replay/rdisp_format_block_for_test.py
src/discof/replay/test_rdisp.c

(PR ready for review. Just marked as draft because it depends on the slist commit)

replay: add replay dispatcher

---

src/discof/replay/fd_sched.c

tested on ledger mainnet-364974841 slot 365125180

replay: fix buffer overflow in scheduler

---

contrib/tango.lua
src/app/shared/fd_action.h
src/app/shared_dev/commands/dump.c
src/disco/stem/fd_stem.c
src/disco/topo/fd_topo.h
src/util/net/fd_pcap.c
src/util/net/fd_pcap.h

- Also fix some issues in tango.lua wireshark dissector

fddev/dump: add realtime / continuous mode

---

book/api/websocket.md
src/app/firedancer/topology.c
src/disco/gui/fd_gui.c
src/disco/gui/fd_gui.h
src/disco/gui/fd_gui_printf.c
src/disco/gui/fd_gui_printf.h
src/disco/gui/fd_gui_tile.c

- add max known slot and catchup slot messages
- full-client only

gui: track when we've caught up

---

src/app/shared_dev/commands/dump.c

This is not perfect, as some tiles do not populate tspub at all, or use some other value than fd_tickcount(). Additionally, if the original tspub was taken more than ~2s away from when the dump tool reads it, the timestamp decompression will return an incorrect result. Regardless, this should be more useful than putting the tango seq in the timestamp field and yields the expected result for the vast majority of frags.

dump: output wallclock timestamps in realtime mode

---

src/discof/replay/fd_exec.h
src/discof/replay/fd_replay_tile.c
src/discof/restore/utils/fd_ssload.c
src/discof/restore/utils/fd_ssload.h
src/discof/writer/fd_writer_tile.c
src/flamenco/runtime/context/fd_capture_ctx.h
src/flamenco/runtime/fd_runtime.c

not removing in runtime to avoid merge conflicts with database effort. just an initial pr to remove it from the replay tile

replay: remove tile-level slot_ctx

---

src/discof/restore/fd_snaprd_tile.c

We should not leave temporary files in the user's snapshot directory so we can cleanly run backtest and auto-update ledgers.

snapshots: remove temp files

---

src/discof/replay/fd_replay_tile.c
src/flamenco/runtime/fd_bank.c
src/flamenco/runtime/fd_bank.h
src/flamenco/runtime/fd_runtime.c
src/flamenco/runtime/sysvar/test_sysvar_cache.c
src/flamenco/runtime/test_bank.c
src/flamenco/runtime/tests/fd_block_harness.c

brings banks footprint for 1024 banks to 64gb

banks: moving cost tracker to pool & pool lock fix
